# Marketing Strategy PhD skills
What's unique about my approach? Mixing the oriental and western PhD training. 

1)  Chinese scholars are better at summarizing the teaching/ standardizing
2)  American scholars are better at originality/ high quality questions

## Reading

### Meta skill to gain 
1) Screen information quickly in this information overload age 

2) Figure content with enough depth by discussing with other people/ expert screening 
3) Acquire the beginner to expert mindset, so that you can be the teacher to give feedback to students 

### Reading Purpose

#### Conversant reading/ narrow
1) build a system of knowledge mgmt - in R book or Notion (30 mins summary)
2) Extract word, logic and structure of the papers in your field (90-120 mins read) - variables, measurement, method, research design, theory
3) Practice screening information to see the big picture (10 mins skim)

How to train: detailed note. 2 pgs on one paper + challenger reading + response paper on several key conversant 

Two types of papers: 
1) Theory paper 
a) gist of thesis b) logic of the argument c) propositions 

2) Empirical paper
a) gist of RQ b) logic of argument c) hypothesis - key finding d) Method, measure

#### Get to know a field/ broad

How to train: abstract summary. 1 pgs on multiple papers.  

#### Method/ sectioning

#### Hobby/ creative


### How to train

1)  

2)  

### Suggested reading (optional)

## Writing
