<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Applied Stats Model II - Exam Two STAT 4520/7520 - Exam 2 | Frank’s second book</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Applied Stats Model II - Exam Two STAT 4520/7520 - Exam 2 | Frank’s second book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Applied Stats Model II - Exam Two STAT 4520/7520 - Exam 2 | Frank’s second book" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Frank Lin" />


<meta name="date" content="2022-05-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="applied-stats-model-ii---exam-1.html"/>
<link rel="next" href="asm2-hw-term-project.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Frank second book</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html"><i class="fa fa-check"></i><b>1</b> Selling and buying process:</a>
<ul>
<li class="chapter" data-level="1.1" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salespeople-skill-perception"><i class="fa fa-check"></i><b>1.1</b> Salespeople skill/ perception</a></li>
<li class="chapter" data-level="1.2" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#communication---intraorganization"><i class="fa fa-check"></i><b>1.2</b> Communication - intraorganization</a></li>
<li class="chapter" data-level="1.3" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#communication-interorganization---fle-interactions"><i class="fa fa-check"></i><b>1.3</b> Communication Interorganization - FLE interactions</a></li>
<li class="chapter" data-level="1.4" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#sales-marketing-interface"><i class="fa fa-check"></i><b>1.4</b> Sales marketing interface</a></li>
<li class="chapter" data-level="1.5" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#firm-level-impact-on-salespeople"><i class="fa fa-check"></i><b>1.5</b> Firm level impact on salespeople</a></li>
<li class="chapter" data-level="1.6" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salesperson-trait-orientation"><i class="fa fa-check"></i><b>1.6</b> Salesperson trait orientation</a></li>
<li class="chapter" data-level="1.7" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salesperson-non-sales-activity-service"><i class="fa fa-check"></i><b>1.7</b> Salesperson non-sales activity/ service</a></li>
<li class="chapter" data-level="1.8" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#b2g-selling"><i class="fa fa-check"></i><b>1.8</b> B2G selling</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="literature-review-note.html"><a href="literature-review-note.html"><i class="fa fa-check"></i><b>2</b> Literature Review Note</a>
<ul>
<li class="chapter" data-level="2.1" data-path="literature-review-note.html"><a href="literature-review-note.html#persuasion-knowledge-model-review"><i class="fa fa-check"></i><b>2.1</b> Persuasion knowledge Model Review</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="literature-review-note.html"><a href="literature-review-note.html#summary-for-pkm-in-online-environment"><i class="fa fa-check"></i><b>2.1.1</b> Summary for PKM in online environment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html"><i class="fa fa-check"></i><b>3</b> Database marketing substantive domain</a>
<ul>
<li class="chapter" data-level="3.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#key-issues"><i class="fa fa-check"></i><b>3.1</b> Key Issues</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#data-privacy"><i class="fa fa-check"></i><b>3.1.1</b> Data Privacy</a></li>
<li class="chapter" data-level="3.1.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#customer-lifetime-value-ltv"><i class="fa fa-check"></i><b>3.1.2</b> Customer lifetime value (LTV)</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#method"><i class="fa fa-check"></i><b>3.2</b> Method</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#rfm"><i class="fa fa-check"></i><b>3.2.1</b> RFM</a></li>
<li class="chapter" data-level="3.2.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#market-basket-analysis"><i class="fa fa-check"></i><b>3.2.2</b> Market basket analysis</a></li>
<li class="chapter" data-level="3.2.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#collaborative-filtering"><i class="fa fa-check"></i><b>3.2.3</b> Collaborative filtering</a></li>
<li class="chapter" data-level="3.2.4" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#cluster-analysis"><i class="fa fa-check"></i><b>3.2.4</b> Cluster analysis</a></li>
<li class="chapter" data-level="3.2.5" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#decision-trees"><i class="fa fa-check"></i><b>3.2.5</b> Decision trees</a></li>
<li class="chapter" data-level="3.2.6" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#machine-learning"><i class="fa fa-check"></i><b>3.2.6</b> Machine learning</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#sub---substantive-areas"><i class="fa fa-check"></i><b>3.3</b> Sub - substantive areas</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#acquisition"><i class="fa fa-check"></i><b>3.3.1</b> Acquisition</a></li>
<li class="chapter" data-level="3.3.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#retention-churn-management"><i class="fa fa-check"></i><b>3.3.2</b> Retention/ Churn management</a></li>
<li class="chapter" data-level="3.3.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#cross-selling-and-up-selling"><i class="fa fa-check"></i><b>3.3.3</b> Cross-selling and up-selling</a></li>
<li class="chapter" data-level="3.3.4" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#reward-program"><i class="fa fa-check"></i><b>3.3.4</b> Reward program</a></li>
<li class="chapter" data-level="3.3.5" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#multichannel-customer"><i class="fa fa-check"></i><b>3.3.5</b> Multichannel customer</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-scientist-job.html"><a href="data-scientist-job.html"><i class="fa fa-check"></i><b>4</b> Data Scientist Job</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#business-strategy-track-a.k.a-marketing-analytics"><i class="fa fa-check"></i><b>4.1</b> Business strategy Track (a.k.a Marketing Analytics)</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#database-marketing"><i class="fa fa-check"></i><b>4.1.1</b> Database marketing</a></li>
<li class="chapter" data-level="4.1.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#programming"><i class="fa fa-check"></i><b>4.1.2</b> Programming</a></li>
<li class="chapter" data-level="4.1.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#statistics"><i class="fa fa-check"></i><b>4.1.3</b> Statistics:</a></li>
<li class="chapter" data-level="4.1.4" data-path="data-scientist-job.html"><a href="data-scientist-job.html#visualization"><i class="fa fa-check"></i><b>4.1.4</b> Visualization</a></li>
<li class="chapter" data-level="4.1.5" data-path="data-scientist-job.html"><a href="data-scientist-job.html#automation"><i class="fa fa-check"></i><b>4.1.5</b> Automation</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#consumer-insight-track-aka.-marketing-research"><i class="fa fa-check"></i><b>4.2</b> Consumer insight Track (aka. Marketing Research)</a></li>
<li class="chapter" data-level="4.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#optimization-track-a.k.a-operational-research"><i class="fa fa-check"></i><b>4.3</b> Optimization Track (a.k.a Operational Research)</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#model-optimization"><i class="fa fa-check"></i><b>4.3.1</b> Model optimization</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#macro-level-models"><i class="fa fa-check"></i><b>4.3.2</b> Macro level models</a></li>
<li class="chapter" data-level="4.3.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#academic-paper-implementation"><i class="fa fa-check"></i><b>4.3.3</b> Academic Paper implementation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html"><i class="fa fa-check"></i><b>5</b> Marketing Strategy PhD skills</a>
<ul>
<li class="chapter" data-level="5.1" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#reading"><i class="fa fa-check"></i><b>5.1</b> Reading</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#meta-skill-to-gain"><i class="fa fa-check"></i><b>5.1.1</b> Meta skill to gain</a></li>
<li class="chapter" data-level="5.1.2" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#reading-purpose"><i class="fa fa-check"></i><b>5.1.2</b> Reading Purpose</a></li>
<li class="chapter" data-level="5.1.3" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#how-to-train"><i class="fa fa-check"></i><b>5.1.3</b> How to train</a></li>
<li class="chapter" data-level="5.1.4" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#suggested-reading-optional"><i class="fa fa-check"></i><b>5.1.4</b> Suggested reading (optional)</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#writing"><i class="fa fa-check"></i><b>5.2</b> Writing</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html"><i class="fa fa-check"></i><b>6</b> Applied Stats Model II - Exam 1</a>
<ul>
<li class="chapter" data-level="6.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-in-a-poisson-regression-problem-with-one-explanatory-variable-x-the-estimate-of-the-β"><i class="fa fa-check"></i><b>6.1</b> 1. (7 points) In a poisson regression problem with one explanatory variable x, the estimate of the β</a></li>
<li class="chapter" data-level="6.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-in-a-generalized-linear-model-why-is-the-null-deviance-typically-larger-than-the-residual-deviance"><i class="fa fa-check"></i><b>6.2</b> 2. (5 points) In a generalized linear model, why is the null deviance typically larger than the residual deviance?</a></li>
<li class="chapter" data-level="6.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-can-standard-linear-regression-ever-be-used-when-the-data-are-counts-explain-why-or-why-not."><i class="fa fa-check"></i><b>6.3</b> 3. (5 points) Can standard linear regression ever be used when the data are counts? Explain why or why not.</a></li>
<li class="chapter" data-level="6.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#take-the-following-random-effect-model"><i class="fa fa-check"></i><b>6.4</b> 4. Take the following random effect model</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#section"><i class="fa fa-check"></i><b>6.4.1</b> </a></li>
<li class="chapter" data-level="6.4.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-find-the-intra-class-correlation-coefficient."><i class="fa fa-check"></i><b>6.4.2</b> (3 points) Find the intra class correlation coefficient.</a></li>
<li class="chapter" data-level="6.4.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-which-level-of-the-random-effect-α-will-have-the-largest-predicted-value"><i class="fa fa-check"></i><b>6.4.3</b> (2 points) Which level of the random effect α will have the largest predicted value?</a></li>
<li class="chapter" data-level="6.4.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-predict-y-for-level-6-of-the-random-effect."><i class="fa fa-check"></i><b>6.4.4</b> (2 points) Predict y for level 6 of the random effect.</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#utilizing-the-below-code-and-output-answer-the-following"><i class="fa fa-check"></i><b>6.5</b> 5. Utilizing the below code and output, answer the following:</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-why-are-the-residual-and-null-deviance-values-the-same"><i class="fa fa-check"></i><b>6.5.1</b> • (3 points) Why are the residual and null deviance values the same?</a></li>
<li class="chapter" data-level="6.5.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-based-on-these-deviance-values-does-the-model-fit-well-does-this-make-sense"><i class="fa fa-check"></i><b>6.5.2</b> • (2 points) Based on these deviance values, does the model “fit” well? Does this make sense?</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#take-the-data-given-by-problem6data.csv-which-contains-a-continuous-response-y-and-two-predictors-x1-and-x2."><i class="fa fa-check"></i><b>6.6</b> 6. Take the data given by Problem6Data.csv, which contains a continuous response y and two predictors x1 and x2.</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#a.-5-points-read-the-data-into-r-and-make-some-plots-between-the-response-and-predictors.-describe-the-patterns-and-comment-on-behaviors-you-observe-with-exact-0s."><i class="fa fa-check"></i><b>6.6.1</b> a. (5 points) Read the data into R and make some plots between the response and predictors. Describe the patterns and comment on behaviors you observe with exact 0s.</a></li>
<li class="chapter" data-level="6.6.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#b.-5-points-make-a-histogram-of-the-response-variable-and-comment-on-the-shape.-are-the-values-strictly-positive"><i class="fa fa-check"></i><b>6.6.2</b> b. (5 points) Make a histogram of the response variable and comment on the shape. Are the values strictly positive?</a></li>
<li class="chapter" data-level="6.6.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#c.-4-points-state-the-range-that-the-index-parameter-p-for-use-in-the-tweedie-distribution-must-be-contained-in.-why-is-this-the-case"><i class="fa fa-check"></i><b>6.6.3</b> c. (4 points) State the range that the index parameter p, for use in the Tweedie distribution, must be contained in. Why is this the case?</a></li>
<li class="chapter" data-level="6.6.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#d.-6-points-find-an-optimal-value-of-p-for-use-in-the-tweedie-distribution-using-a-log-link."><i class="fa fa-check"></i><b>6.6.4</b> d. (6 points) Find an optimal value of p for use in the Tweedie Distribution, using a log link.</a></li>
<li class="chapter" data-level="6.6.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#e.-5-points-again-using-a-log-link-fit-a-tweedie-distribution-using-the-index-parameter-value-you-obtained-in-part-d."><i class="fa fa-check"></i><b>6.6.5</b> e. (5 points) Again using a log link, fit a Tweedie Distribution using the index parameter value you obtained in part d.</a></li>
<li class="chapter" data-level="6.6.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#f.-6-points-for-each-of-the-values-of-x2-given-by-the-r-vector-x2_vals---seq0-15-by-.01-use-the-compound-poisson-gamma-structure-to-predict-the-probability-of-obtaining-an-exact-0-response-when-x1-is-at-its-mean-value."><i class="fa fa-check"></i><b>6.6.6</b> f. (6 points) For each of the values of x2 given by the R vector x2_vals &lt;- seq(0, 15, by= .01), use the compound Poisson-Gamma structure to predict the probability of obtaining an exact 0 response when x1 is at its mean value.</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#the-ships-dataset-in-the-mass-package-provides-the-number-of-incidentsindicents-resulting-in-ship-damage-as-a-function-of-total-months-of-serviceservice-ship-typetype-as-well-as-year-of-ship-constructionyear-broken-into-5-year-increments-with-the-years-variable-value-indicating-the-beginning-of-this-period.-e.g.-year60-refers-to-1960-1964-period-of-operationperiod-with-realizations-60-1960---1974-75-1975---1979-the-data-can-be-loaded-with-dataships-packagemass"><i class="fa fa-check"></i><b>6.7</b> 7. The ships dataset in the MASS package provides the number of incidents(indicents) resulting in ship damage as a function of total months of service(service), ship type(type), as well as: • Year of ship construction(year) – Broken into 5 year increments with the year’s variable value indicating the beginning of this period. e.g. year=60 refers to 1960-1964 • Period of operation(period) with realizations: – 60: 1960 - 1974 – 75: 1975 - 1979 The data can be loaded with: data(ships, package=“MASS”)</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#a.-4-points-use-group_by-and-summarise-to-compute-the-average-months-of-service-for-each-combination-of-year-of-construction-and-period-of-operation.-explain-why-there-is-a-0-in-the-result."><i class="fa fa-check"></i><b>6.7.1</b> a. (4 points) Use group_by and summarise to compute the average months of service for each combination of year of construction and period of operation. Explain why there is a 0 in the result.</a></li>
<li class="chapter" data-level="6.7.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#b.-3-points-create-a-new-filtered-dataset-by-removing-the-rows-where-service0."><i class="fa fa-check"></i><b>6.7.2</b> b. (3 points) Create a new filtered dataset by removing the rows where service=0.</a></li>
<li class="chapter" data-level="6.7.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#c.-10-points-fit-both-a-poisson-rate-model-and-negative-binomial-rate-model-model-using-number-of-incidents-per-service-month-as-the-response-and-all-other-variables-as-predictors.-compare-which-model-is-better-using-aic."><i class="fa fa-check"></i><b>6.7.3</b> c. (10 points) Fit both a Poisson rate model and Negative Binomial rate model model using number of incidents per service month as the response and all other variables as predictors. Compare which model is better using AIC.</a></li>
<li class="chapter" data-level="6.7.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#d.-7-points-using-the-better-model-selected-in-part-c-assess-the-significance-of-each-term-using-drop1.-which-terms-are-insignificant-remove-the-insignificant-variables-from-the-model-in-c-and-refit."><i class="fa fa-check"></i><b>6.7.4</b> d. (7 points) Using the better model selected in part c, assess the significance of each term using drop1(). Which terms are insignificant? Remove the insignificant variables from the model in c, and refit.</a></li>
<li class="chapter" data-level="6.7.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#e.-6-points-statistically-compare-the-residual-deviance-in-your-final-model-from-d-to-the-null-deviance."><i class="fa fa-check"></i><b>6.7.5</b> e. (6 points) Statistically compare the residual deviance in your final model from d to the null deviance.</a></li>
<li class="chapter" data-level="6.7.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#f.-4-points-compare-the-aic-from-the-reduced-model-in-d-to-the-corresponding-value-from-c.-is-the-change-you-see-expected-also-examine-the-residual-deviance-of-the-model-in-d-what-does-it-say-about-the-models-fit-to-the-data"><i class="fa fa-check"></i><b>6.7.6</b> f. (4 points) Compare the AIC from the reduced model in d to the corresponding value from c. Is the change you see expected? Also examine the residual deviance of the model in d, what does it say about the model’s fit to the data?</a></li>
<li class="chapter" data-level="6.7.7" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#g.-6-points-make-a-plot-of-the-deviance-residuals-vs-the-predicted-valueslink-scale.-how-is-the-fit"><i class="fa fa-check"></i><b>6.7.7</b> g. (6 points) Make a plot of the deviance residuals vs the predicted values(link scale). How is the fit?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><i class="fa fa-check"></i><b>7</b> Applied Stats Model II - Exam Two STAT 4520/7520 - Exam 2</a>
<ul>
<li class="chapter" data-level="7.1" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-consider-the-two-plots-below-which-show-the-exact-same-x-y-data.-the-difference-is-that-the-right-plot-has-colored-points-based-on-a-grouping-variable.-is-there-a-relationship-between-x-and-y-if-not-how-can-we-explain-the-left-plot-finally-how-would-you-model-the-response-y"><i class="fa fa-check"></i><b>7.1</b> 1. (7 points) Consider the two plots below, which show the exact same (x, y) data. The difference is that the right plot has colored points based on a grouping variable. Is there a relationship between x and y? If not, how can we explain the left plot? Finally, how would you model the response y?</a></li>
<li class="chapter" data-level="7.2" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-say-we-have-a-fitted-armapq-model-given-byy_t-.3y_t1-ε_t-what-are-the-values-of-p-and-q"><i class="fa fa-check"></i><b>7.2</b> 2. (3 points) Say we have a fitted ARMA(p,q) model given by<span class="math inline">\(Y_t = .3Y_{t−1} + ε_t\)</span> What are the values of p and q?</a></li>
<li class="chapter" data-level="7.3" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#say-we-observe-100-events-in-a-20ft-10ft-spatial-field-under-a-homogeneous-poisson-process"><i class="fa fa-check"></i><b>7.3</b> 3. Say we observe 100 events in a 20ft × 10ft spatial field under a homogeneous Poisson process:</a></li>
<li class="chapter" data-level="7.4" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-suppose-we-are-measuring-some-response-variable-and-our-data-contains-5-locations.-how-would-our-research-goals-be-different-if-we-considered-the-location-factor-as-fixed-vs-random"><i class="fa fa-check"></i><b>7.4</b> 4. (6 points) Suppose we are measuring some response variable and our data contains 5 locations. How would our research goals be different if we considered the location factor as fixed vs random?</a></li>
<li class="chapter" data-level="7.5" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-using-the-below-keras-code-and-summary-output-justify-the-number-of-parameters-at-each-layer-of-the-neural-network."><i class="fa fa-check"></i><b>7.5</b> 5. (7 points) Using the below keras code and summary output, justify the number of parameters at each layer of the neural network.</a></li>
<li class="chapter" data-level="7.6" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#consider-the-below-ann-which-was-fit-to-predict-a-cereals-rating-based-on-its-protein-content.-using-the-provided-weights-and-biases-with-an-input-of-protein4-find"><i class="fa fa-check"></i><b>7.6</b> 6. Consider the below ANN which was fit to predict a cereal’s rating based on its protein content. Using the provided weights and biases with an input of protein=4, find:</a></li>
<li class="chapter" data-level="7.7" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-consider-the-following-acf-plot."><i class="fa fa-check"></i><b>7.7</b> 7. (7 points) Consider the following ACF plot.</a></li>
<li class="chapter" data-level="7.8" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-the-file-1dconvolutiondata.csv-contains-a-collection-of-100-sequential-points.-read-them-into-r-and-convolve-them-with-the-kernal-c0.054-0.242-0.389-0.242-0.054.-place-the-orginal-signal-as-well-as-the-output-from-the-convolution-on-the-same-plotbe-sure-to-line-them-up-properly.-what-did-this-kernal-do"><i class="fa fa-check"></i><b>7.8</b> 8. (5 points) The file 1dConvolutionData.csv contains a collection of 100 sequential points. Read them into R and convolve them with the kernal c(0.054, 0.242, 0.389, 0.242, 0.054). Place the orginal signal as well as the output from the convolution on the same plot(be sure to line them up properly). What did this kernal do?</a></li>
<li class="chapter" data-level="7.9" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#time-series-20-points"><i class="fa fa-check"></i><b>7.9</b> 9. Time series (20 points)</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#a.-3-points-write-the-model-for-yt-mathematically-and-explain-the-intuition-behind-this-naming-convention."><i class="fa fa-check"></i><b>7.9.1</b> a. (3 points) Write the model for Yt mathematically and explain the intuition behind this naming convention.</a></li>
<li class="chapter" data-level="7.9.2" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#b.-6-points-using-a-random-error-process-of-ε-n0-1-start-a-random-walk-from-y_1-0-and-continue-for-1000-steps.-plot-the-time-series."><i class="fa fa-check"></i><b>7.9.2</b> b. (6 points) Using a random error process of ε ∼ N(0, 1), start a random walk from <span class="math inline">\(Y_1 = 0\)</span> and continue for 1000 steps. Plot the time series.</a></li>
<li class="chapter" data-level="7.9.3" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#c.-6-points-provide-both-an-autocorrelation-plot-as-well-as-a-partial-autocorrelation-plot.-explain-why-they-are-so-different."><i class="fa fa-check"></i><b>7.9.3</b> c. (6 points) Provide both an autocorrelation plot as well as a partial autocorrelation plot. Explain why they are so different.</a></li>
<li class="chapter" data-level="7.9.4" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#d.-5-points-change-the-value-of-φ"><i class="fa fa-check"></i><b>7.9.4</b> d. (5 points) Change the value of φ</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#open-ended-analysis-in-r-29-points"><i class="fa fa-check"></i><b>7.10</b> 10. Open Ended Analysis in R (29 points)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="asm2-hw-term-project.html"><a href="asm2-hw-term-project.html"><i class="fa fa-check"></i><b>8</b> ASM2 HW Term Project</a>
<ul>
<li class="chapter" data-level="8.1" data-path="asm2-hw-term-project.html"><a href="asm2-hw-term-project.html#rq-what-workds-based-on-what-theory"><i class="fa fa-check"></i><b>8.1</b> RQ: what workds based on what theory</a></li>
<li class="chapter" data-level="8.2" data-path="asm2-hw-term-project.html"><a href="asm2-hw-term-project.html#descriptive-analysis"><i class="fa fa-check"></i><b>8.2</b> Descriptive analysis</a></li>
<li class="chapter" data-level="8.3" data-path="asm2-hw-term-project.html"><a href="asm2-hw-term-project.html#mixed-model"><i class="fa fa-check"></i><b>8.3</b> Mixed Model</a></li>
<li class="chapter" data-level="8.4" data-path="asm2-hw-term-project.html"><a href="asm2-hw-term-project.html#qa-a-why-small-change-b-prediction-measurement-auc-make-sense-c-interpretation-residual-centering-in-stats-vs.-econ."><i class="fa fa-check"></i><b>8.4</b> Q&amp;A: a) why small change b) prediction measurement, AUC make sense? c) interpretation residual centering in stats vs. econ.</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="question-1.html"><a href="question-1.html"><i class="fa fa-check"></i><b>9</b> Question 1:</a>
<ul>
<li class="chapter" data-level="9.1" data-path="question-1.html"><a href="question-1.html#a.-8-points-create-plots-to-examine-how-launch-speed-and-angle-may-affect-the-probability-of-a-home-run-and-describe-your-findings."><i class="fa fa-check"></i><b>9.1</b> a. (8 points) Create plots to examine how launch speed and angle may affect the probability of a home run and describe your findings.</a></li>
<li class="chapter" data-level="9.2" data-path="question-1.html"><a href="question-1.html#b.-9-points-fit-a-logistic-regression-model-with-home_run-as-the-response-and-all-other-variables-as-predictors.-conduct-a-deviance-test-to-assess-if-this-model-is-better-than-the-null-model."><i class="fa fa-check"></i><b>9.2</b> b. (9 points) Fit a logistic regression model with home_run as the response and all other variables as predictors. Conduct a deviance test to assess if this model is better than the null model.</a></li>
<li class="chapter" data-level="9.3" data-path="question-1.html"><a href="question-1.html#c.-8-points-conduct-deviance-tests-with-the-drop1-function-to-assess-the-significance-of-each-individual-variable-and-report-the-results.-compare-the-p-values-to-those-obtained-from-summary."><i class="fa fa-check"></i><b>9.3</b> c. (8 points) Conduct deviance tests with the drop1() function to assess the significance of each individual variable and report the results. Compare the p-values to those obtained from summary().</a></li>
<li class="chapter" data-level="9.4" data-path="question-1.html"><a href="question-1.html#d.-6-points-fit-a-smaller-model-after-removing-all-variables-which-are-insignificant-using-α-0.05.-compare-this-model-to-the-larger-model-are-they-significantly-different-what-are-the-implications-of-this-with-regard-to-model-selection-until-the-end-of-this-question-use-the-smaller-model-for-all-analysis"><i class="fa fa-check"></i><b>9.4</b> d. (6 points) Fit a smaller model after removing all variables which are insignificant using α = 0.05. Compare this model to the larger model, are they significantly different? What are the implications of this with regard to model selection? Until the end of this question, use the smaller model for all analysis</a></li>
<li class="chapter" data-level="9.5" data-path="question-1.html"><a href="question-1.html#e.-7-points-how-does-the-launch-speed-after-the-ball-is-hit-affect-the-odds-of-homerun-occurring-provide-a-confidence-interval-for-this-value."><i class="fa fa-check"></i><b>9.5</b> e. (7 points) How does the launch speed after the ball is hit affect the <strong>odds of HomeRun occurring</strong>? Provide a confidence interval for this value.</a></li>
<li class="chapter" data-level="9.6" data-path="question-1.html"><a href="question-1.html#f.-5-points-using-the-deviance-residuals-make-a-binned-residual-vs-fitted-probability-plot-and-comment-on-the-fit-of-the-model."><i class="fa fa-check"></i><b>9.6</b> f. (5 points) Using the deviance residuals, make a binned residual vs fitted probability plot and comment on the fit of the model.</a></li>
<li class="chapter" data-level="9.7" data-path="question-1.html"><a href="question-1.html#g.-4-points-using-a-probability-of-0.5-as-the-threshold-for-predicting-an-observation-yielding-a-home-run-create-a-table-classifying-the-predictions-against-the-observed-values.-describe-your-findings.-what-is-the-misclassification-rate"><i class="fa fa-check"></i><b>9.7</b> g. (4 points) Using a probability of 0.5 as the threshold for predicting an observation yielding a home run, create a table classifying the predictions against the observed values. Describe your findings. What is the misclassification rate?</a></li>
<li class="chapter" data-level="9.8" data-path="question-1.html"><a href="question-1.html#h.-6-points-using-probability-thresholds-from-0.005-to-0.995-obtain-the-sensitivities-and-specificity-of-the-resulting-predictions.-create-an-roc-plot-and-comment-on-the-effectiveness-of-the-models-ability-to-correctly-classify-the-response.-as-we-vary-the-threshold-to-determine-classifications-is-inverse-relationship-between-sensitivity-and-specificity-strongly-evident"><i class="fa fa-check"></i><b>9.8</b> h. (6 points) Using probability thresholds from 0.005 to 0.995, obtain the sensitivities and specificity of the resulting predictions. Create an ROC plot and comment on the effectiveness of the model’s ability to correctly classify the response. As we vary the threshold to determine classifications, is inverse relationship between sensitivity and specificity strongly evident?</a></li>
<li class="chapter" data-level="9.9" data-path="question-1.html"><a href="question-1.html#i.-5-points-produce-a-plot-of-the-sensitivity-and-specificity-against-the-threshold.-is-there-a-threshold-for-classification-you-would-recommend-that-provides-a-good-balance-between-the-two-make-another-confusion-matrix-using-this-cutoff-how-does-the-result-compare-to-the-previous-one-consider-the-types-of-errors-you-observe."><i class="fa fa-check"></i><b>9.9</b> i. (5 points) Produce a plot of the sensitivity and specificity against the threshold. Is there a threshold for classification you would recommend that provides a good balance between the two? Make another confusion matrix using this cutoff, how does the result compare to the previous one? Consider the types of errors you observe.</a></li>
<li class="chapter" data-level="9.10" data-path="question-1.html"><a href="question-1.html#j.-3-points-consider-a-logistic-model-with-only-launch_angle-and-launch_speed-being-used-to-predict-the-probability-of-a-home-run.-what-is-the-aic-of-this-model"><i class="fa fa-check"></i><b>9.10</b> j. (3 points) Consider a logistic model with only launch_angle and launch_speed being used to predict the probability of a home run. What is the AIC of this model?</a></li>
<li class="chapter" data-level="9.11" data-path="question-1.html"><a href="question-1.html#k.-11-points-create-a-dummy-variable-which-is-1-if-launch_angle-is-between-20-and-40-degrees-and-use-this-variable-in-your-model-instead-of-the-raw-value-for-launch_angle.-then-complete-the-following-1.-compare-the-aic-of-this-model-to-the-model-in-part-j-which-model-is-better-2.-what-does-the-coefficient-of-your-dummy-variable-mean-interpret-the-value.-3.-interpret-the-value-of-the-intercept-by-converting-to-a-probability.-does-this-result-make-sense"><i class="fa fa-check"></i><b>9.11</b> k. (11 points) Create a dummy variable which is 1 if launch_angle is between 20 and 40 degrees and use this variable in your model instead of the raw value for launch_angle. Then, complete the following: 1. Compare the AIC of this model to the model in part j, which model is better? 2. What does the coefficient of your dummy variable mean? Interpret the value. 3. Interpret the value of the intercept by converting to a probability. Does this result make sense?</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="question-1.html"><a href="question-1.html#section-1"><i class="fa fa-check"></i><b>9.11.1</b> </a></li>
</ul></li>
<li class="chapter" data-level="9.12" data-path="question-1.html"><a href="question-1.html#a.-5-points-make-a-plot-or-set-of-tables-showing-the-distribution-of-lsd-use-between-genders-and-interpret.-you-can-use-code-similar-to-that-on-slide-84-of-the-course-notes."><i class="fa fa-check"></i><b>9.12</b> a. (5 points) Make a plot or set of tables showing the distribution of LSD use between genders and interpret. You can use code similar to that on slide 84 of the course notes.</a></li>
<li class="chapter" data-level="9.13" data-path="question-1.html"><a href="question-1.html#b.-9-points-fit-a-proportional-odds-model-using-lsd-as-the-response-variable-and-the-other-variables-listed-above-as-predictors.-using-drop1-test-if-the-variables-are-significant-or-insignificant-and-describe-2-your-results."><i class="fa fa-check"></i><b>9.13</b> b. (9 points) Fit a proportional odds model using LSD as the response variable and the other variables listed above as predictors. Using drop1(), test if the variables are significant or insignificant and describe 2 your results.</a></li>
<li class="chapter" data-level="9.14" data-path="question-1.html"><a href="question-1.html#c.-6-points-interpret-the-values-of-the-intercepts-θj-."><i class="fa fa-check"></i><b>9.14</b> c. (6 points) Interpret the values of the intercepts θj .</a></li>
<li class="chapter" data-level="9.15" data-path="question-1.html"><a href="question-1.html#d.-10-points-print-the-coefficient-table-and-interpret-the-values-of-the-significant-personality-characteristics."><i class="fa fa-check"></i><b>9.15</b> d. (10 points) Print the coefficient table and interpret the values of the significant personality characteristics.</a></li>
<li class="chapter" data-level="9.16" data-path="question-1.html"><a href="question-1.html#e.-7250-only-6-points-explore-interacting-some-of-the-categorical-demographic-variables-with-the-personality-measurements-and-report-your-findings-does-the-nature-of-any-personality-characteristics-affect-on-lsd-usage-change-according-to-your-analysis"><i class="fa fa-check"></i><b>9.16</b> e. (7250 only) (6 points) Explore interacting some of the categorical demographic variables with the personality measurements and report your findings, does the nature of any personality characteristics affect on LSD usage change according to your analysis?</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html"><i class="fa fa-check"></i><b>10</b> 1 1) Modeling the Number of Claims</a>
<ul>
<li class="chapter" data-level="10.1" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#a.-5-points-create-a-table-to-present-the-distribution-of-the-number-of-claims-by-computing-the-proportion-of-each-possibility.-what-percent-of-the-policies-have-0-claims"><i class="fa fa-check"></i><b>10.1</b> a. (5 points) Create a table to present the distribution of the number of claims by computing the proportion of each possibility. What percent of the policies have 0 claims?</a></li>
<li class="chapter" data-level="10.2" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#b.-6-points-create-a-poisson-regression-to-predict-the-number-of-claims-in-the-year-using-only-the-variables-for-vehicle-age-driver-age-bonusmalus-and-density.-what-is-the-deviance-does-is-differ-significantly-from-the-null-deviance"><i class="fa fa-check"></i><b>10.2</b> b. (6 points) Create a Poisson regression to predict the number of claims in the year using only the variables for vehicle age, driver age, bonusMalus, and density. What is the deviance? Does is differ significantly from the null deviance?</a></li>
<li class="chapter" data-level="10.3" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#c.-4-points-generate-predictions-on-the-response-scale-µ-and-round-them-to-the-nearest-count.-create-a-table-as-in-part-a-and-comment-on-how-similar-or-dissimilar-this-result-is."><i class="fa fa-check"></i><b>10.3</b> c. (4 points) Generate predictions on the response scale µ and round them to the nearest count. Create a table as in part a and comment on how similar or dissimilar this result is.</a></li>
<li class="chapter" data-level="10.4" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#d.-3-points-fit-a-negative-binomial-model-to-the-data-and-generate-predictions-as-in-part-c.-did-this-solve-the-problem"><i class="fa fa-check"></i><b>10.4</b> d. (3 points) Fit a negative binomial model to the data and generate predictions as in part c. Did this solve the problem?</a></li>
<li class="chapter" data-level="10.5" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#e.-5-points-now-fit-a-zero-inflation-poisson-model-zip-and-compute-the-fitted-proportion-of-zero-counts-as-on-slide-38-of-the-poisson-notes.-does-this-help"><i class="fa fa-check"></i><b>10.5</b> e. (5 points) Now fit a zero inflation Poisson model (ZIP) and compute the fitted proportion of zero counts as on slide 38 of the Poisson Notes. Does this help?</a></li>
<li class="chapter" data-level="10.6" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#f.-8-points-interpret-the-signs-of-the-coefficient-estimates-out-of-the-zip-model-both-the-count-portion-as-well-as-the-zero-inflated-portion"><i class="fa fa-check"></i><b>10.6</b> f. (8 points) Interpret the signs of the coefficient estimates out of the ZIP model, both the count portion as well as the zero inflated portion!</a></li>
<li class="chapter" data-level="10.7" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#a.-3-points-in-this-problem-we-will-focus-on-modeling-the-positive-continuous-variable-avgclaimamount.-attempt-to-fit-a-gamma-regression-with-a-log-link-predicting-avgclaimamount-as-a-function-of-all-feature-variables-in-the-dataset.-what-happens-when-you-attempt-to-fit-this-model"><i class="fa fa-check"></i><b>10.7</b> a. (3 points) In this problem we will focus on modeling the positive continuous variable “AvgClaimAmount.” Attempt to fit a Gamma regression with a log link, predicting AvgClaimAmount as a function of all feature variables in the dataset. What happens when you attempt to fit this model?</a></li>
<li class="chapter" data-level="10.8" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#b.-5-points-create-a-new-dataset-consisting-of-the-rows-that-correspond-to-strictly-positive-realizations-of-avgclaimamount.-make-a-histogram-of-this-variable-on-standard-and-log-scale-and-describe-your-findings."><i class="fa fa-check"></i><b>10.8</b> b. (5 points) Create a new dataset consisting of the rows that correspond to strictly positive realizations of AvgClaimAmount. Make a histogram of this variable on standard and log scale and describe your findings.</a></li>
<li class="chapter" data-level="10.9" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#c.-4-points-fit-the-gamma-regression-proposed-in-part-a-to-the-filtered-dataset.-do-you-notice-anything-strange-how-many-iterations-did-it-take-glm-to-find-this-result"><i class="fa fa-check"></i><b>10.9</b> c. (4 points) Fit the Gamma regression proposed in part a to the filtered dataset. Do you notice anything strange? How many iterations did it take glm() to find this result?</a></li>
<li class="chapter" data-level="10.10" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#d.-3-points-to-the-glm-function-add-the-argument-control-listmaxit-500.-what-do-you-think-this-will-do-fit-the-model-and-examine-the-summary-output-to-check-the-number-of-iterations-needed-for-convergence."><i class="fa fa-check"></i><b>10.10</b> d. (3 points) To the glm() function, add the argument control = list(maxit = 500). What do you think this will do? Fit the model and examine the summary output to check the number of iterations needed for convergence.</a></li>
<li class="chapter" data-level="10.11" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#e.3-points-from-the-model-in-e.-interpret-the-parameter-estimate-for-a-vehicles-age"><i class="fa fa-check"></i><b>10.11</b> e.(3 points) From the model in e. Interpret the parameter estimate for a vehicle’s age</a></li>
<li class="chapter" data-level="10.12" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#a.-8-points-using-the-entire-dataset-create-a-profile-likelihood-of-the-index-values-p-for-use-in-a-glm-utilizing-the-tweedie-distribution-to-predict-purepremium-directly.-make-a-plot-of-the-profile-likelihood-and-select-the-best-value.-7520---3-points-for-graduate-students-i-expect-some-exploration-to-find-the-best-value-as-these-data-are-quite-poorly-behaved.-look-at-the-value-section-of-tweedie.profile-for-some-hints-and-i-would-suggest-narrowing-the-search-space-for-p-and-evaluating-it-on-a-somewhat-fine-grid."><i class="fa fa-check"></i><b>10.12</b> a. (8 points) Using the entire dataset, create a profile likelihood of the index values p for use in a glm utilizing the Tweedie distribution to predict PurePremium directly. Make a plot of the profile likelihood and select the best value. (7520 - 3 points): For graduate students, I expect some <strong>exploration to find the best value as these data are quite poorly behaved</strong>. Look at the “Value” section of ?tweedie.profile for some hints, and I <strong>would suggest narrowing the search space for p and evaluating it on a somewhat fine grid.</strong></a></li>
<li class="chapter" data-level="10.13" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#b.-fit-the-tweedie-glm-model-using-the-optimal-power-value-you-computed-from-the-previous-question.-the-file-insurance_test.csv-contains-a-few-additional-observations-which-were-not-a-portion-of-the-data-used-to-fit-the-previous-models.-we-can-read-it-in-and-format-it-using-syntax-similar-to-when-we-started.-newdatapoints---read.csv.insurance_test.csv-newdatapointsvehbrand---as.factornewdatapointsvehbrand-newdatapointsvehpower---as.factornewdatapointsvehpower-newdatapointsvehgas---as.factornewdatapointsvehgas-newdatapointsregion---as.factornewdatapointsregion-newdatapointsarea---as.factornewdatapointsarea"><i class="fa fa-check"></i><b>10.13</b> b. Fit the Tweedie GLM model using the optimal power value you computed from the previous question. The file Insurance_test.csv contains a few additional observations which were not a portion of the data used to fit the previous models. We can read it in and format it using syntax similar to when we started. NewDataPoints &lt;- read.csv(“…./Insurance_test.csv”) NewDataPoints$VehBrand &lt;- as.factor(NewDataPoints$VehBrand) NewDataPoints$VehPower &lt;- as.factor(NewDataPoints$VehPower) NewDataPoints$VehGas &lt;- as.factor(NewDataPoints$VehGas) NewDataPoints$Region &lt;- as.factor(NewDataPoints$Region) NewDataPoints$Area &lt;- as.factor(NewDataPoints$Area)</a></li>
<li class="chapter" data-level="10.14" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#c.7-points-use-your-poisson-model-from-1b-from-and-your-final-gamma-model-from-2d-to-generate-respective-predictions-for-the-number-of-claims-in-a-year-as-well-as-the-average-amount-per-claim.-multiply-these-together-and-call-this-product-purepremium_prod.-similarly-use-your-tweedie-model-from-3b-to-directly-predict-the-purepremium-value-and-store-this-in-purepremium_tw."><i class="fa fa-check"></i><b>10.14</b> c.(7 points) Use your Poisson model from 1b from and your final Gamma model from 2d to generate respective predictions for the number of claims in a year as well as the average amount per claim. Multiply these together and call this product purepremium_prod. Similarly, use your Tweedie model from 3b to directly predict the PurePremium value and store this in purepremium_TW.</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><i class="fa fa-check"></i><b>11</b> STAT 4520/7520 - Homework 3 Spring 2022 Due: March 30, 2022</a>
<ul>
<li class="chapter" data-level="11.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#the-cake-dataset-in-the-lme4-package-contains-data-on-an-experiment-was-conducted-to-determine-the-effect-of-recipe-and-baking-temperature-on-chocolate-cake-quality.-fifteen-batches-of-cake-mix-for-each-recipe-were-prepared.-each-batch-was-sufficient-for-six-cakes.-each-of-the-six-cakes-was-baked-at-a-different-temperature-which-was-randomly-assigned.-as-an-indicator-of-quality-the-breakage-angle-of-the-cake-was-recorded."><i class="fa fa-check"></i><b>11.1</b> 1) The cake dataset in the lme4 package contains data on an experiment was conducted to determine the effect of recipe and baking temperature on chocolate cake quality. Fifteen batches of cake mix for each recipe were prepared. Each batch was sufficient for six cakes. Each of the six cakes was baked at a different temperature which was randomly assigned. As an indicator of quality, the breakage angle of the cake was recorded.</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#a.-of-the-explanatory-variables-recipe-temp-and-replicate-which-are-fixed-and-which-are-random-explain.-is-there-any-nesting-in-these-variables"><i class="fa fa-check"></i><b>11.1.1</b> a. Of the explanatory variables recipe, temp, and replicate, which are fixed and which are random? Explain. Is there any nesting in these variables?</a></li>
<li class="chapter" data-level="11.1.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#b.-fit-a-linear-model-with-no-random-effects-for-breaking-angle-against-the-interaction-between-recipe-and-temperature.-which-variables-are-significant-what-is-the-t-value-for-temp-the-temperature-variable-what-is-the-rmse-of-this-model"><i class="fa fa-check"></i><b>11.1.2</b> b. Fit a linear model with no random effects for breaking angle against the interaction between recipe and temperature. Which variables are significant? What is the t value for temp the temperature variable? What is the RMSE of this model?</a></li>
<li class="chapter" data-level="11.1.3" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#c.-fit-a-mixed-model-to-the-data-which-takes-into-account-the-replicates-of-the-recipes.-examine-the-variance-components.-is-there-variation-in-the-batches-made-with-each-recipe-how-does-the-residual-variance-component-compare-to-the-mse-from-b-what-is-the-t-value-for-temperature"><i class="fa fa-check"></i><b>11.1.3</b> c. Fit a mixed model to the data which takes into account the replicates of the recipes. Examine the variance components. Is there variation in the batches made with each recipe? How does the Residual variance component compare to the MSE from (b)? What is the t-value for temperature?</a></li>
<li class="chapter" data-level="11.1.4" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#d.-test-for-a-recipe-and-temperature-effect."><i class="fa fa-check"></i><b>11.1.4</b> d. Test for a recipe and temperature effect.</a></li>
<li class="chapter" data-level="11.1.5" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#e.-create-a-qq-plot-of-the-residuals-and-a-residual-vs-predicted-plot-for-the-linear-model-in-b-and-the-mixed-model-in-d-describe-how-well-the-model-assumptions-are-satisfied-for-each."><i class="fa fa-check"></i><b>11.1.5</b> e. Create a QQ plot of the residuals and a residual vs predicted plot for the linear model in (b) and the mixed model in (d), describe how well the model assumptions are satisfied for each.</a></li>
<li class="chapter" data-level="11.1.6" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#f.-7510-only-examine-the-blups-from-the-mixed-model-in-d.-do-you-notice-any-patterns"><i class="fa fa-check"></i><b>11.1.6</b> f. (7510 only) Examine the BLUPs from the mixed model in (d). Do you notice any patterns?</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#the-purpose-of-random-effects-is-to-remove-variation-from-known-sources.-in-this-problem-we-will-use-this-idea-and-see-how-it-can-work-with-a-popular-technique-for-predictive-modeling-the-random-forest.-random-forests-were-covered-in-the-prerequisite-course-and-can-be-fit-using-the-randomforest-function-in-the-randomforest-library.-the-dataset-problem-2.csv-has-a-simulated-dataset.-there-is-a-nonlinear-relationship-between-6-numeric-explanatory-variables-x1-.-.-.-x6-and-the-response-y-to-addition-to-a-grouping-effect-according-to-the-id-variable-which-has-100-levels."><i class="fa fa-check"></i><b>11.2</b> 2) The purpose of random effects is to remove variation from known sources. In this problem, we will use this idea and see how it can work with a popular technique for predictive modeling, the random forest. Random forests were covered in the prerequisite course, and can be fit using the randomForest function in the randomForest library. The dataset Problem-2.csv has a simulated dataset. There is a nonlinear relationship between 6 numeric explanatory variables x1, . . . x6 and the response y, to addition to a grouping effect according to the ID variable, which has 100 levels.</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#a.-read-in-the-dataset-and-split-the-data-into-a-training-and-test-set-using-95-of-the-data-for-the-training-set.-set-a-seed-of-1-for-consistency-of-results."><i class="fa fa-check"></i><b>11.2.1</b> a. Read in the dataset, and split the data into a training and test set, using 95% of the data for the training set. Set a seed of 1 for consistency of results.</a></li>
<li class="chapter" data-level="11.2.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#b.-fit-a-random-forest-model-to-the-training-data-using-y-as-the-response-with-x1-.-.-.-x6-and-id-as-the-explanatory-variables.-use-the-model-to-predict-y-in-the-test-set-and-compute-the-test-root-mean-squared-error-rmse-."><i class="fa fa-check"></i><b>11.2.2</b> b. Fit a random forest model to the training data using y as the response with x1, . . . x6 and ID as the explanatory variables. Use the model to predict y in the test set and compute the test root mean squared error ( RMSE ).</a></li>
<li class="chapter" data-level="11.2.3" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#c.-fit-the-mixed-model-yij-µ-idi-εij-to-the-training-data.-this-model-does-not-use-the-x_i-at-all-and-has-a-random-intercept-based-on-id.-after-fitting-the-model-extract-the-blups-for-id-and-add-them-to-the-constant-µˆ-the-estimate-of-the-overall-intercept.-what-do-these-values-represent-store-them-in-a-data-frame-along-with-a-column-storing-the-ids."><i class="fa fa-check"></i><b>11.2.3</b> c. Fit the mixed model yij = µ + IDi + εij to the training data. This model does not use the x_i at all, and has a random intercept based on ID. After fitting the model, extract the BLUPs for ID and add them to the constant µˆ, the estimate of the overall intercept. What do these values represent? Store them in a data frame along with a column storing the IDs.</a></li>
<li class="chapter" data-level="11.2.4" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#d.-add-a-column-to-the-test-dataset-containing-the-values-obtained-in-part-c-joined-to-the-test-dataset-by-matching-the-ids.-note-with-the-dplyr-package-loaded-you-can-quickly-join-by-id-using-a-line-like-data.test---left_joindata.test-int_plus_blups-by-id-examine-the-first-few-rows-and-describe-what-the-new-column-represents."><i class="fa fa-check"></i><b>11.2.4</b> d. Add a column to the test dataset containing the values obtained in part c, joined to the test dataset by matching the IDs. Note: with the dplyr package loaded, you can quickly join by ID using a line like: Data.Test &lt;- left_join(Data.Test, int_plus_blups, by = “ID”) Examine the first few rows and describe what the new column represents.</a></li>
<li class="chapter" data-level="11.2.5" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#e.-compute-the-residuals-of-the-mixed-model-fit-in-c-using-the-residuals-function-store-them-in-a-column-of-the-training-data."><i class="fa fa-check"></i><b>11.2.5</b> e. Compute the residuals of the mixed model fit in (c) using the residuals() function, store them in a column of the training data.</a></li>
<li class="chapter" data-level="11.2.6" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#f.-fit-another-random-forest-model-to-the-training-data-using-the-residuals-from-part-e-as-the-response-and-only-x1-.-.-.-x6-as-the-explanatory-variables.-use-this-model-to-predict-into-the-test-data-and-store-these-predictions.-what-do-these-predictions-represent"><i class="fa fa-check"></i><b>11.2.6</b> f. Fit another random forest model to the training data, using the residuals from part (e) as the response and only x1, . . . x6 as the explanatory variables. Use this model to predict into the test data and store these predictions. What do these predictions represent?</a></li>
<li class="chapter" data-level="11.2.7" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#g.-add-the-predictions-in-f-to-the-values-joined-to-the-test-data-in-d.-consider-these-values-test-predictions-and-compute-the-test-mse.-compare-this-to-the-test-mse-compared-in-part-b.-what-do-you-observe"><i class="fa fa-check"></i><b>11.2.7</b> g. Add the predictions in (f) to the values joined to the test data in (d). Consider these values test predictions, and compute the test MSE. Compare this to the test MSE compared in part (b). What do you observe?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><i class="fa fa-check"></i><b>12</b> STAT 4520/7520 - Homework 4 Spring 2022 Due: April 25, 2022</a>
<ul>
<li class="chapter" data-level="12.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#section-2"><i class="fa fa-check"></i><b>12.1</b> 1)</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-make-a-plot-of-weight-vs-time-for-the-data-with-rat-specific-lines-to-show-the-subject-specific-trajectory.-describe-your-findings.-7510-only-further-color-the-lines-differently-for-the-different-diets.-do-you-notice-anything-further"><i class="fa fa-check"></i><b>12.1.1</b> a. Make a plot of weight vs Time for the data with rat specific lines to show the subject specific trajectory. Describe your findings. (7510 only) Further, color the lines differently for the different diets. Do you notice anything further?</a></li>
<li class="chapter" data-level="12.1.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-use-lm-to-regress-the-weight-onto-the-time.-what-is-the-slope-and-intercept-of-this-model-is-the-slope-significant"><i class="fa fa-check"></i><b>12.1.2</b> b. Use lm() to regress the weight onto the Time. What is the slope and intercept of this model? Is the slope significant?</a></li>
<li class="chapter" data-level="12.1.3" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-use-the-lmlist-function-to-fit-a-linear-regression-model-that-describes-how-weight-varies-with-days-for-each-individual-rat.-how-do-the-slopes-and-intercepts-vary-do-you-notice-any-patterns-with-respect-to-diets"><i class="fa fa-check"></i><b>12.1.3</b> c. Use the lmList function to fit a linear regression model that describes how weight varies with days for each individual rat. How do the slopes and intercepts vary? Do you notice any patterns with respect to diets?</a></li>
<li class="chapter" data-level="12.1.4" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#d.-fit-a-random-intercept-model-to-account-for-the-different-weights-of-each-individual-rat-and-continue-to-use-time-as-a-fixed-effect.-answer-the-following"><i class="fa fa-check"></i><b>12.1.4</b> d. Fit a random intercept model to account for the different weights of each individual rat and continue to use Time as a fixed effect. Answer the following:</a></li>
<li class="chapter" data-level="12.1.5" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#e.-obtain-the-blups-for-the-rats-and-list-who-is-the-most-heavy."><i class="fa fa-check"></i><b>12.1.5</b> e. Obtain the BLUPs for the rats and list who is the most heavy.</a></li>
<li class="chapter" data-level="12.1.6" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#f.-fit-a-mixed-effects-model-that-describes-how-the-weight-varies-linearly-with-time-and-allows-for-random-variation-in-the-intercepts-and-slopes-of-the-rats.-then-do-the-following"><i class="fa fa-check"></i><b>12.1.6</b> f. Fit a mixed effects model that describes how the weight varies linearly with time and allows for random variation in the intercepts and slopes of the rats. Then do the following:</a></li>
<li class="chapter" data-level="12.1.7" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#g.-obtain-the-blups-for-the-model-in-part-f.-which-rat-has-the-fastest-rate-of-increase-the-slowest"><i class="fa fa-check"></i><b>12.1.7</b> g. Obtain the BLUPs for the model in part f. Which rat has the fastest rate of increase? The slowest?</a></li>
<li class="chapter" data-level="12.1.8" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#h.-add-the-fixed-diet-variable-to-the-model-in-the-form-of-an-interaction-with-time.-does-the-diet-effect-weight-is-this-effect-different-at-different-times"><i class="fa fa-check"></i><b>12.1.8</b> h. Add the (fixed) diet variable to the model in the form of an interaction with time. Does the diet effect weight? Is this effect different at different times?</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#time-series"><i class="fa fa-check"></i><b>12.2</b> 2) Time Series</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-create-a-variable-containing-the-log-base-10-of-the-eps-then-use-lm-to-regress-it-onto-time.-store-the-residuals-of-this-regression-in-another-variable-in-jj.-make-a-plot-of-the-residuals-vs-time-and-describe-your-findings."><i class="fa fa-check"></i><b>12.2.1</b> a. Create a variable containing the log (base 10) of the EPS, then use lm() to regress it onto Time. Store the residuals of this regression in another variable in JJ. Make a plot of the residuals vs Time and describe your findings.</a></li>
<li class="chapter" data-level="12.2.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-run-the-detrended-values-through-auto.arima-to-find-a-good-arma-model.-note-that-you-may-want-to-use-the-additional-argument-stepwise-false-to-allow-auto.arima-to-conduct-a-full-grid-search.-what-model-was-found"><i class="fa fa-check"></i><b>12.2.2</b> b. Run the detrended values through auto.arima() to find a good ARMA model. Note that you may want to use the additional argument stepwise = FALSE to allow auto.arima() to conduct a full grid search. What model was found?</a></li>
<li class="chapter" data-level="12.2.3" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-use-the-best-model-to-forecast-the-detrended-relationship-2-years-8-quarters-ahead.-make-a-plot-of-the-result-and-comment-on-how-reasonable-your-predictions-look."><i class="fa fa-check"></i><b>12.2.3</b> c. Use the best model to forecast the detrended relationship 2 years (8 quarters) ahead. Make a plot of the result and comment on how reasonable your predictions look.</a></li>
<li class="chapter" data-level="12.2.4" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#d.-use-the-linear-model-from-part-a-to-predict-the-trend-for-the-next-8-quarters-add-the-result-to-that-of-part-c-transform-back-to-the-original-scale-and-plot-the-forecast-along-with-the-original-data.-does-the-forecast-seem-reasonable"><i class="fa fa-check"></i><b>12.2.4</b> d. Use the linear model from part a to predict the trend for the next 8 quarters, add the result to that of part c, transform back to the original scale, and plot the forecast along with the original data. Does the forecast seem reasonable?</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#spatial-point-process-analysis"><i class="fa fa-check"></i><b>12.3</b> 3) Spatial Point Process Analysis</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-make-a-plot-of-the-point-pattern.-does-the-distribution-of-the-points-in-space-appear-to-be-homogeneous-poisson-process"><i class="fa fa-check"></i><b>12.3.1</b> a. Make a plot of the point pattern. Does the distribution of the points in space appear to be homogeneous Poisson process?</a></li>
<li class="chapter" data-level="12.3.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-make-plots-of-gr-and-fr-and-comment-on-what-you-observe."><i class="fa fa-check"></i><b>12.3.2</b> b. Make plots of G(r) and F(r) and comment on what you observe.</a></li>
<li class="chapter" data-level="12.3.3" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-fit-a-point-process-model-with-linear-terms-in-both-x-and-y.-are-there-any-significant-spatial-relationships"><i class="fa fa-check"></i><b>12.3.3</b> c. Fit a point process model with linear terms in both x and y. Are there any significant spatial relationships?</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#loading-keras"><i class="fa fa-check"></i><b>12.4</b> 4) Loading Keras</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-mostly-as-an-exercise-to-ensure-you-have-keras-installed-correctly-run-the-above-code-and-comment-onthe-quality-of-the-fit-you-observe.-note-i-was-unable-to-run-the-code-within-an-rmarkdown-cell-but-this-may-be-due-to-a-system-configuration-issue."><i class="fa fa-check"></i><b>12.4.1</b> a. Mostly as an exercise to ensure you have Keras installed correctly, run the above code and comment onthe quality of the fit you observe. NOTE: I was unable to run the code within an RMarkdown cell, but this may be due to a system configuration issue.</a></li>
<li class="chapter" data-level="12.4.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-modify-the-code-in-an-attempt-to-improve-the-fit.-specifically-study-the-effects-as-well-as-interactions-of"><i class="fa fa-check"></i><b>12.4.2</b> b. Modify the code in an attempt to improve the fit. Specifically, study the effects (as well as interactions) of:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html"><i class="fa fa-check"></i><b>13</b> Applied Stats Model II Lecture Note</a>
<ul>
<li class="chapter" data-level="13.1" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#list-of-questions"><i class="fa fa-check"></i><b>13.1</b> List of Questions:</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#hw1"><i class="fa fa-check"></i><b>13.1.1</b> HW1</a></li>
<li class="chapter" data-level="13.1.2" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#hw2"><i class="fa fa-check"></i><b>13.1.2</b> HW2</a></li>
<li class="chapter" data-level="13.1.3" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#midterm"><i class="fa fa-check"></i><b>13.1.3</b> Midterm</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#class-content-overview"><i class="fa fa-check"></i><b>13.2</b> Class content overview:</a></li>
<li class="chapter" data-level="13.3" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glm-categoricaldata_sp2022"><i class="fa fa-check"></i><b>13.3</b> GLM-CategoricalData_SP2022</a></li>
<li class="chapter" data-level="13.4" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glm-countdata_sp2022"><i class="fa fa-check"></i><b>13.4</b> GLM-CountData_SP2022</a></li>
<li class="chapter" data-level="13.5" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glms_advancedtopics_sp2022"><i class="fa fa-check"></i><b>13.5</b> GLMs_AdvancedTopics_SP2022</a></li>
<li class="chapter" data-level="13.6" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#mm-randomeffects_spring2022"><i class="fa fa-check"></i><b>13.6</b> MM-RandomEffects_Spring2022</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#hw4-repeated-measure-time-and-space-dependence."><i class="fa fa-check"></i><b>13.6.1</b> HW4: Repeated measure, time and space dependence.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html"><i class="fa fa-check"></i><b>14</b> Experimental Data Analysis</a>
<ul>
<li class="chapter" data-level="14.1" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#process-macro"><i class="fa fa-check"></i><b>14.1</b> PROCESS Macro</a></li>
<li class="chapter" data-level="14.2" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#data-cleaning"><i class="fa fa-check"></i><b>14.2</b> Data cleaning</a></li>
<li class="chapter" data-level="14.3" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#mediation-analysis"><i class="fa fa-check"></i><b>14.3</b> Mediation analysis</a></li>
<li class="chapter" data-level="14.4" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#adding-more-controls"><i class="fa fa-check"></i><b>14.4</b> Adding more controls</a></li>
<li class="chapter" data-level="14.5" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#efa-and-cfa-analysis-measurement-analysis"><i class="fa fa-check"></i><b>14.5</b> EFA And CFA Analysis / Measurement analysis</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html"><a href="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html"><i class="fa fa-check"></i><b>15</b> SEM HW5 - code in the chunk but don’t run them. copy them as a whole with the comments</a>
<ul>
<li class="chapter" data-level="15.1" data-path="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html"><a href="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html#replicate-hw3"><i class="fa fa-check"></i><b>15.1</b> Replicate HW3</a></li>
<li class="chapter" data-level="15.2" data-path="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html"><a href="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html#most-of-the-previous-steps-can-be-done-in-r-and-stata-in-parellel."><i class="fa fa-check"></i><b>15.2</b> most of the previous steps can be done in R and stata in parellel.</a></li>
<li class="chapter" data-level="15.3" data-path="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html"><a href="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html#output-the-write-up-in-the-r.-only-add-stata-as-complement.---use-tc-as-template."><i class="fa fa-check"></i><b>15.3</b> output the write up in the R. Only add Stata as complement. -&gt; use TC as template.</a></li>
<li class="chapter" data-level="15.4" data-path="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html"><a href="sem-hw5---code-in-the-chunk-but-dont-run-them.-copy-them-as-a-whole-with-the-comments.html#goal-is-to-understand-the-application-of-regression-at-different-angle-to-fully-understand-it."><i class="fa fa-check"></i><b>15.4</b> Goal is to understand the application of regression at different angle to fully understand it.</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Frank’s second book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="applied-stats-model-ii---exam-two-stat-45207520---exam-2" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Applied Stats Model II - Exam Two STAT 4520/7520 - Exam 2<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#applied-stats-model-ii---exam-two-stat-45207520---exam-2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="points-consider-the-two-plots-below-which-show-the-exact-same-x-y-data.-the-difference-is-that-the-right-plot-has-colored-points-based-on-a-grouping-variable.-is-there-a-relationship-between-x-and-y-if-not-how-can-we-explain-the-left-plot-finally-how-would-you-model-the-response-y" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> 1. (7 points) Consider the two plots below, which show the exact same (x, y) data. The difference is that the right plot has colored points based on a grouping variable. Is there a relationship between x and y? If not, how can we explain the left plot? Finally, how would you model the response y?<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-consider-the-two-plots-below-which-show-the-exact-same-x-y-data.-the-difference-is-that-the-right-plot-has-colored-points-based-on-a-grouping-variable.-is-there-a-relationship-between-x-and-y-if-not-how-can-we-explain-the-left-plot-finally-how-would-you-model-the-response-y" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="images/ASM_Q1.PNG" /></p>
<p>No relationship between X and Y if I control for the grouping variable.
Within each group, x and y has no relationship.</p>
<p>I will build a model of Y = X + four dummy variables (5-1 categories).</p>
</div>
<div id="points-say-we-have-a-fitted-armapq-model-given-byy_t-.3y_t1-ε_t-what-are-the-values-of-p-and-q" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> 2. (3 points) Say we have a fitted ARMA(p,q) model given by<span class="math inline">\(Y_t = .3Y_{t−1} + ε_t\)</span> What are the values of p and q?<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-say-we-have-a-fitted-armapq-model-given-byy_t-.3y_t1-ε_t-what-are-the-values-of-p-and-q" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>p is 1
q is 0</p>
</div>
<div id="say-we-observe-100-events-in-a-20ft-10ft-spatial-field-under-a-homogeneous-poisson-process" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> 3. Say we observe 100 events in a 20ft × 10ft spatial field under a homogeneous Poisson process:<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#say-we-observe-100-events-in-a-20ft-10ft-spatial-field-under-a-homogeneous-poisson-process" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>• (4 points) What is the estimate of λ?</p>
<p><span class="math inline">\(\lambda\)</span> is 100 or the average events</p>
<p>• (3 points) If we considered a 100ft × 100ft region, how many events
would we expect?</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span> <span class="sc">*</span> <span class="dv">100</span> <span class="sc">/</span> (<span class="dv">20</span> <span class="sc">*</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## [1] 50</code></pre>
<p>Since the size is 50 times larger and is a homogeneous poisson process, we will expect 50 * 100 = 5000 events.</p>
</div>
<div id="points-suppose-we-are-measuring-some-response-variable-and-our-data-contains-5-locations.-how-would-our-research-goals-be-different-if-we-considered-the-location-factor-as-fixed-vs-random" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> 4. (6 points) Suppose we are measuring some response variable and our data contains 5 locations. How would our research goals be different if we considered the location factor as fixed vs random?<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-suppose-we-are-measuring-some-response-variable-and-our-data-contains-5-locations.-how-would-our-research-goals-be-different-if-we-considered-the-location-factor-as-fixed-vs-random" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The location is considered fixed if we are interested in the specific 5 locations’ effect.</p>
<p>The location is considered as random if we are NOT interested in their specific effect. We consider the five locations as a random sample of n locations.</p>
</div>
<div id="points-using-the-below-keras-code-and-summary-output-justify-the-number-of-parameters-at-each-layer-of-the-neural-network." class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> 5. (7 points) Using the below keras code and summary output, justify the number of parameters at each layer of the neural network.<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-using-the-below-keras-code-and-summary-output-justify-the-number-of-parameters-at-each-layer-of-the-neural-network." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(keras)</span>
<span id="cb4-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb4-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">keras_model_sequential</span>() <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">8</span>, <span class="at">activation=</span> <span class="st">&quot;relu&quot;</span>, <span class="at">input_shape=</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">4</span>, <span class="at">activation=</span> <span class="st">&quot;relu&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-5"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">1</span>, <span class="at">activation=</span> <span class="st">&quot;linear&quot;</span>)</span></code></pre></div>
<pre><code>## Loaded Tensorflow version 2.8.0</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb6-1" aria-hidden="true" tabindex="-1"></a>model <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Model: &quot;sequential&quot;
## ________________________________________________________________________________
##  Layer (type)                       Output Shape                    Param #     
## ================================================================================
##  dense_2 (Dense)                    (None, 8)                       16          
##                                                                                 
##  dense_1 (Dense)                    (None, 4)                       36          
##                                                                                 
##  dense (Dense)                      (None, 1)                       5           
##                                                                                 
## ================================================================================
## Total params: 57
## Trainable params: 57
## Non-trainable params: 0
## ________________________________________________________________________________</code></pre>
<p><img src="images/ASM_Q5.PNG" /></p>
<p>There are units with bias for each layers.Thus,
First layer: 1 input (input_Shape =1) with one bias for each hidden unit. 2 * 8 = 16 parameters.
Second layer: 8 units + 1 bias unit = 9 input units for each hidden unit (4 hidden units in the layer). 9 * 4 = 36 parameters.
Third layer: 4 units + 1 bias unit = 5 input units for each final output unit (1 output unit. 5*1 = 5 parameters.</p>
</div>
<div id="consider-the-below-ann-which-was-fit-to-predict-a-cereals-rating-based-on-its-protein-content.-using-the-provided-weights-and-biases-with-an-input-of-protein4-find" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> 6. Consider the below ANN which was fit to predict a cereal’s rating based on its protein content. Using the provided weights and biases with an input of protein=4, find:<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#consider-the-below-ann-which-was-fit-to-predict-a-cereals-rating-based-on-its-protein-content.-using-the-provided-weights-and-biases-with-an-input-of-protein4-find" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: lower-alpha">
<li>(6 points) The output value of each of the 3 neurons in the hidden layer assuming sigmoid activations.
<img src="images/ASM_Q6.PNG" /></li>
</ol>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb8-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb8-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb8-2" aria-hidden="true" tabindex="-1"></a>y_Sigmoid <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>x))</span>
<span id="cb8-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb8-3" aria-hidden="true" tabindex="-1"></a>h1 <span class="ot">&lt;-</span> <span class="fu">y_Sigmoid</span>((<span class="sc">-</span><span class="fl">0.85181</span>)<span class="sc">*</span>x <span class="sc">+</span> (<span class="sc">-</span><span class="fl">0.28327</span>))</span>
<span id="cb8-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb8-4" aria-hidden="true" tabindex="-1"></a>h2 <span class="ot">&lt;-</span> <span class="fu">y_Sigmoid</span>((<span class="fl">0.01593</span>)<span class="sc">*</span>x <span class="sc">+</span> (<span class="fl">1.04183</span>))</span>
<span id="cb8-5"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb8-5" aria-hidden="true" tabindex="-1"></a>h3 <span class="ot">&lt;-</span> <span class="fu">y_Sigmoid</span>((<span class="sc">-</span><span class="fl">0.68229</span>)<span class="sc">*</span>x <span class="sc">+</span> (<span class="fl">0.52639</span>))</span>
<span id="cb8-6"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(h1)</span></code></pre></div>
<pre><code>## [1] 0.02435147</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(h2)</span></code></pre></div>
<pre><code>## [1] 0.7512986</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(h3)</span></code></pre></div>
<pre><code>## [1] 0.09950202</code></pre>
<p>The output values are the above.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>(3 points) The output rating value assuming a linear activation. Be sure to show your calculatons (feel free to use R)</li>
</ol>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear is identity?</span></span>
<span id="cb14-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb14-2" aria-hidden="true" tabindex="-1"></a>y_identity <span class="ot">&lt;-</span> <span class="cf">function</span>(x) x</span>
<span id="cb14-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb14-3" aria-hidden="true" tabindex="-1"></a>o1 <span class="ot">&lt;-</span> <span class="fu">y_identity</span>((<span class="sc">-</span><span class="fl">0.80025</span>)<span class="sc">*</span><span class="fl">0.02435147</span> <span class="sc">+</span> (<span class="fl">1.23886</span>)<span class="sc">*</span><span class="fl">0.7512986</span> <span class="sc">+</span> (<span class="sc">-</span><span class="fl">0.69436</span>)<span class="sc">*</span><span class="fl">0.09950202</span>  <span class="sc">+</span> (<span class="fl">0.10131</span>))</span>
<span id="cb14-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb14-4" aria-hidden="true" tabindex="-1"></a>o1</span></code></pre></div>
<pre><code>## [1] 0.9434863</code></pre>
<p>The output rating value is 0.9434863</p>
</div>
<div id="points-consider-the-following-acf-plot." class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> 7. (7 points) Consider the following ACF plot.<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-consider-the-following-acf-plot." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Which of the following models is more likely to have generated this
plot? Explain why.</p>
<p>Model A: <span class="math inline">\(Y_t = 0.9Y_{t−1} + ε_t\)</span></p>
<p>Model B: <span class="math inline">\(Y_t = −0.9Y_{t−1} + ε_t\)</span></p>
<p><img src="images/ASM_Q7.PNG" /></p>
<p>Model A is more likely, as the dependency gets weaker.</p>
</div>
<div id="points-the-file-1dconvolutiondata.csv-contains-a-collection-of-100-sequential-points.-read-them-into-r-and-convolve-them-with-the-kernal-c0.054-0.242-0.389-0.242-0.054.-place-the-orginal-signal-as-well-as-the-output-from-the-convolution-on-the-same-plotbe-sure-to-line-them-up-properly.-what-did-this-kernal-do" class="section level2 hasAnchor" number="7.8">
<h2><span class="header-section-number">7.8</span> 8. (5 points) The file 1dConvolutionData.csv contains a collection of 100 sequential points. Read them into R and convolve them with the kernal c(0.054, 0.242, 0.389, 0.242, 0.054). Place the orginal signal as well as the output from the convolution on the same plot(be sure to line them up properly). What did this kernal do?<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#points-the-file-1dconvolutiondata.csv-contains-a-collection-of-100-sequential-points.-read-them-into-r-and-convolve-them-with-the-kernal-c0.054-0.242-0.389-0.242-0.054.-place-the-orginal-signal-as-well-as-the-output-from-the-convolution-on-the-same-plotbe-sure-to-line-them-up-properly.-what-did-this-kernal-do" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#S4 - what does it mean to trim. how does the code work with kernal? purpose of kernal? can&#39;t we observe it already without it? not as obvious? large larger reverse is log?</span></span>
<span id="cb16-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb16-2" aria-hidden="true" tabindex="-1"></a>cnn_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;E:/Cloud/OneDrive - University of Missouri/Mizzou_PhD/Class plan/Applied Stats Model II/Exam 2/1dConvolutionData.csv&quot;</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb17-1" aria-hidden="true" tabindex="-1"></a>input <span class="ot">&lt;-</span> cnn_data<span class="sc">$</span>x </span>
<span id="cb17-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb17-2" aria-hidden="true" tabindex="-1"></a>kernal <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.054</span>, <span class="fl">0.242</span>, <span class="fl">0.389</span>, <span class="fl">0.242</span>, <span class="fl">0.054</span>)</span>
<span id="cb17-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb17-3" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb17-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>(<span class="fu">length</span>(input)<span class="sc">-</span><span class="dv">1</span>)){</span>
<span id="cb17-5"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb17-5" aria-hidden="true" tabindex="-1"></a>value <span class="ot">&lt;-</span> <span class="fu">sum</span>(input[(i<span class="dv">-1</span>)<span class="sc">:</span>(i<span class="sc">+</span><span class="dv">1</span>)]<span class="sc">*</span>kernal)</span>
<span id="cb17-6"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb17-6" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">c</span>(output, value)</span>
<span id="cb17-7"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb17-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-8"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(output)</span></code></pre></div>
<pre><code>##  [1] -0.961955625 -1.915538333 -2.995930056 -3.848004043 -4.551280610
##  [6] -4.972453783 -5.033774992 -5.080213936 -4.524158304 -4.088413561
## [11] -3.275951905 -3.102833509 -3.451367383 -4.049387298 -4.511878784
## [16] -4.663058544 -4.761963824 -5.152595067 -4.706440185 -4.597501059
## [21] -4.689175074 -5.577107860 -6.022871498 -6.771229669 -7.215228565
## [26] -7.950927279 -8.239379008 -8.105257819 -8.214729089 -8.131398312
## [31] -8.220891333 -7.794180158 -8.115268754 -7.727446213 -7.531897294
## [36] -6.767634541 -6.670732895 -6.322696737 -5.833421186 -5.022111464
## [41] -4.446935327 -4.030695578 -3.563526225 -3.320498284 -3.006107104
## [46] -3.109237138 -3.221920085 -3.387963155 -3.518413372 -3.333375517
## [51] -3.052103219 -2.857732771 -2.926663595 -3.336366490 -3.564824304
## [56] -4.023990815 -4.305621947 -4.471155365 -4.298629347 -4.374062962
## [61] -4.280446451 -4.473147585 -4.725700439 -4.750539800 -5.097070001
## [66] -5.502924696 -6.155508490 -6.356331049 -6.464565527 -6.038974647
## [71] -5.815253546 -4.991305976 -4.595765064 -3.785075493 -3.588631575
## [76] -2.613430490 -2.191058762 -1.328527541 -0.733745698  0.208060687
## [81]  0.785040471  1.145025209  0.826156353  0.012339936 -0.304906599
## [86]  0.043322054  0.437272676  0.508118142 -0.336632956 -0.423463117
## [91] -0.470591518 -0.114943473 -0.501087652 -0.364161922 -0.417163670
## [96]  0.002408011 -0.008509076  0.478793847</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(cnn_data$x[2:99],output,type=&quot;hist&quot;,col= c(&quot;blue&quot;,&quot;red&quot;))</span></span>
<span id="cb19-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb19-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(output)</span>
<span id="cb19-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(cnn_data<span class="sc">$</span>x[<span class="dv">2</span><span class="sc">:</span><span class="dv">99</span>])</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The kernal help me find the peak. since the middle points are larger than the surrounding points.</p>
</div>
<div id="time-series-20-points" class="section level2 hasAnchor" number="7.9">
<h2><span class="header-section-number">7.9</span> 9. Time series (20 points)<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#time-series-20-points" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>An AR(1) model with φ = 1 is often referred to as a random walk model.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? AR(1) vs. theta = 1, S17</span></span></code></pre></div>
<div id="a.-3-points-write-the-model-for-yt-mathematically-and-explain-the-intuition-behind-this-naming-convention." class="section level3 hasAnchor" number="7.9.1">
<h3><span class="header-section-number">7.9.1</span> a. (3 points) Write the model for Yt mathematically and explain the intuition behind this naming convention.<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#a.-3-points-write-the-model-for-yt-mathematically-and-explain-the-intuition-behind-this-naming-convention." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math inline">\(Y_t = Y_{t−1} + ε_t\)</span></p>
<p>next period is the same distribution and independent from the previous period plus some random error. It is like walk in a random direction.</p>
</div>
<div id="b.-6-points-using-a-random-error-process-of-ε-n0-1-start-a-random-walk-from-y_1-0-and-continue-for-1000-steps.-plot-the-time-series." class="section level3 hasAnchor" number="7.9.2">
<h3><span class="header-section-number">7.9.2</span> b. (6 points) Using a random error process of ε ∼ N(0, 1), start a random walk from <span class="math inline">\(Y_1 = 0\)</span> and continue for 1000 steps. Plot the time series.<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#b.-6-points-using-a-random-error-process-of-ε-n0-1-start-a-random-walk-from-y_1-0-and-continue-for-1000-steps.-plot-the-time-series." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>); n <span class="ot">&lt;-</span> <span class="dv">1000</span>; eps_t <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb21-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb21-2" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">&lt;-</span> Y2 <span class="ot">&lt;-</span> Y3 <span class="ot">&lt;-</span> <span class="fu">double</span>(n)</span>
<span id="cb21-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb21-3" aria-hidden="true" tabindex="-1"></a>Y1[<span class="dv">1</span>] <span class="ot">&lt;-</span> Y2[<span class="dv">1</span>] <span class="ot">&lt;-</span> Y3[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb21-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Y_t = phi * Y_(t-1) + eps_t</span></span>
<span id="cb21-5"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>n) Y1[i] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">*</span> Y1[i<span class="dv">-1</span>] <span class="sc">+</span> eps_t[i]</span>
<span id="cb21-6"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(Y1,<span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>,<span class="dv">100</span>));</span>
<span id="cb21-7"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#S24 dependent ppt ??? how to set it as AR(1)? theta?</span></span>
<span id="cb22-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co">#set.seed(1); n &lt;- 1000; eps_t &lt;- rnorm(n, sd = 1); par(mfrow=c(1,1))</span></span>
<span id="cb22-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#AR &lt;- MA &lt;- ARMA &lt;- double(n)</span></span>
<span id="cb22-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">#AR[1:2] &lt;- MA[1:2] &lt;- ARMA[1:2] &lt;- 0</span></span>
<span id="cb22-5"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co">#for(i in 3:n) AR[i] &lt;- sum(c(.6, .2) * AR[(i-1):(i-2)]) + eps_t[i]</span></span></code></pre></div>
</div>
<div id="c.-6-points-provide-both-an-autocorrelation-plot-as-well-as-a-partial-autocorrelation-plot.-explain-why-they-are-so-different." class="section level3 hasAnchor" number="7.9.3">
<h3><span class="header-section-number">7.9.3</span> c. (6 points) Provide both an autocorrelation plot as well as a partial autocorrelation plot. Explain why they are so different.<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#c.-6-points-provide-both-an-autocorrelation-plot-as-well-as-a-partial-autocorrelation-plot.-explain-why-they-are-so-different." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#S12 ??? why non-constant variance?</span></span>
<span id="cb23-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co">#S18 </span></span>
<span id="cb23-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb23-3" aria-hidden="true" tabindex="-1"></a>lm_Y1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Y1 <span class="sc">~</span> <span class="fu">I</span>(<span class="dv">1</span><span class="sc">:</span>n))</span></code></pre></div>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb24-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">resid</span>(lm_Y1))</span>
<span id="cb24-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(<span class="fu">resid</span>(lm_Y1))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Partial ACF takes out the general autocorrelation trend while ACF does not (i.e., preseve all the autocorrleation).</p>
</div>
<div id="d.-5-points-change-the-value-of-φ" class="section level3 hasAnchor" number="7.9.4">
<h3><span class="header-section-number">7.9.4</span> d. (5 points) Change the value of φ<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#d.-5-points-change-the-value-of-φ" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>to be something larger than 1 and generate another time series. Plot the
result and on comment on what you observe. Why does the AR(1) model have
the restriction that |φ| &lt; 1?</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>); n <span class="ot">&lt;-</span> <span class="dv">1000</span>; eps_t <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb25-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb25-2" aria-hidden="true" tabindex="-1"></a>Y1 <span class="ot">&lt;-</span> Y2 <span class="ot">&lt;-</span> Y3 <span class="ot">&lt;-</span> <span class="fu">double</span>(n)</span>
<span id="cb25-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb25-3" aria-hidden="true" tabindex="-1"></a>Y1[<span class="dv">1</span>] <span class="ot">&lt;-</span> Y2[<span class="dv">1</span>] <span class="ot">&lt;-</span> Y3[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb25-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Y_t = phi * Y_(t-1) + eps_t</span></span>
<span id="cb25-5"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>n) Y2[i] <span class="ot">&lt;-</span> <span class="fl">1.2</span> <span class="sc">*</span> Y2[i<span class="dv">-1</span>] <span class="sc">+</span> eps_t[i]</span>
<span id="cb25-6"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(Y2,<span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>,<span class="dv">100</span>));</span>
<span id="cb25-7"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-14-1.png" width="672" />
The model explodes. The Y2 goes to infinite.
AR(1) must have the restriction to keep it from exploding.</p>
</div>
</div>
<div id="open-ended-analysis-in-r-29-points" class="section level2 hasAnchor" number="7.10">
<h2><span class="header-section-number">7.10</span> 10. Open Ended Analysis in R (29 points)<a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#open-ended-analysis-in-r-29-points" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The data given in salamanders.csv contains counts of salamanders with
site and sampling covariates. Each of 23 sites was sampled 4 times. The
variables are as follows: • site: name of a location where repeated
samples were taken • mined: factor indicating whether the site was
affected by mountain top removal coal mining • sample: repeated sample •
spp: abbreviated species name, possibly also life stage • count: number
of salamanders observed We are primarily interested if mining is playing
an impact on the counts of salamanders, and also if this effect depends
on the species of salamander.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb26-1" aria-hidden="true" tabindex="-1"></a>salamanders <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;E:/Cloud/OneDrive - University of Missouri/Mizzou_PhD/Class plan/Applied Stats Model II/Exam 2/salamanders.csv&quot;</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li>(4 points) Examine the distribution of
the response. Comment on what you observe and how it will effect your
analysis.</li>
</ol>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(salamanders<span class="sc">$</span>count)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-16-1.png" width="672" />
Based on the histogram, there are many 0s. When there are too many 0s, there could be two distributions. The first is a hurdle from 0 to non-zero. Then the second distribution could be for non-zero responses.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Fit a mixed model to the data. You are free to choose how
to conduct the analysis. Please specifically list the following choices
along with a justification.</li>
</ol>
<p>• (4 points) R package (lme4, MCMCglmm,
glmmTMB, etc)</p>
<p>I will use glmmTMB as it has the flexibity of fitting zero inflated and hurdle model for negative bionomial with random and fixed effects.</p>
<p>• (5 points) Response distribution.</p>
<p>To model the count data with many 0s, I will use zero-inflated negative bionomial regression.</p>
<p>• (7 points) Model
structure (fixed and random effects, etc)</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? does the fixed effect also need to be nested? vs. fixed effect analysis?</span></span></code></pre></div>
<p>Site is random effect since I am not interested in the specific location. There could be more locations to be sampled.
The species are fixed effect since I am interested in the specific type’s impact on the count.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>(6 points) Conduct an
analysis of your fixed effects and comment on how it answers the
questions of interest.</li>
</ol>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)</span>
<span id="cb29-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb29-2" aria-hidden="true" tabindex="-1"></a>sal_glmm_zi <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(count <span class="sc">~</span> <span class="dv">1</span>  <span class="sc">+</span> mined<span class="sc">*</span>spp <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>site),</span>
<span id="cb29-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="at">ziformula=</span><span class="sc">~</span><span class="dv">1</span>,<span class="at">family=</span><span class="fu">nbinom2</span>(<span class="at">link =</span> <span class="st">&quot;log&quot;</span>),</span>
<span id="cb29-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="at">data=</span>salamanders)</span>
<span id="cb29-5"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co">#??? S26 GLMMs - why set parameter = ~1, ~0, </span></span>
<span id="cb29-7"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co">#??? S35 GLMMs count data. how are these diff? glmmTMB, zeroinfl. what&#39;s the scale? log?</span></span>
<span id="cb29-8"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co">#??? S46 Randomeffect -&gt; class nested in school? math, english why? or unique class?</span></span></code></pre></div>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sal_glmm_zi)</span></code></pre></div>
<pre><code>##  Family: nbinom2  ( log )
## Formula:          count ~ 1 + mined * spp + (1 | site)
## Zero inflation:         ~1
## Data: salamanders
## 
##      AIC      BIC   logLik deviance df.resid 
##   1665.3   1741.3   -815.7   1631.3      627 
## 
## Random effects:
## 
## Conditional model:
##  Groups Name        Variance Std.Dev.
##  site   (Intercept) 0.2827   0.5317  
## Number of obs: 644, groups:  site, 23
## 
## Dispersion parameter for nbinom2 family (): 1.04 
## 
## Conditional model:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        1.3739     0.2429   5.657 1.54e-08 ***
## minedyes          -2.2238     0.3954  -5.624 1.87e-08 ***
## sppDF             -0.7417     0.2481  -2.990  0.00279 ** 
## sppDM             -0.4769     0.2413  -1.976  0.04813 *  
## sppEC-A           -1.4398     0.2705  -5.324 1.02e-07 ***
## sppEC-L           -0.0993     0.2377  -0.418  0.67619    
## sppGP             -0.5779     0.2422  -2.386  0.01701 *  
## sppPR             -2.2247     0.3109  -7.155 8.34e-13 ***
## minedyes:sppDF     0.8066     0.4521   1.784  0.07442 .  
## minedyes:sppDM     0.2157     0.4633   0.466  0.64156    
## minedyes:sppEC-A  -0.3567     0.6537  -0.546  0.58531    
## minedyes:sppEC-L  -0.6005     0.5025  -1.195  0.23208    
## minedyes:sppGP    -1.9324     0.8159  -2.368  0.01786 *  
## minedyes:sppPR     0.6446     0.6331   1.018  0.30862    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Zero-inflation model:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)   -4.354      7.862  -0.554     0.58</code></pre>
<p>The fixed effect analysis show that:
Mining has a negative and significant simple effect on the number of salamanders (-2.22), p &lt; 0.01.
Mining’s effect depends on the specie. The GP specie has a negative interaction with the mining. When there is minig, the GP specie’s count decrease is much higher (-1.93), p&lt;0.05</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>(3 points) Create one or more diagnostic plots
and comment.</li>
</ol>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(sal_glmm_zi),<span class="at">main=</span><span class="st">&quot;QQ plot of Residuals&quot;</span>)</span>
<span id="cb32-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(sal_glmm_zi))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-20-1.png" width="672" />
The model doesn’t fit well as the two ends deviate from the normal line.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? how to fix? is it the outlier?</span></span>
<span id="cb33-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co">#??? how to interpret? S50 random effect ppt</span></span>
<span id="cb33-3"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(sal_glmm_zi),<span class="fu">residuals</span>(sal_glmm_zi),<span class="at">xlab=</span><span class="st">&quot;Fitted&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Residuals&quot;</span>,<span class="at">main=</span><span class="st">&quot;Residuals vs Fitted&quot;</span>)</span>
<span id="cb33-4"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#qqnorm(ranef(sal_glmm_zi)$site[[1]],main=&quot;site Effects&quot;)</span></span>
<span id="cb34-2"><a href="applied-stats-model-ii---exam-two-stat-45207520---exam-2.html#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#qqline(ranef(sal_glmm_zi)$site[[1]])</span></span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="applied-stats-model-ii---exam-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="asm2-hw-term-project.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/lyf718718/Book2.git/edit/master/ASM2_Exam2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/lyf718718/Book2.git/blob/master/ASM2_Exam2.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
