<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Question 1: | ASM_II_Class_Note</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Question 1: | ASM_II_Class_Note" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://lyf718718.github.io/Book2/" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Question 1: | ASM_II_Class_Note" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Yufan Lin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="applied-stats-model-ii---exam-1.html"/>
<link rel="next" href="question-2.html"/>
<script src="libs/header-attrs-2.12/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Frank second book</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html"><i class="fa fa-check"></i><b>1</b> Selling and buying process:<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salespeople-skill-perception"><i class="fa fa-check"></i><b>1.1</b> Salespeople skill/ perception<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#communication---intraorganization"><i class="fa fa-check"></i><b>1.2</b> Communication - intraorganization<span></span></a></li>
<li class="chapter" data-level="1.3" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#communication-interorganization---fle-interactions"><i class="fa fa-check"></i><b>1.3</b> Communication Interorganization - FLE interactions<span></span></a></li>
<li class="chapter" data-level="1.4" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#sales-marketing-interface"><i class="fa fa-check"></i><b>1.4</b> Sales marketing interface<span></span></a></li>
<li class="chapter" data-level="1.5" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#firm-level-impact-on-salespeople"><i class="fa fa-check"></i><b>1.5</b> Firm level impact on salespeople<span></span></a></li>
<li class="chapter" data-level="1.6" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salesperson-trait-orientation"><i class="fa fa-check"></i><b>1.6</b> Salesperson trait orientation<span></span></a></li>
<li class="chapter" data-level="1.7" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salesperson-non-sales-activity-service"><i class="fa fa-check"></i><b>1.7</b> Salesperson non-sales activity/ service<span></span></a></li>
<li class="chapter" data-level="1.8" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#b2g-selling"><i class="fa fa-check"></i><b>1.8</b> B2G selling<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="literature-review-note.html"><a href="literature-review-note.html"><i class="fa fa-check"></i><b>2</b> Literature Review Note<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="literature-review-note.html"><a href="literature-review-note.html#persuasion-knowledge-model-review"><i class="fa fa-check"></i><b>2.1</b> Persuasion knowledge Model Review<span></span></a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="literature-review-note.html"><a href="literature-review-note.html#summary-for-pkm-in-online-environment"><i class="fa fa-check"></i><b>2.1.1</b> Summary for PKM in online environment<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html"><i class="fa fa-check"></i><b>3</b> Database marketing substantive domain<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#key-issues"><i class="fa fa-check"></i><b>3.1</b> Key Issues<span></span></a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#data-privacy"><i class="fa fa-check"></i><b>3.1.1</b> Data Privacy<span></span></a></li>
<li class="chapter" data-level="3.1.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#customer-lifetime-value-ltv"><i class="fa fa-check"></i><b>3.1.2</b> Customer lifetime value (LTV)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#method"><i class="fa fa-check"></i><b>3.2</b> Method<span></span></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#rfm"><i class="fa fa-check"></i><b>3.2.1</b> RFM<span></span></a></li>
<li class="chapter" data-level="3.2.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#market-basket-analysis"><i class="fa fa-check"></i><b>3.2.2</b> Market basket analysis<span></span></a></li>
<li class="chapter" data-level="3.2.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#collaborative-filtering"><i class="fa fa-check"></i><b>3.2.3</b> Collaborative filtering<span></span></a></li>
<li class="chapter" data-level="3.2.4" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#cluster-analysis"><i class="fa fa-check"></i><b>3.2.4</b> Cluster analysis<span></span></a></li>
<li class="chapter" data-level="3.2.5" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#decision-trees"><i class="fa fa-check"></i><b>3.2.5</b> Decision trees<span></span></a></li>
<li class="chapter" data-level="3.2.6" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#machine-learning"><i class="fa fa-check"></i><b>3.2.6</b> Machine learning<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#sub---substantive-areas"><i class="fa fa-check"></i><b>3.3</b> Sub - substantive areas<span></span></a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#acquisition"><i class="fa fa-check"></i><b>3.3.1</b> Acquisition<span></span></a></li>
<li class="chapter" data-level="3.3.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#retention-churn-management"><i class="fa fa-check"></i><b>3.3.2</b> Retention/ Churn management<span></span></a></li>
<li class="chapter" data-level="3.3.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#cross-selling-and-up-selling"><i class="fa fa-check"></i><b>3.3.3</b> Cross-selling and up-selling<span></span></a></li>
<li class="chapter" data-level="3.3.4" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#reward-program"><i class="fa fa-check"></i><b>3.3.4</b> Reward program<span></span></a></li>
<li class="chapter" data-level="3.3.5" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#multichannel-customer"><i class="fa fa-check"></i><b>3.3.5</b> Multichannel customer<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-scientist-job.html"><a href="data-scientist-job.html"><i class="fa fa-check"></i><b>4</b> Data Scientist Job<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#business-strategy-track-a.k.a-marketing-analytics"><i class="fa fa-check"></i><b>4.1</b> Business strategy Track (a.k.a Marketing Analytics)<span></span></a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#database-marketing"><i class="fa fa-check"></i><b>4.1.1</b> Database marketing<span></span></a></li>
<li class="chapter" data-level="4.1.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#programming"><i class="fa fa-check"></i><b>4.1.2</b> Programming<span></span></a></li>
<li class="chapter" data-level="4.1.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#statistics"><i class="fa fa-check"></i><b>4.1.3</b> Statistics:<span></span></a></li>
<li class="chapter" data-level="4.1.4" data-path="data-scientist-job.html"><a href="data-scientist-job.html#visualization"><i class="fa fa-check"></i><b>4.1.4</b> Visualization<span></span></a></li>
<li class="chapter" data-level="4.1.5" data-path="data-scientist-job.html"><a href="data-scientist-job.html#automation"><i class="fa fa-check"></i><b>4.1.5</b> Automation<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#consumer-insight-track-aka.-marketing-research"><i class="fa fa-check"></i><b>4.2</b> Consumer insight Track (aka. Marketing Research)<span></span></a></li>
<li class="chapter" data-level="4.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#optimization-track-a.k.a-operational-research"><i class="fa fa-check"></i><b>4.3</b> Optimization Track (a.k.a Operational Research)<span></span></a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#model-optimization"><i class="fa fa-check"></i><b>4.3.1</b> Model optimization<span></span></a></li>
<li class="chapter" data-level="4.3.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#macro-level-models"><i class="fa fa-check"></i><b>4.3.2</b> Macro level models<span></span></a></li>
<li class="chapter" data-level="4.3.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#academic-paper-implementation"><i class="fa fa-check"></i><b>4.3.3</b> Academic Paper implementation<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html"><i class="fa fa-check"></i><b>5</b> Marketing Strategy PhD skills<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#reading"><i class="fa fa-check"></i><b>5.1</b> Reading<span></span></a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#meta-skill-to-gain"><i class="fa fa-check"></i><b>5.1.1</b> Meta skill to gain<span></span></a></li>
<li class="chapter" data-level="5.1.2" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#reading-purpose"><i class="fa fa-check"></i><b>5.1.2</b> Reading Purpose<span></span></a></li>
<li class="chapter" data-level="5.1.3" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#how-to-train"><i class="fa fa-check"></i><b>5.1.3</b> How to train<span></span></a></li>
<li class="chapter" data-level="5.1.4" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#suggested-reading-optional"><i class="fa fa-check"></i><b>5.1.4</b> Suggested reading (optional)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#writing"><i class="fa fa-check"></i><b>5.2</b> Writing<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html"><i class="fa fa-check"></i><b>6</b> Applied Stats Model II - Exam 1<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-in-a-poisson-regression-problem-with-one-explanatory-variable-x-the-estimate-of-the-β"><i class="fa fa-check"></i><b>6.1</b> 1. (7 points) In a poisson regression problem with one explanatory variable x, the estimate of the β<span></span></a></li>
<li class="chapter" data-level="6.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-in-a-generalized-linear-model-why-is-the-null-deviance-typically-larger-than-the-residual-deviance"><i class="fa fa-check"></i><b>6.2</b> 2. (5 points) In a generalized linear model, why is the null deviance typically larger than the residual deviance?<span></span></a></li>
<li class="chapter" data-level="6.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-can-standard-linear-regression-ever-be-used-when-the-data-are-counts-explain-why-or-why-not."><i class="fa fa-check"></i><b>6.3</b> 3. (5 points) Can standard linear regression ever be used when the data are counts? Explain why or why not.<span></span></a></li>
<li class="chapter" data-level="6.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#take-the-following-random-effect-model"><i class="fa fa-check"></i><b>6.4</b> 4. Take the following random effect model<span></span></a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#section"><i class="fa fa-check"></i><b>6.4.1</b> </a></li>
<li class="chapter" data-level="6.4.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-find-the-intra-class-correlation-coefficient."><i class="fa fa-check"></i><b>6.4.2</b> (3 points) Find the intra class correlation coefficient.<span></span></a></li>
<li class="chapter" data-level="6.4.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-which-level-of-the-random-effect-α-will-have-the-largest-predicted-value"><i class="fa fa-check"></i><b>6.4.3</b> (2 points) Which level of the random effect α will have the largest predicted value?<span></span></a></li>
<li class="chapter" data-level="6.4.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-predict-y-for-level-6-of-the-random-effect."><i class="fa fa-check"></i><b>6.4.4</b> (2 points) Predict y for level 6 of the random effect.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#utilizing-the-below-code-and-output-answer-the-following"><i class="fa fa-check"></i><b>6.5</b> 5. Utilizing the below code and output, answer the following:<span></span></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-why-are-the-residual-and-null-deviance-values-the-same"><i class="fa fa-check"></i><b>6.5.1</b> • (3 points) Why are the residual and null deviance values the same?<span></span></a></li>
<li class="chapter" data-level="6.5.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-based-on-these-deviance-values-does-the-model-fit-well-does-this-make-sense"><i class="fa fa-check"></i><b>6.5.2</b> • (2 points) Based on these deviance values, does the model “fit” well? Does this make sense?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#take-the-data-given-by-problem6data.csv-which-contains-a-continuous-response-y-and-two-predictors-x1-and-x2."><i class="fa fa-check"></i><b>6.6</b> 6. Take the data given by Problem6Data.csv, which contains a continuous response y and two predictors x1 and x2.<span></span></a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#a.-5-points-read-the-data-into-r-and-make-some-plots-between-the-response-and-predictors.-describe-the-patterns-and-comment-on-behaviors-you-observe-with-exact-0s."><i class="fa fa-check"></i><b>6.6.1</b> a. (5 points) Read the data into R and make some plots between the response and predictors. Describe the patterns and comment on behaviors you observe with exact 0s.<span></span></a></li>
<li class="chapter" data-level="6.6.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#b.-5-points-make-a-histogram-of-the-response-variable-and-comment-on-the-shape.-are-the-values-strictly-positive"><i class="fa fa-check"></i><b>6.6.2</b> b. (5 points) Make a histogram of the response variable and comment on the shape. Are the values strictly positive?<span></span></a></li>
<li class="chapter" data-level="6.6.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#c.-4-points-state-the-range-that-the-index-parameter-p-for-use-in-the-tweedie-distribution-must-be-contained-in.-why-is-this-the-case"><i class="fa fa-check"></i><b>6.6.3</b> c. (4 points) State the range that the index parameter p, for use in the Tweedie distribution, must be contained in. Why is this the case?<span></span></a></li>
<li class="chapter" data-level="6.6.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#d.-6-points-find-an-optimal-value-of-p-for-use-in-the-tweedie-distribution-using-a-log-link."><i class="fa fa-check"></i><b>6.6.4</b> d. (6 points) Find an optimal value of p for use in the Tweedie Distribution, using a log link.<span></span></a></li>
<li class="chapter" data-level="6.6.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#e.-5-points-again-using-a-log-link-fit-a-tweedie-distribution-using-the-index-parameter-value-you-obtained-in-part-d."><i class="fa fa-check"></i><b>6.6.5</b> e. (5 points) Again using a log link, fit a Tweedie Distribution using the index parameter value you obtained in part d.<span></span></a></li>
<li class="chapter" data-level="6.6.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#f.-6-points-for-each-of-the-values-of-x2-given-by-the-r-vector-x2_vals---seq0-15-by-.01-use-the-compound-poisson-gamma-structure-to-predict-the-probability-of-obtaining-an-exact-0-response-when-x1-is-at-its-mean-value."><i class="fa fa-check"></i><b>6.6.6</b> f. (6 points) For each of the values of x2 given by the R vector x2_vals &lt;- seq(0, 15, by= .01), use the compound Poisson-Gamma structure to predict the probability of obtaining an exact 0 response when x1 is at its mean value.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#the-ships-dataset-in-the-mass-package-provides-the-number-of-incidentsindicents-resulting-in-ship-damage-as-a-function-of-total-months-of-serviceservice-ship-typetype-as-well-as-year-of-ship-constructionyear-broken-into-5-year-increments-with-the-years-variable-value-indicating-the-beginning-of-this-period.-e.g.-year60-refers-to-1960-1964-period-of-operationperiod-with-realizations-60-1960---1974-75-1975---1979-the-data-can-be-loaded-with-dataships-packagemass"><i class="fa fa-check"></i><b>6.7</b> 7. The ships dataset in the MASS package provides the number of incidents(indicents) resulting in ship damage as a function of total months of service(service), ship type(type), as well as: • Year of ship construction(year) – Broken into 5 year increments with the year’s variable value indicating the beginning of this period. e.g. year=60 refers to 1960-1964 • Period of operation(period) with realizations: – 60: 1960 - 1974 – 75: 1975 - 1979 The data can be loaded with: data(ships, package=“MASS”)<span></span></a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#a.-4-points-use-group_by-and-summarise-to-compute-the-average-months-of-service-for-each-combination-of-year-of-construction-and-period-of-operation.-explain-why-there-is-a-0-in-the-result."><i class="fa fa-check"></i><b>6.7.1</b> a. (4 points) Use group_by and summarise to compute the average months of service for each combination of year of construction and period of operation. Explain why there is a 0 in the result.<span></span></a></li>
<li class="chapter" data-level="6.7.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#b.-3-points-create-a-new-filtered-dataset-by-removing-the-rows-where-service0."><i class="fa fa-check"></i><b>6.7.2</b> b. (3 points) Create a new filtered dataset by removing the rows where service=0.<span></span></a></li>
<li class="chapter" data-level="6.7.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#c.-10-points-fit-both-a-poisson-rate-model-and-negative-binomial-rate-model-model-using-number-of-incidents-per-service-month-as-the-response-and-all-other-variables-as-predictors.-compare-which-model-is-better-using-aic."><i class="fa fa-check"></i><b>6.7.3</b> c. (10 points) Fit both a Poisson rate model and Negative Binomial rate model model using number of incidents per service month as the response and all other variables as predictors. Compare which model is better using AIC.<span></span></a></li>
<li class="chapter" data-level="6.7.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#d.-7-points-using-the-better-model-selected-in-part-c-assess-the-significance-of-each-term-using-drop1.-which-terms-are-insignificant-remove-the-insignificant-variables-from-the-model-in-c-and-refit."><i class="fa fa-check"></i><b>6.7.4</b> d. (7 points) Using the better model selected in part c, assess the significance of each term using drop1(). Which terms are insignificant? Remove the insignificant variables from the model in c, and refit.<span></span></a></li>
<li class="chapter" data-level="6.7.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#e.-6-points-statistically-compare-the-residual-deviance-in-your-final-model-from-d-to-the-null-deviance."><i class="fa fa-check"></i><b>6.7.5</b> e. (6 points) Statistically compare the residual deviance in your final model from d to the null deviance.<span></span></a></li>
<li class="chapter" data-level="6.7.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#f.-4-points-compare-the-aic-from-the-reduced-model-in-d-to-the-corresponding-value-from-c.-is-the-change-you-see-expected-also-examine-the-residual-deviance-of-the-model-in-d-what-does-it-say-about-the-models-fit-to-the-data"><i class="fa fa-check"></i><b>6.7.6</b> f. (4 points) Compare the AIC from the reduced model in d to the corresponding value from c. Is the change you see expected? Also examine the residual deviance of the model in d, what does it say about the model’s fit to the data?<span></span></a></li>
<li class="chapter" data-level="6.7.7" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#g.-6-points-make-a-plot-of-the-deviance-residuals-vs-the-predicted-valueslink-scale.-how-is-the-fit"><i class="fa fa-check"></i><b>6.7.7</b> g. (6 points) Make a plot of the deviance residuals vs the predicted values(link scale). How is the fit?<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="question-1.html"><a href="question-1.html"><i class="fa fa-check"></i><b>7</b> Question 1:<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="question-1.html"><a href="question-1.html#a.-8-points-create-plots-to-examine-how-launch-speed-and-angle-may-affect-the-probability-of-a-home-run-and-describe-your-findings."><i class="fa fa-check"></i><b>7.1</b> a. (8 points) Create plots to examine how launch speed and angle may affect the probability of a home run and describe your findings.<span></span></a></li>
<li class="chapter" data-level="7.2" data-path="question-1.html"><a href="question-1.html#b.-9-points-fit-a-logistic-regression-model-with-home_run-as-the-response-and-all-other-variables-as-predictors.-conduct-a-deviance-test-to-assess-if-this-model-is-better-than-the-null-model."><i class="fa fa-check"></i><b>7.2</b> b. (9 points) Fit a logistic regression model with home_run as the response and all other variables as predictors. Conduct a deviance test to assess if this model is better than the null model.<span></span></a></li>
<li class="chapter" data-level="7.3" data-path="question-1.html"><a href="question-1.html#c.-8-points-conduct-deviance-tests-with-the-drop1-function-to-assess-the-significance-of-each-individual-variable-and-report-the-results.-compare-the-p-values-to-those-obtained-from-summary."><i class="fa fa-check"></i><b>7.3</b> c. (8 points) Conduct deviance tests with the drop1() function to assess the significance of each individual variable and report the results. Compare the p-values to those obtained from summary().<span></span></a></li>
<li class="chapter" data-level="7.4" data-path="question-1.html"><a href="question-1.html#d.-6-points-fit-a-smaller-model-after-removing-all-variables-which-are-insignificant-using-α-0.05.-compare-this-model-to-the-larger-model-are-they-significantly-different-what-are-the-implications-of-this-with-regard-to-model-selection-until-the-end-of-this-question-use-the-smaller-model-for-all-analysis"><i class="fa fa-check"></i><b>7.4</b> d. (6 points) Fit a smaller model after removing all variables which are insignificant using α = 0.05. Compare this model to the larger model, are they significantly different? What are the implications of this with regard to model selection? Until the end of this question, use the smaller model for all analysis<span></span></a></li>
<li class="chapter" data-level="7.5" data-path="question-1.html"><a href="question-1.html#e.-7-points-how-does-the-launch-speed-after-the-ball-is-hit-affect-the-odds-of-homerun-occurring-provide-a-confidence-interval-for-this-value."><i class="fa fa-check"></i><b>7.5</b> e. (7 points) How does the launch speed after the ball is hit affect the <strong>odds of HomeRun occurring</strong>? Provide a confidence interval for this value.<span></span></a></li>
<li class="chapter" data-level="7.6" data-path="question-1.html"><a href="question-1.html#f.-5-points-using-the-deviance-residuals-make-a-binned-residual-vs-fitted-probability-plot-and-comment-on-the-fit-of-the-model."><i class="fa fa-check"></i><b>7.6</b> f. (5 points) Using the deviance residuals, make a binned residual vs fitted probability plot and comment on the fit of the model.<span></span></a></li>
<li class="chapter" data-level="7.7" data-path="question-1.html"><a href="question-1.html#g.-4-points-using-a-probability-of-0.5-as-the-threshold-for-predicting-an-observation-yielding-a-home-run-create-a-table-classifying-the-predictions-against-the-observed-values.-describe-your-findings.-what-is-the-misclassification-rate"><i class="fa fa-check"></i><b>7.7</b> g. (4 points) Using a probability of 0.5 as the threshold for predicting an observation yielding a home run, create a table classifying the predictions against the observed values. Describe your findings. What is the misclassification rate?<span></span></a></li>
<li class="chapter" data-level="7.8" data-path="question-1.html"><a href="question-1.html#h.-6-points-using-probability-thresholds-from-0.005-to-0.995-obtain-the-sensitivities-and-specificity-of-the-resulting-predictions.-create-an-roc-plot-and-comment-on-the-effectiveness-of-the-models-ability-to-correctly-classify-the-response.-as-we-vary-the-threshold-to-determine-classifications-is-inverse-relationship-between-sensitivity-and-specificity-strongly-evident"><i class="fa fa-check"></i><b>7.8</b> h. (6 points) Using probability thresholds from 0.005 to 0.995, obtain the sensitivities and specificity of the resulting predictions. Create an ROC plot and comment on the effectiveness of the model’s ability to correctly classify the response. As we vary the threshold to determine classifications, is inverse relationship between sensitivity and specificity strongly evident?<span></span></a></li>
<li class="chapter" data-level="7.9" data-path="question-1.html"><a href="question-1.html#i.-5-points-produce-a-plot-of-the-sensitivity-and-specificity-against-the-threshold.-is-there-a-threshold-for-classification-you-would-recommend-that-provides-a-good-balance-between-the-two-make-another-confusion-matrix-using-this-cutoff-how-does-the-result-compare-to-the-previous-one-consider-the-types-of-errors-you-observe."><i class="fa fa-check"></i><b>7.9</b> i. (5 points) Produce a plot of the sensitivity and specificity against the threshold. Is there a threshold for classification you would recommend that provides a good balance between the two? Make another confusion matrix using this cutoff, how does the result compare to the previous one? Consider the types of errors you observe.<span></span></a></li>
<li class="chapter" data-level="7.10" data-path="question-1.html"><a href="question-1.html#j.-3-points-consider-a-logistic-model-with-only-launch_angle-and-launch_speed-being-used-to-predict-the-probability-of-a-home-run.-what-is-the-aic-of-this-model"><i class="fa fa-check"></i><b>7.10</b> j. (3 points) Consider a logistic model with only launch_angle and launch_speed being used to predict the probability of a home run. What is the AIC of this model?<span></span></a></li>
<li class="chapter" data-level="7.11" data-path="question-1.html"><a href="question-1.html#k.-11-points-create-a-dummy-variable-which-is-1-if-launch_angle-is-between-20-and-40-degrees-and-use-this-variable-in-your-model-instead-of-the-raw-value-for-launch_angle.-then-complete-the-following-1.-compare-the-aic-of-this-model-to-the-model-in-part-j-which-model-is-better-2.-what-does-the-coefficient-of-your-dummy-variable-mean-interpret-the-value.-3.-interpret-the-value-of-the-intercept-by-converting-to-a-probability.-does-this-result-make-sense"><i class="fa fa-check"></i><b>7.11</b> k. (11 points) Create a dummy variable which is 1 if launch_angle is between 20 and 40 degrees and use this variable in your model instead of the raw value for launch_angle. Then, complete the following: 1. Compare the AIC of this model to the model in part j, which model is better? 2. What does the coefficient of your dummy variable mean? Interpret the value. 3. Interpret the value of the intercept by converting to a probability. Does this result make sense?<span></span></a>
<ul>
<li class="chapter" data-level="7.11.1" data-path="question-1.html"><a href="question-1.html#section-1"><i class="fa fa-check"></i><b>7.11.1</b> </a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="question-2.html"><a href="question-2.html"><i class="fa fa-check"></i><b>8</b> Question 2<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="question-2.html"><a href="question-2.html#a.-5-points-make-a-plot-or-set-of-tables-showing-the-distribution-of-lsd-use-between-genders-and-interpret.-you-can-use-code-similar-to-that-on-slide-84-of-the-course-notes."><i class="fa fa-check"></i><b>8.1</b> a. (5 points) Make a plot or set of tables showing the distribution of LSD use between genders and interpret. You can use code similar to that on slide 84 of the course notes.<span></span></a></li>
<li class="chapter" data-level="8.2" data-path="question-2.html"><a href="question-2.html#b.-9-points-fit-a-proportional-odds-model-using-lsd-as-the-response-variable-and-the-other-variables-listed-above-as-predictors.-using-drop1-test-if-the-variables-are-significant-or-insignificant-and-describe-2-your-results."><i class="fa fa-check"></i><b>8.2</b> b. (9 points) Fit a proportional odds model using LSD as the response variable and the other variables listed above as predictors. Using drop1(), test if the variables are significant or insignificant and describe 2 your results.<span></span></a></li>
<li class="chapter" data-level="8.3" data-path="question-2.html"><a href="question-2.html#c.-6-points-interpret-the-values-of-the-intercepts-θj-."><i class="fa fa-check"></i><b>8.3</b> c. (6 points) Interpret the values of the intercepts θj .<span></span></a></li>
<li class="chapter" data-level="8.4" data-path="question-2.html"><a href="question-2.html#d.-10-points-print-the-coefficient-table-and-interpret-the-values-of-the-significant-personality-characteristics."><i class="fa fa-check"></i><b>8.4</b> d. (10 points) Print the coefficient table and interpret the values of the significant personality characteristics.<span></span></a></li>
<li class="chapter" data-level="8.5" data-path="question-2.html"><a href="question-2.html#e.-7250-only-6-points-explore-interacting-some-of-the-categorical-demographic-variables-with-the-personality-measurements-and-report-your-findings-does-the-nature-of-any-personality-characteristics-affect-on-lsd-usage-change-according-to-your-analysis"><i class="fa fa-check"></i><b>8.5</b> e. (7250 only) (6 points) Explore interacting some of the categorical demographic variables with the personality measurements and report your findings, does the nature of any personality characteristics affect on LSD usage change according to your analysis?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html"><i class="fa fa-check"></i><b>9</b> 1 1) Modeling the Number of Claims<span></span></a>
<ul>
<li class="chapter" data-level="9.1" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#a.-5-points-create-a-table-to-present-the-distribution-of-the-number-of-claims-by-computing-the-proportion-of-each-possibility.-what-percent-of-the-policies-have-0-claims"><i class="fa fa-check"></i><b>9.1</b> a. (5 points) Create a table to present the distribution of the number of claims by computing the proportion of each possibility. What percent of the policies have 0 claims?<span></span></a></li>
<li class="chapter" data-level="9.2" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#b.-6-points-create-a-poisson-regression-to-predict-the-number-of-claims-in-the-year-using-only-the-variables-for-vehicle-age-driver-age-bonusmalus-and-density.-what-is-the-deviance-does-is-differ-significantly-from-the-null-deviance"><i class="fa fa-check"></i><b>9.2</b> b. (6 points) Create a Poisson regression to predict the number of claims in the year using only the variables for vehicle age, driver age, bonusMalus, and density. What is the deviance? Does is differ significantly from the null deviance?<span></span></a></li>
<li class="chapter" data-level="9.3" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#c.-4-points-generate-predictions-on-the-response-scale-µ-and-round-them-to-the-nearest-count.-create-a-table-as-in-part-a-and-comment-on-how-similar-or-dissimilar-this-result-is."><i class="fa fa-check"></i><b>9.3</b> c. (4 points) Generate predictions on the response scale µ and round them to the nearest count. Create a table as in part a and comment on how similar or dissimilar this result is.<span></span></a></li>
<li class="chapter" data-level="9.4" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#d.-3-points-fit-a-negative-binomial-model-to-the-data-and-generate-predictions-as-in-part-c.-did-this-solve-the-problem"><i class="fa fa-check"></i><b>9.4</b> d. (3 points) Fit a negative binomial model to the data and generate predictions as in part c. Did this solve the problem?<span></span></a></li>
<li class="chapter" data-level="9.5" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#e.-5-points-now-fit-a-zero-inflation-poisson-model-zip-and-compute-the-fitted-proportion-of-zero-counts-as-on-slide-38-of-the-poisson-notes.-does-this-help"><i class="fa fa-check"></i><b>9.5</b> e. (5 points) Now fit a zero inflation Poisson model (ZIP) and compute the fitted proportion of zero counts as on slide 38 of the Poisson Notes. Does this help?<span></span></a></li>
<li class="chapter" data-level="9.6" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#f.-8-points-interpret-the-signs-of-the-coefficient-estimates-out-of-the-zip-model-both-the-count-portion-as-well-as-the-zero-inflated-portion"><i class="fa fa-check"></i><b>9.6</b> f. (8 points) Interpret the signs of the coefficient estimates out of the ZIP model, both the count portion as well as the zero inflated portion!<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="modeling-the-average-claim-payout.html"><a href="modeling-the-average-claim-payout.html"><i class="fa fa-check"></i><b>10</b> 2) Modeling the Average Claim Payout<span></span></a>
<ul>
<li class="chapter" data-level="10.1" data-path="modeling-the-average-claim-payout.html"><a href="modeling-the-average-claim-payout.html#a.-3-points-in-this-problem-we-will-focus-on-modeling-the-positive-continuous-variable-avgclaimamount.-attempt-to-fit-a-gamma-regression-with-a-log-link-predicting-avgclaimamount-as-a-function-of-all-feature-variables-in-the-dataset.-what-happens-when-you-attempt-to-fit-this-model"><i class="fa fa-check"></i><b>10.1</b> a. (3 points) In this problem we will focus on modeling the positive continuous variable “AvgClaimAmount.” Attempt to fit a Gamma regression with a log link, predicting AvgClaimAmount as a function of all feature variables in the dataset. What happens when you attempt to fit this model?<span></span></a></li>
<li class="chapter" data-level="10.2" data-path="modeling-the-average-claim-payout.html"><a href="modeling-the-average-claim-payout.html#b.-5-points-create-a-new-dataset-consisting-of-the-rows-that-correspond-to-strictly-positive-realizations-of-avgclaimamount.-make-a-histogram-of-this-variable-on-standard-and-log-scale-and-describe-your-findings."><i class="fa fa-check"></i><b>10.2</b> b. (5 points) Create a new dataset consisting of the rows that correspond to strictly positive realizations of AvgClaimAmount. Make a histogram of this variable on standard and log scale and describe your findings.<span></span></a></li>
<li class="chapter" data-level="10.3" data-path="modeling-the-average-claim-payout.html"><a href="modeling-the-average-claim-payout.html#c.-4-points-fit-the-gamma-regression-proposed-in-part-a-to-the-filtered-dataset.-do-you-notice-anything-strange-how-many-iterations-did-it-take-glm-to-find-this-result"><i class="fa fa-check"></i><b>10.3</b> c. (4 points) Fit the Gamma regression proposed in part a to the filtered dataset. Do you notice anything strange? How many iterations did it take glm() to find this result?<span></span></a></li>
<li class="chapter" data-level="10.4" data-path="modeling-the-average-claim-payout.html"><a href="modeling-the-average-claim-payout.html#d.-3-points-to-the-glm-function-add-the-argument-control-listmaxit-500.-what-do-you-think-this-will-do-fit-the-model-and-examine-the-summary-output-to-check-the-number-of-iterations-needed-for-convergence."><i class="fa fa-check"></i><b>10.4</b> d. (3 points) To the glm() function, add the argument control = list(maxit = 500). What do you think this will do? Fit the model and examine the summary output to check the number of iterations needed for convergence.<span></span></a></li>
<li class="chapter" data-level="10.5" data-path="modeling-the-average-claim-payout.html"><a href="modeling-the-average-claim-payout.html#e.3-points-from-the-model-in-e.-interpret-the-parameter-estimate-for-a-vehicles-age"><i class="fa fa-check"></i><b>10.5</b> e.(3 points) From the model in e. Interpret the parameter estimate for a vehicle’s age<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="tweedie.html"><a href="tweedie.html"><i class="fa fa-check"></i><b>11</b> 3. Tweedie<span></span></a>
<ul>
<li class="chapter" data-level="11.1" data-path="tweedie.html"><a href="tweedie.html#a.-8-points-using-the-entire-dataset-create-a-profile-likelihood-of-the-index-values-p-for-use-in-a-glm-utilizing-the-tweedie-distribution-to-predict-purepremium-directly.-make-a-plot-of-the-profile-likelihood-and-select-the-best-value.-7520---3-points-for-graduate-students-i-expect-some-exploration-to-find-the-best-value-as-these-data-are-quite-poorly-behaved.-look-at-the-value-section-of-tweedie.profile-for-some-hints-and-i-would-suggest-narrowing-the-search-space-for-p-and-evaluating-it-on-a-somewhat-fine-grid."><i class="fa fa-check"></i><b>11.1</b> a. (8 points) Using the entire dataset, create a profile likelihood of the index values p for use in a glm utilizing the Tweedie distribution to predict PurePremium directly. Make a plot of the profile likelihood and select the best value. (7520 - 3 points): For graduate students, I expect some <strong>exploration to find the best value as these data are quite poorly behaved</strong>. Look at the “Value” section of ?tweedie.profile for some hints, and I <strong>would suggest narrowing the search space for p and evaluating it on a somewhat fine grid.</strong><span></span></a></li>
<li class="chapter" data-level="11.2" data-path="tweedie.html"><a href="tweedie.html#b.-fit-the-tweedie-glm-model-using-the-optimal-power-value-you-computed-from-the-previous-question.-the-file-insurance_test.csv-contains-a-few-additional-observations-which-were-not-a-portion-of-the-data-used-to-fit-the-previous-models.-we-can-read-it-in-and-format-it-using-syntax-similar-to-when-we-started.-newdatapoints---read.csv.insurance_test.csv-newdatapointsvehbrand---as.factornewdatapointsvehbrand-newdatapointsvehpower---as.factornewdatapointsvehpower-newdatapointsvehgas---as.factornewdatapointsvehgas-newdatapointsregion---as.factornewdatapointsregion-newdatapointsarea---as.factornewdatapointsarea"><i class="fa fa-check"></i><b>11.2</b> b. Fit the Tweedie GLM model using the optimal power value you computed from the previous question. The file Insurance_test.csv contains a few additional observations which were not a portion of the data used to fit the previous models. We can read it in and format it using syntax similar to when we started. NewDataPoints &lt;- read.csv(“…./Insurance_test.csv”) NewDataPoints$VehBrand &lt;- as.factor(NewDataPoints$VehBrand) NewDataPoints$VehPower &lt;- as.factor(NewDataPoints$VehPower) NewDataPoints$VehGas &lt;- as.factor(NewDataPoints$VehGas) NewDataPoints$Region &lt;- as.factor(NewDataPoints$Region) NewDataPoints$Area &lt;- as.factor(NewDataPoints$Area)<span></span></a></li>
<li class="chapter" data-level="11.3" data-path="tweedie.html"><a href="tweedie.html#c.7-points-use-your-poisson-model-from-1b-from-and-your-final-gamma-model-from-2d-to-generate-respective-predictions-for-the-number-of-claims-in-a-year-as-well-as-the-average-amount-per-claim.-multiply-these-together-and-call-this-product-purepremium_prod.-similarly-use-your-tweedie-model-from-3b-to-directly-predict-the-purepremium-value-and-store-this-in-purepremium_tw."><i class="fa fa-check"></i><b>11.3</b> c.(7 points) Use your Poisson model from 1b from and your final Gamma model from 2d to generate respective predictions for the number of claims in a year as well as the average amount per claim. Multiply these together and call this product purepremium_prod. Similarly, use your Tweedie model from 3b to directly predict the PurePremium value and store this in purepremium_TW.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><i class="fa fa-check"></i><b>12</b> STAT 4520/7520 - Homework 3 Spring 2022 Due: March 30, 2022<span></span></a>
<ul>
<li class="chapter" data-level="12.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#the-cake-dataset-in-the-lme4-package-contains-data-on-an-experiment-was-conducted-to-determine-the-effect-of-recipe-and-baking-temperature-on-chocolate-cake-quality.-fifteen-batches-of-cake-mix-for-each-recipe-were-prepared.-each-batch-was-sufficient-for-six-cakes.-each-of-the-six-cakes-was-baked-at-a-different-temperature-which-was-randomly-assigned.-as-an-indicator-of-quality-the-breakage-angle-of-the-cake-was-recorded."><i class="fa fa-check"></i><b>12.1</b> 1) The cake dataset in the lme4 package contains data on an experiment was conducted to determine the effect of recipe and baking temperature on chocolate cake quality. Fifteen batches of cake mix for each recipe were prepared. Each batch was sufficient for six cakes. Each of the six cakes was baked at a different temperature which was randomly assigned. As an indicator of quality, the breakage angle of the cake was recorded.<span></span></a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#a.-of-the-explanatory-variables-recipe-temp-and-replicate-which-are-fixed-and-which-are-random-explain.-is-there-any-nesting-in-these-variables"><i class="fa fa-check"></i><b>12.1.1</b> a. Of the explanatory variables recipe, temp, and replicate, which are fixed and which are random? Explain. Is there any nesting in these variables?<span></span></a></li>
<li class="chapter" data-level="12.1.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#b.-fit-a-linear-model-with-no-random-effects-for-breaking-angle-against-the-interaction-between-recipe-and-temperature.-which-variables-are-significant-what-is-the-t-value-for-temp-the-temperature-variable-what-is-the-rmse-of-this-model"><i class="fa fa-check"></i><b>12.1.2</b> b. Fit a linear model with no random effects for breaking angle against the interaction between recipe and temperature. Which variables are significant? What is the t value for temp the temperature variable? What is the RMSE of this model?<span></span></a></li>
<li class="chapter" data-level="12.1.3" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#c.-fit-a-mixed-model-to-the-data-which-takes-into-account-the-replicates-of-the-recipes.-examine-the-variance-components.-is-there-variation-in-the-batches-made-with-each-recipe-how-does-the-residual-variance-component-compare-to-the-mse-from-b-what-is-the-t-value-for-temperature"><i class="fa fa-check"></i><b>12.1.3</b> c. Fit a mixed model to the data which takes into account the replicates of the recipes. Examine the variance components. Is there variation in the batches made with each recipe? How does the Residual variance component compare to the MSE from (b)? What is the t-value for temperature?<span></span></a></li>
<li class="chapter" data-level="12.1.4" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#d.-test-for-a-recipe-and-temperature-effect."><i class="fa fa-check"></i><b>12.1.4</b> d. Test for a recipe and temperature effect.<span></span></a></li>
<li class="chapter" data-level="12.1.5" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#e.-create-a-qq-plot-of-the-residuals-and-a-residual-vs-predicted-plot-for-the-linear-model-in-b-and-the-mixed-model-in-d-describe-how-well-the-model-assumptions-are-satisfied-for-each."><i class="fa fa-check"></i><b>12.1.5</b> e. Create a QQ plot of the residuals and a residual vs predicted plot for the linear model in (b) and the mixed model in (d), describe how well the model assumptions are satisfied for each.<span></span></a></li>
<li class="chapter" data-level="12.1.6" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#f.-7510-only-examine-the-blups-from-the-mixed-model-in-d.-do-you-notice-any-patterns"><i class="fa fa-check"></i><b>12.1.6</b> f. (7510 only) Examine the BLUPs from the mixed model in (d). Do you notice any patterns?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#the-purpose-of-random-effects-is-to-remove-variation-from-known-sources.-in-this-problem-we-will-use-this-idea-and-see-how-it-can-work-with-a-popular-technique-for-predictive-modeling-the-random-forest.-random-forests-were-covered-in-the-prerequisite-course-and-can-be-fit-using-the-randomforest-function-in-the-randomforest-library.-the-dataset-problem-2.csv-has-a-simulated-dataset.-there-is-a-nonlinear-relationship-between-6-numeric-explanatory-variables-x1-.-.-.-x6-and-the-response-y-to-addition-to-a-grouping-effect-according-to-the-id-variable-which-has-100-levels."><i class="fa fa-check"></i><b>12.2</b> 2) The purpose of random effects is to remove variation from known sources. In this problem, we will use this idea and see how it can work with a popular technique for predictive modeling, the random forest. Random forests were covered in the prerequisite course, and can be fit using the randomForest function in the randomForest library. The dataset Problem-2.csv has a simulated dataset. There is a nonlinear relationship between 6 numeric explanatory variables x1, . . . x6 and the response y, to addition to a grouping effect according to the ID variable, which has 100 levels.<span></span></a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#a.-read-in-the-dataset-and-split-the-data-into-a-training-and-test-set-using-95-of-the-data-for-the-training-set.-set-a-seed-of-1-for-consistency-of-results."><i class="fa fa-check"></i><b>12.2.1</b> a. Read in the dataset, and split the data into a training and test set, using 95% of the data for the training set. Set a seed of 1 for consistency of results.<span></span></a></li>
<li class="chapter" data-level="12.2.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#b.-fit-a-random-forest-model-to-the-training-data-using-y-as-the-response-with-x1-.-.-.-x6-and-id-as-the-explanatory-variables.-use-the-model-to-predict-y-in-the-test-set-and-compute-the-test-root-mean-squared-error-rmse-."><i class="fa fa-check"></i><b>12.2.2</b> b. Fit a random forest model to the training data using y as the response with x1, . . . x6 and ID as the explanatory variables. Use the model to predict y in the test set and compute the test root mean squared error ( RMSE ).<span></span></a></li>
<li class="chapter" data-level="12.2.3" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#c.-fit-the-mixed-model-yij-µ-idi-εij-to-the-training-data.-this-model-does-not-use-the-x_i-at-all-and-has-a-random-intercept-based-on-id.-after-fitting-the-model-extract-the-blups-for-id-and-add-them-to-the-constant-µˆ-the-estimate-of-the-overall-intercept.-what-do-these-values-represent-store-them-in-a-data-frame-along-with-a-column-storing-the-ids."><i class="fa fa-check"></i><b>12.2.3</b> c. Fit the mixed model yij = µ + IDi + εij to the training data. This model does not use the x_i at all, and has a random intercept based on ID. After fitting the model, extract the BLUPs for ID and add them to the constant µˆ, the estimate of the overall intercept. What do these values represent? Store them in a data frame along with a column storing the IDs.<span></span></a></li>
<li class="chapter" data-level="12.2.4" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#d.-add-a-column-to-the-test-dataset-containing-the-values-obtained-in-part-c-joined-to-the-test-dataset-by-matching-the-ids.-note-with-the-dplyr-package-loaded-you-can-quickly-join-by-id-using-a-line-like-data.test---left_joindata.test-int_plus_blups-by-id-examine-the-first-few-rows-and-describe-what-the-new-column-represents."><i class="fa fa-check"></i><b>12.2.4</b> d. Add a column to the test dataset containing the values obtained in part c, joined to the test dataset by matching the IDs. Note: with the dplyr package loaded, you can quickly join by ID using a line like: Data.Test &lt;- left_join(Data.Test, int_plus_blups, by = “ID”) Examine the first few rows and describe what the new column represents.<span></span></a></li>
<li class="chapter" data-level="12.2.5" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#e.-compute-the-residuals-of-the-mixed-model-fit-in-c-using-the-residuals-function-store-them-in-a-column-of-the-training-data."><i class="fa fa-check"></i><b>12.2.5</b> e. Compute the residuals of the mixed model fit in (c) using the residuals() function, store them in a column of the training data.<span></span></a></li>
<li class="chapter" data-level="12.2.6" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#f.-fit-another-random-forest-model-to-the-training-data-using-the-residuals-from-part-e-as-the-response-and-only-x1-.-.-.-x6-as-the-explanatory-variables.-use-this-model-to-predict-into-the-test-data-and-store-these-predictions.-what-do-these-predictions-represent"><i class="fa fa-check"></i><b>12.2.6</b> f. Fit another random forest model to the training data, using the residuals from part (e) as the response and only x1, . . . x6 as the explanatory variables. Use this model to predict into the test data and store these predictions. What do these predictions represent?<span></span></a></li>
<li class="chapter" data-level="12.2.7" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#g.-add-the-predictions-in-f-to-the-values-joined-to-the-test-data-in-d.-consider-these-values-test-predictions-and-compute-the-test-mse.-compare-this-to-the-test-mse-compared-in-part-b.-what-do-you-observe"><i class="fa fa-check"></i><b>12.2.7</b> g. Add the predictions in (f) to the values joined to the test data in (d). Consider these values test predictions, and compute the test MSE. Compare this to the test MSE compared in part (b). What do you observe?<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html"><i class="fa fa-check"></i><b>13</b> Applied Stats Model II Lecture Note<span></span></a>
<ul>
<li class="chapter" data-level="13.1" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#list-of-questions"><i class="fa fa-check"></i><b>13.1</b> List of Questions:<span></span></a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#hw1"><i class="fa fa-check"></i><b>13.1.1</b> HW1<span></span></a></li>
<li class="chapter" data-level="13.1.2" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#hw2"><i class="fa fa-check"></i><b>13.1.2</b> HW2<span></span></a></li>
<li class="chapter" data-level="13.1.3" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#midterm"><i class="fa fa-check"></i><b>13.1.3</b> Midterm<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#class-content-overview"><i class="fa fa-check"></i><b>13.2</b> Class content overview:<span></span></a></li>
<li class="chapter" data-level="13.3" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glm-categoricaldata_sp2022"><i class="fa fa-check"></i><b>13.3</b> GLM-CategoricalData_SP2022<span></span></a></li>
<li class="chapter" data-level="13.4" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glm-countdata_sp2022"><i class="fa fa-check"></i><b>13.4</b> GLM-CountData_SP2022<span></span></a></li>
<li class="chapter" data-level="13.5" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glms_advancedtopics_sp2022"><i class="fa fa-check"></i><b>13.5</b> GLMs_AdvancedTopics_SP2022<span></span></a></li>
<li class="chapter" data-level="13.6" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#mm-randomeffects_spring2022"><i class="fa fa-check"></i><b>13.6</b> MM-RandomEffects_Spring2022<span></span></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ASM_II_Class_Note</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="question-1" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Question 1:<a href="question-1.html#question-1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><span class="math inline">\(1\)</span> Logistic Regression: Major League Baseball (MLB) maintains a public facing version of it’s “Statcast” system. Since 2015, MLB teams have been leveraging data analytics to gain a competitive advantage using the raw data out of Statcast, which captures extremely high resolution views of player performance. Here we will study a dataset I have pulled and curated. We will examine which of several characteristics are predictive of a hit yielding a “home run.” The selected variables are as follows: • pitch_speed: Speed of pitch in mph. • pitch_spin: Spin rate of pitch • pitch_horizontal_movement: Horizontal movement of the pitch in feet from the catcher’s perspective. • pitch_vertical_movement: Vertical movement of the pitch in feet from the catcher’s perpsective. • plate_x: Horizontal position of the ball when it crosses home plate from the catcher’s perspective. • plate_z: Vertical position of the ball when it crosses home plate from the catcher’s perspective. • pitcher_hand: Pitcher’s throwing hand. • launch_angle: Launch angle of the batted ball. • launch_speed: Exit velocity of the batted ball (so, how fast it is going once hit by the batter) • stand: Side of the plate batter is standing from the pitcher’s perspective. • home_run: 1/0, the target variable The dataset can be loaded with the command HomeRun &lt;- read.csv(“…/HomeRunData.csv,” stringsAsFactors = TRUE)</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="question-1.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? Cannot knit the single document?</span></span></code></pre></div>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="question-1.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Input the dataset</span></span>
<span id="cb70-2"><a href="question-1.html#cb70-2" aria-hidden="true" tabindex="-1"></a>HomeRun <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;E:/Cloud/OneDrive - University of Missouri/Mizzou_PhD/Class plan/Applied Stats Model II/HW1/HomeRunData.csv&quot;</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="a.-8-points-create-plots-to-examine-how-launch-speed-and-angle-may-affect-the-probability-of-a-home-run-and-describe-your-findings." class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> a. (8 points) Create plots to examine how launch speed and angle may affect the probability of a home run and describe your findings.<a href="question-1.html#a.-8-points-create-plots-to-examine-how-launch-speed-and-angle-may-affect-the-probability-of-a-home-run-and-describe-your-findings." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>On the first plot between launch speed and the probability of a home run, as the launch speed increase to 80 and above, the home run chance increases.</p>
<p>On the second plot between launch angle and the probability of a home run, as the launch angle increase to be above 10, the chance of home run increases. However, when it surpass 50 the chance of home run decreases.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="question-1.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># S39. class is the DV, thickness is the IV. ??? why it doesn&#39;t need binning but deviances needs it? Why is my output different from the ppt?</span></span>
<span id="cb71-2"><a href="question-1.html#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="question-1.html#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(home_run <span class="sc">~</span> launch_speed,HomeRun)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="question-1.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># as the lauch speed increase to 80, the home run chance increase.</span></span>
<span id="cb72-2"><a href="question-1.html#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="question-1.html#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(home_run <span class="sc">~</span> launch_angle,HomeRun)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-30-2.png" width="672" /></p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="question-1.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># seems to have an u-shape effect. less than 0 and more than 50 are both bad. </span></span></code></pre></div>
</div>
<div id="b.-9-points-fit-a-logistic-regression-model-with-home_run-as-the-response-and-all-other-variables-as-predictors.-conduct-a-deviance-test-to-assess-if-this-model-is-better-than-the-null-model." class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> b. (9 points) Fit a logistic regression model with home_run as the response and all other variables as predictors. Conduct a deviance test to assess if this model is better than the null model.<a href="question-1.html#b.-9-points-fit-a-logistic-regression-model-with-home_run-as-the-response-and-all-other-variables-as-predictors.-conduct-a-deviance-test-to-assess-if-this-model-is-better-than-the-null-model." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I ran the logistic regression to predict home run using all other variables.</p>
<p>The results show the pitch_speed, launch angle and launch speed are statistically significant predictors at 95% confidence level.</p>
<p>I then conducted the deviance test. The result is significant. Thus, the model is better than the null model.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="question-1.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model with all variables. Note &lt;- not =  </span></span>
<span id="cb74-2"><a href="question-1.html#cb74-2" aria-hidden="true" tabindex="-1"></a>Logistic_Model <span class="ot">&lt;-</span> <span class="fu">glm</span>(home_run <span class="sc">~</span> ., <span class="at">family =</span> binomial, <span class="at">data =</span> HomeRun)</span>
<span id="cb74-3"><a href="question-1.html#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred. ??? What does the warning mean? still can run. move on for now. </span></span>
<span id="cb74-4"><a href="question-1.html#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="co"># https://www.statology.org/glm-fit-fitted-probabilities-numerically-0-or-1-occurred/</span></span></code></pre></div>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="question-1.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Logistic_Model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = home_run ~ ., family = binomial, data = HomeRun)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.7030  -0.1785  -0.0455  -0.0036   4.2501  
## 
## Coefficients:
##                             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)               -3.288e+01  1.073e+00 -30.632  &lt; 2e-16 ***
## pitch_speed               -5.416e-02  8.723e-03  -6.209 5.32e-10 ***
## pitch_spin                 6.729e-05  1.221e-04   0.551    0.581    
## pitch_horizontal_movement -2.779e-02  5.151e-02  -0.539    0.590    
## pitch_vertical_movement   -5.401e-02  7.207e-02  -0.749    0.454    
## plate_x                   -4.299e-02  8.223e-02  -0.523    0.601    
## plate_z                    1.040e-01  7.133e-02   1.458    0.145    
## pitcher_handR             -6.163e-02  9.391e-02  -0.656    0.512    
## launch_angle               9.850e-02  2.962e-03  33.253  &lt; 2e-16 ***
## launch_speed               3.250e-01  7.796e-03  41.691  &lt; 2e-16 ***
## standR                    -8.384e-02  7.141e-02  -1.174    0.240    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 10624.6  on 29595  degrees of freedom
## Residual deviance:  6109.7  on 29585  degrees of freedom
## AIC: 6131.7
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="question-1.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(Logistic_Model)$coefficients</span></span>
<span id="cb77-2"><a href="question-1.html#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="co"># S22: change the df per the summary stats above. </span></span>
<span id="cb77-3"><a href="question-1.html#cb77-3" aria-hidden="true" tabindex="-1"></a>Test_Dev <span class="ot">=</span> <span class="fu">summary</span>(Logistic_Model)<span class="sc">$</span>null.deviance <span class="sc">-</span> <span class="fu">summary</span>(Logistic_Model)<span class="sc">$</span>deviance</span>
<span id="cb77-4"><a href="question-1.html#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(<span class="at">q =</span> Test_Dev, <span class="at">df =</span> <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="question-1.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? What does the 0 stands for here? significant?</span></span></code></pre></div>
</div>
<div id="c.-8-points-conduct-deviance-tests-with-the-drop1-function-to-assess-the-significance-of-each-individual-variable-and-report-the-results.-compare-the-p-values-to-those-obtained-from-summary." class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> c. (8 points) Conduct deviance tests with the drop1() function to assess the significance of each individual variable and report the results. Compare the p-values to those obtained from summary().<a href="question-1.html#c.-8-points-conduct-deviance-tests-with-the-drop1-function-to-assess-the-significance-of-each-individual-variable-and-report-the-results.-compare-the-p-values-to-those-obtained-from-summary." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I conducted the deviance test using drop1 function. The pitch speed, plate_z, launch_angle, launch_speed and stand are significant at 95% confidence level.</p>
<p>The p-value are different from the summary. Plate_z went from 0.145 to 0.001; Stand went 0.240 from to 0.01. All other variables have similar p values as before.</p>
<p>I would trust the drop1 function’s results as it doesn’t rely on the unreliable walt’s test.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="question-1.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># S30, S67: stepwise selection - backward. large predictors some will randomly be significant. but note, you are not eliminate the one with p at border? once your predictors number is small enough. it is ok? </span></span>
<span id="cb80-2"><a href="question-1.html#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="co">#??? Why no reaction for a long time?</span></span>
<span id="cb80-3"><a href="question-1.html#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="question-1.html#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(Logistic_Model,<span class="at">test=</span><span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## Single term deletions
## 
## Model:
## home_run ~ pitch_speed + pitch_spin + pitch_horizontal_movement + 
##     pitch_vertical_movement + plate_x + plate_z + pitcher_hand + 
##     launch_angle + launch_speed + stand
##                           Df Deviance     AIC    F value    Pr(&gt;F)    
## &lt;none&gt;                         6109.7  6131.7                         
## pitch_speed                1   6147.7  6167.7   183.9705 &lt; 2.2e-16 ***
## pitch_spin                 1   6110.0  6130.0     1.4772  0.224219    
## pitch_horizontal_movement  1   6110.0  6130.0     1.4068  0.235594    
## pitch_vertical_movement    1   6110.3  6130.3     2.7214  0.099019 .  
## plate_x                    1   6110.0  6130.0     1.3233  0.250003    
## plate_z                    1   6111.8  6131.8    10.2774  0.001348 ** 
## pitcher_hand               1   6110.1  6130.1     2.0781  0.149433    
## launch_angle               1   7716.6  7736.6  7781.3469 &lt; 2.2e-16 ***
## launch_speed               1  10133.9 10153.9 19486.6009 &lt; 2.2e-16 ***
## stand                      1   6111.1  6131.1     6.6608  0.009861 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="d.-6-points-fit-a-smaller-model-after-removing-all-variables-which-are-insignificant-using-α-0.05.-compare-this-model-to-the-larger-model-are-they-significantly-different-what-are-the-implications-of-this-with-regard-to-model-selection-until-the-end-of-this-question-use-the-smaller-model-for-all-analysis" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> d. (6 points) Fit a smaller model after removing all variables which are insignificant using α = 0.05. Compare this model to the larger model, are they significantly different? What are the implications of this with regard to model selection? Until the end of this question, use the smaller model for all analysis<a href="question-1.html#d.-6-points-fit-a-smaller-model-after-removing-all-variables-which-are-insignificant-using-α-0.05.-compare-this-model-to-the-larger-model-are-they-significantly-different-what-are-the-implications-of-this-with-regard-to-model-selection-until-the-end-of-this-question-use-the-smaller-model-for-all-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I compare the smaller model with the larger model, they are not significantly different per the deviance test.</p>
<p>The result suggests that larger model doesn’t add much explanation power. I should use the smaller model for parsimonious explanation.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="question-1.html#cb82-1" aria-hidden="true" tabindex="-1"></a>Logistic_Model_better <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> home_run <span class="sc">~</span> pitch_speed<span class="sc">+</span> plate_z <span class="sc">+</span> launch_angle <span class="sc">+</span> launch_speed <span class="sc">+</span> stand, <span class="at">family =</span> binomial, <span class="at">data =</span> HomeRun)</span></code></pre></div>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="question-1.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Logistic_Model_better)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = home_run ~ pitch_speed + plate_z + launch_angle + 
##     launch_speed + stand, family = binomial, data = HomeRun)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.7028  -0.1792  -0.0455  -0.0036   4.2511  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -32.484157   0.935687 -34.717   &lt;2e-16 ***
## pitch_speed   -0.057392   0.006136  -9.354   &lt;2e-16 ***
## plate_z        0.096252   0.070659   1.362    0.173    
## launch_angle   0.098273   0.002941  33.420   &lt;2e-16 ***
## launch_speed   0.324831   0.007788  41.711   &lt;2e-16 ***
## standR        -0.088306   0.069221  -1.276    0.202    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 10624.6  on 29595  degrees of freedom
## Residual deviance:  6111.3  on 29590  degrees of freedom
## AIC: 6123.3
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="question-1.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? Is sthe plate_Z and standR just noise? random significant on the backward selection drop1 process?</span></span></code></pre></div>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="question-1.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note the df difference 11 (baseline all variable) - 5 (better model) = 6</span></span>
<span id="cb86-2"><a href="question-1.html#cb86-2" aria-hidden="true" tabindex="-1"></a>Test_Dev_better <span class="ot">=</span> <span class="fu">summary</span>(Logistic_Model_better)<span class="sc">$</span>deviance <span class="sc">-</span> <span class="fu">summary</span>(Logistic_Model)<span class="sc">$</span>deviance</span>
<span id="cb86-3"><a href="question-1.html#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(<span class="at">q =</span> Test_Dev_better, <span class="at">df =</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.9502016</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="question-1.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The result shows insignificant difference between the two. Thus, better model is parsimony.</span></span></code></pre></div>
</div>
<div id="e.-7-points-how-does-the-launch-speed-after-the-ball-is-hit-affect-the-odds-of-homerun-occurring-provide-a-confidence-interval-for-this-value." class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> e. (7 points) How does the launch speed after the ball is hit affect the <strong>odds of HomeRun occurring</strong>? Provide a confidence interval for this value.<a href="question-1.html#e.-7-points-how-does-the-launch-speed-after-the-ball-is-hit-affect-the-odds-of-homerun-occurring-provide-a-confidence-interval-for-this-value." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The odds is 1.38. As the launch speed increase by 1, the chance of success will increase by 100% * (1.38-1) = 38%</p>
<p>The confidence interval for the odds is between 1.36 to 1.40.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="question-1.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># S57/ </span></span>
<span id="cb89-2"><a href="question-1.html#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="question-1.html#cb89-3" aria-hidden="true" tabindex="-1"></a>Coef_LogOdds <span class="ot">&lt;-</span> <span class="fu">coefficients</span>(Logistic_Model_better)</span>
<span id="cb89-4"><a href="question-1.html#cb89-4" aria-hidden="true" tabindex="-1"></a>Coef_LogOdds <span class="sc">|&gt;</span> <span class="fu">exp</span>()</span></code></pre></div>
<pre><code>##  (Intercept)  pitch_speed      plate_z launch_angle launch_speed       standR 
## 7.803867e-15 9.442236e-01 1.101037e+00 1.103264e+00 1.383797e+00 9.154811e-01</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="question-1.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co">#1.383797e+00  ??? interpret e+00 menas integer? 1.38 more success than failure to hit home rum </span></span>
<span id="cb91-2"><a href="question-1.html#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="co">#S17: When launch speed increases by 1, the odds of success increases by a factor of 1.38 pr 100% * (1.38-1) = 38% increase in chance/ odds??? of sucess. </span></span>
<span id="cb91-3"><a href="question-1.html#cb91-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-4"><a href="question-1.html#cb91-4" aria-hidden="true" tabindex="-1"></a><span class="co">#What if I want the chance vs. odds???</span></span>
<span id="cb91-5"><a href="question-1.html#cb91-5" aria-hidden="true" tabindex="-1"></a><span class="co"># why the number different? 1.38/(1+1.38) = .57 </span></span></code></pre></div>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="question-1.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># type of confidenec interval</span></span>
<span id="cb92-2"><a href="question-1.html#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="co">#??? What if I use directly the CI from the model? violate assumption in binomial family?</span></span>
<span id="cb92-3"><a href="question-1.html#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="co"># A lot of warning message: Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred ???</span></span>
<span id="cb92-4"><a href="question-1.html#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co">#S44: </span></span>
<span id="cb92-5"><a href="question-1.html#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Confidence_Intervals &lt;- confint(Logistic_Model_better)</span></span>
<span id="cb92-6"><a href="question-1.html#cb92-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Confidence_Intervals</span></span>
<span id="cb92-7"><a href="question-1.html#cb92-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-8"><a href="question-1.html#cb92-8" aria-hidden="true" tabindex="-1"></a>Confidence_Intervals <span class="ot">&lt;-</span> <span class="fu">confint</span>(Logistic_Model_better)</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="question-1.html#cb94-1" aria-hidden="true" tabindex="-1"></a>Confidence_Intervals <span class="sc">|&gt;</span> <span class="fu">exp</span>()</span></code></pre></div>
<pre><code>##                     2.5 %       97.5 %
## (Intercept)  1.218007e-15 4.773109e-14
## pitch_speed  9.329500e-01 9.556669e-01
## plate_z      9.584535e-01 1.264379e+00
## launch_angle 1.096995e+00 1.109715e+00
## launch_speed 1.363138e+00 1.405399e+00
## standR       7.995274e-01 1.048816e+00</code></pre>
</div>
<div id="f.-5-points-using-the-deviance-residuals-make-a-binned-residual-vs-fitted-probability-plot-and-comment-on-the-fit-of-the-model." class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> f. (5 points) Using the deviance residuals, make a binned residual vs fitted probability plot and comment on the fit of the model.<a href="question-1.html#f.-5-points-using-the-deviance-residuals-make-a-binned-residual-vs-fitted-probability-plot-and-comment-on-the-fit-of-the-model." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The model doesn’t fit well. The residual gets bigger rather than smaller when the probability increases. Based on the theoretical distribution, as the probability increases, the variance should be smaller. Thus, there may be misspecification in the model.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="question-1.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bin plot vs. fitted plt </span></span>
<span id="cb96-2"><a href="question-1.html#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co"># random subset is not required.</span></span>
<span id="cb96-3"><a href="question-1.html#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb96-4"><a href="question-1.html#cb96-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-5"><a href="question-1.html#cb96-5" aria-hidden="true" tabindex="-1"></a>plot_bin <span class="ot">&lt;-</span> <span class="cf">function</span>(Y, X, <span class="at">bins =</span> <span class="dv">100</span>, <span class="at">return.DF =</span> <span class="cn">FALSE</span>){</span>
<span id="cb96-6"><a href="question-1.html#cb96-6" aria-hidden="true" tabindex="-1"></a>Y_Name <span class="ot">&lt;-</span> <span class="fu">deparse</span>(<span class="fu">substitute</span>(Y))</span>
<span id="cb96-7"><a href="question-1.html#cb96-7" aria-hidden="true" tabindex="-1"></a>X_Name <span class="ot">&lt;-</span> <span class="fu">deparse</span>(<span class="fu">substitute</span>(X))</span>
<span id="cb96-8"><a href="question-1.html#cb96-8" aria-hidden="true" tabindex="-1"></a>Binned_Plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Plot_Y =</span> Y, <span class="at">Plot_X =</span> X)</span>
<span id="cb96-9"><a href="question-1.html#cb96-9" aria-hidden="true" tabindex="-1"></a>Binned_Plot<span class="sc">$</span>bin <span class="ot">&lt;-</span> <span class="fu">cut</span>(Binned_Plot<span class="sc">$</span>Plot_X,<span class="at">breaks =</span> bins) <span class="sc">|&gt;</span></span>
<span id="cb96-10"><a href="question-1.html#cb96-10" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>()</span>
<span id="cb96-11"><a href="question-1.html#cb96-11" aria-hidden="true" tabindex="-1"></a>Binned_Plot_summary <span class="ot">&lt;-</span> Binned_Plot <span class="sc">|&gt;</span></span>
<span id="cb96-12"><a href="question-1.html#cb96-12" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(bin) <span class="sc">|&gt;</span></span>
<span id="cb96-13"><a href="question-1.html#cb96-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="at">Y_ave =</span> <span class="fu">mean</span>(Plot_Y),</span>
<span id="cb96-14"><a href="question-1.html#cb96-14" aria-hidden="true" tabindex="-1"></a><span class="at">X_ave =</span> <span class="fu">mean</span>(Plot_X),</span>
<span id="cb96-15"><a href="question-1.html#cb96-15" aria-hidden="true" tabindex="-1"></a><span class="at">Count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb96-16"><a href="question-1.html#cb96-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> Binned_Plot_summary<span class="sc">$</span>Y_ave,</span>
<span id="cb96-17"><a href="question-1.html#cb96-17" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> Binned_Plot_summary<span class="sc">$</span>X_ave,</span>
<span id="cb96-18"><a href="question-1.html#cb96-18" aria-hidden="true" tabindex="-1"></a><span class="at">ylab =</span> Y_Name,<span class="at">xlab =</span> X_Name)</span>
<span id="cb96-19"><a href="question-1.html#cb96-19" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(return.DF) <span class="fu">return</span>(Binned_Plot_summary)</span>
<span id="cb96-20"><a href="question-1.html#cb96-20" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="question-1.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co">#S32: vs. fitted probability plot rather than individual variable. ??? When to use the individual variable on?</span></span>
<span id="cb97-2"><a href="question-1.html#cb97-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-3"><a href="question-1.html#cb97-3" aria-hidden="true" tabindex="-1"></a>Logistic_better_Resids <span class="ot">&lt;-</span> <span class="fu">residuals</span>(Logistic_Model_better,<span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb97-4"><a href="question-1.html#cb97-4" aria-hidden="true" tabindex="-1"></a>Logistic_better_Predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(Logistic_Model_better,<span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb97-5"><a href="question-1.html#cb97-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-6"><a href="question-1.html#cb97-6" aria-hidden="true" tabindex="-1"></a>NumBins <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb97-7"><a href="question-1.html#cb97-7" aria-hidden="true" tabindex="-1"></a>Binned_Data <span class="ot">&lt;-</span> <span class="fu">plot_bin</span>(<span class="at">Y =</span> Logistic_better_Resids,</span>
<span id="cb97-8"><a href="question-1.html#cb97-8" aria-hidden="true" tabindex="-1"></a><span class="at">X =</span> Logistic_better_Predictions,</span>
<span id="cb97-9"><a href="question-1.html#cb97-9" aria-hidden="true" tabindex="-1"></a><span class="at">bins =</span> NumBins,</span>
<span id="cb97-10"><a href="question-1.html#cb97-10" aria-hidden="true" tabindex="-1"></a><span class="at">return.DF =</span> <span class="cn">TRUE</span>)</span>
<span id="cb97-11"><a href="question-1.html#cb97-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="question-1.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The model doesn&#39;t fit well??? why? </span></span>
<span id="cb98-2"><a href="question-1.html#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="co">#S28 ??? why deviance not the same. why no u shape. np vs. npq.</span></span></code></pre></div>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="question-1.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co">#need more bins, the shape will follow theroy on S18 Chapter 2.</span></span></code></pre></div>
</div>
<div id="g.-4-points-using-a-probability-of-0.5-as-the-threshold-for-predicting-an-observation-yielding-a-home-run-create-a-table-classifying-the-predictions-against-the-observed-values.-describe-your-findings.-what-is-the-misclassification-rate" class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> g. (4 points) Using a probability of 0.5 as the threshold for predicting an observation yielding a home run, create a table classifying the predictions against the observed values. Describe your findings. What is the misclassification rate?<a href="question-1.html#g.-4-points-using-a-probability-of-0.5-as-the-threshold-for-predicting-an-observation-yielding-a-home-run-create-a-table-classifying-the-predictions-against-the-observed-values.-describe-your-findings.-what-is-the-misclassification-rate" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The model predicts well as the accuracy rate is high.</p>
<p>The misclassification rate is 0.043 or 4%. However, the sensitivity and specificity are poor.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="question-1.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix </span></span>
<span id="cb100-2"><a href="question-1.html#cb100-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-3"><a href="question-1.html#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="co"># S47:</span></span>
<span id="cb100-4"><a href="question-1.html#cb100-4" aria-hidden="true" tabindex="-1"></a>Predicted_Prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(Logistic_Model_better, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb100-5"><a href="question-1.html#cb100-5" aria-hidden="true" tabindex="-1"></a>Predicted_Class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(Predicted_Prob <span class="sc">&gt;</span> <span class="fl">0.5</span>,<span class="at">yes =</span> <span class="st">&quot;home_run&quot;</span>,<span class="at">no =</span> <span class="st">&quot;no_home_run&quot;</span>)</span>
<span id="cb100-6"><a href="question-1.html#cb100-6" aria-hidden="true" tabindex="-1"></a>Observed_Class <span class="ot">&lt;-</span> HomeRun<span class="sc">$</span>home_run</span>
<span id="cb100-7"><a href="question-1.html#cb100-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Observed_Class,Predicted_Class)</span></code></pre></div>
<pre><code>##               Predicted_Class
## Observed_Class home_run no_home_run
##              0      190       28113
##              1      274        1019</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="question-1.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Misclassification rate:</span></span>
<span id="cb102-2"><a href="question-1.html#cb102-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-3"><a href="question-1.html#cb102-3" aria-hidden="true" tabindex="-1"></a>table_classify <span class="ot">=</span> <span class="fu">table</span>(Observed_Class,Predicted_Class)</span>
<span id="cb102-4"><a href="question-1.html#cb102-4" aria-hidden="true" tabindex="-1"></a>Accuracy_rate <span class="ot">=</span> (table_classify[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">+</span>table_classify[<span class="dv">1</span>,<span class="dv">2</span>])<span class="sc">/</span>(table_classify[<span class="dv">1</span>,<span class="dv">1</span>]<span class="sc">+</span>table_classify[<span class="dv">1</span>,<span class="dv">2</span>]<span class="sc">+</span>table_classify[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">+</span>table_classify[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb102-5"><a href="question-1.html#cb102-5" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>Accuracy_rate</span></code></pre></div>
<pre><code>## [1] 0.04085011</code></pre>
</div>
<div id="h.-6-points-using-probability-thresholds-from-0.005-to-0.995-obtain-the-sensitivities-and-specificity-of-the-resulting-predictions.-create-an-roc-plot-and-comment-on-the-effectiveness-of-the-models-ability-to-correctly-classify-the-response.-as-we-vary-the-threshold-to-determine-classifications-is-inverse-relationship-between-sensitivity-and-specificity-strongly-evident" class="section level2 hasAnchor" number="7.8">
<h2><span class="header-section-number">7.8</span> h. (6 points) Using probability thresholds from 0.005 to 0.995, obtain the sensitivities and specificity of the resulting predictions. Create an ROC plot and comment on the effectiveness of the model’s ability to correctly classify the response. As we vary the threshold to determine classifications, is inverse relationship between sensitivity and specificity strongly evident?<a href="question-1.html#h.-6-points-using-probability-thresholds-from-0.005-to-0.995-obtain-the-sensitivities-and-specificity-of-the-resulting-predictions.-create-an-roc-plot-and-comment-on-the-effectiveness-of-the-models-ability-to-correctly-classify-the-response.-as-we-vary-the-threshold-to-determine-classifications-is-inverse-relationship-between-sensitivity-and-specificity-strongly-evident" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The inverse relationship is strongly evident as the threshold increases.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="question-1.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create ROC curve</span></span>
<span id="cb104-2"><a href="question-1.html#cb104-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-3"><a href="question-1.html#cb104-3" aria-hidden="true" tabindex="-1"></a><span class="co">#S48: </span></span>
<span id="cb104-4"><a href="question-1.html#cb104-4" aria-hidden="true" tabindex="-1"></a>thresh <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.005</span>,<span class="fl">0.995</span>,<span class="fl">0.001</span>)</span>
<span id="cb104-5"><a href="question-1.html#cb104-5" aria-hidden="true" tabindex="-1"></a>Sensitivity <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(thresh))</span>
<span id="cb104-6"><a href="question-1.html#cb104-6" aria-hidden="true" tabindex="-1"></a>Specificity <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(thresh))</span>
<span id="cb104-7"><a href="question-1.html#cb104-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="fu">seq</span>(<span class="at">along=</span>thresh)){</span>
<span id="cb104-8"><a href="question-1.html#cb104-8" aria-hidden="true" tabindex="-1"></a>Predicted_Class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(Predicted_Prob <span class="sc">&gt;</span> thresh[j],</span>
<span id="cb104-9"><a href="question-1.html#cb104-9" aria-hidden="true" tabindex="-1"></a><span class="at">yes =</span> <span class="st">&quot;1_home_run&quot;</span>,<span class="at">no =</span> <span class="st">&quot;0_no_home_run&quot;</span>)</span>
<span id="cb104-10"><a href="question-1.html#cb104-10" aria-hidden="true" tabindex="-1"></a>Conf_Matrix <span class="ot">&lt;-</span> <span class="fu">table</span>(Observed_Class,Predicted_Class)</span>
<span id="cb104-11"><a href="question-1.html#cb104-11" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb104-12"><a href="question-1.html#cb104-12" aria-hidden="true" tabindex="-1"></a>Specificity[j] <span class="ot">&lt;-</span> Conf_Matrix[<span class="dv">1</span>,<span class="dv">1</span>]<span class="sc">/</span>(Conf_Matrix[<span class="dv">1</span>,<span class="dv">1</span>]<span class="sc">+</span>Conf_Matrix[<span class="dv">1</span>,<span class="dv">2</span>])</span>
<span id="cb104-13"><a href="question-1.html#cb104-13" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb104-14"><a href="question-1.html#cb104-14" aria-hidden="true" tabindex="-1"></a>Sensitivity[j] <span class="ot">&lt;-</span> Conf_Matrix[<span class="dv">2</span>,<span class="dv">2</span>]<span class="sc">/</span>(Conf_Matrix[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">+</span>Conf_Matrix[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb104-15"><a href="question-1.html#cb104-15" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="question-1.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">-</span>Specificity,Sensitivity,<span class="at">type=</span><span class="st">&quot;l&quot;</span>,<span class="at">main =</span> <span class="st">&quot;ROC curve&quot;</span>,</span>
<span id="cb105-2"><a href="question-1.html#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb105-3"><a href="question-1.html#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
</div>
<div id="i.-5-points-produce-a-plot-of-the-sensitivity-and-specificity-against-the-threshold.-is-there-a-threshold-for-classification-you-would-recommend-that-provides-a-good-balance-between-the-two-make-another-confusion-matrix-using-this-cutoff-how-does-the-result-compare-to-the-previous-one-consider-the-types-of-errors-you-observe." class="section level2 hasAnchor" number="7.9">
<h2><span class="header-section-number">7.9</span> i. (5 points) Produce a plot of the sensitivity and specificity against the threshold. Is there a threshold for classification you would recommend that provides a good balance between the two? Make another confusion matrix using this cutoff, how does the result compare to the previous one? Consider the types of errors you observe.<a href="question-1.html#i.-5-points-produce-a-plot-of-the-sensitivity-and-specificity-against-the-threshold.-is-there-a-threshold-for-classification-you-would-recommend-that-provides-a-good-balance-between-the-two-make-another-confusion-matrix-using-this-cutoff-how-does-the-result-compare-to-the-previous-one-consider-the-types-of-errors-you-observe." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The optimal threshold is 0.05.</p>
<p>The result is better than 0.5 as the cut-off: The accuracy is worse but sensitivity and specificity are higher or more discriminant. The accuracy rate is not a good indicator of model performance when the outcomes is rare such as home run.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="question-1.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co">#! The result is better than 0.5 as the cut-off  The accuracy is worse but senstivity and specificity is higher</span></span>
<span id="cb106-2"><a href="question-1.html#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="co">#S50</span></span>
<span id="cb106-3"><a href="question-1.html#cb106-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-4"><a href="question-1.html#cb106-4" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(thresh,<span class="fu">cbind</span>(Sensitivity,Specificity),<span class="at">type=</span><span class="st">&quot;l&quot;</span>,</span>
<span id="cb106-5"><a href="question-1.html#cb106-5" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">&quot;Threshold&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Proportion&quot;</span>,<span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="question-1.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># abline, v = cutoff. </span></span></code></pre></div>
<p># <strong>Rewrie the answer</strong></p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="question-1.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confusion matrix </span></span>
<span id="cb108-2"><a href="question-1.html#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="co"># when we lower the threshold, more on the home run category. if choose 0.5, for the rare. </span></span>
<span id="cb108-3"><a href="question-1.html#cb108-3" aria-hidden="true" tabindex="-1"></a><span class="co"># S47:</span></span>
<span id="cb108-4"><a href="question-1.html#cb108-4" aria-hidden="true" tabindex="-1"></a>Predicted_Prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(Logistic_Model_better, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span>
<span id="cb108-5"><a href="question-1.html#cb108-5" aria-hidden="true" tabindex="-1"></a>Predicted_Class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(Predicted_Prob <span class="sc">&gt;</span> <span class="fl">0.05</span>,<span class="at">yes =</span> <span class="st">&quot;home_run&quot;</span>,<span class="at">no =</span> <span class="st">&quot;no_home_run&quot;</span>)</span>
<span id="cb108-6"><a href="question-1.html#cb108-6" aria-hidden="true" tabindex="-1"></a>Observed_Class <span class="ot">&lt;-</span> HomeRun<span class="sc">$</span>home_run</span>
<span id="cb108-7"><a href="question-1.html#cb108-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Observed_Class,Predicted_Class)</span></code></pre></div>
<pre><code>##               Predicted_Class
## Observed_Class home_run no_home_run
##              0     4222       24081
##              1     1182         111</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="question-1.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Misclassification rate:</span></span>
<span id="cb110-2"><a href="question-1.html#cb110-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-3"><a href="question-1.html#cb110-3" aria-hidden="true" tabindex="-1"></a>table_classify <span class="ot">=</span> <span class="fu">table</span>(Observed_Class,Predicted_Class)</span>
<span id="cb110-4"><a href="question-1.html#cb110-4" aria-hidden="true" tabindex="-1"></a>Accuracy_rate <span class="ot">=</span> (table_classify[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">+</span>table_classify[<span class="dv">1</span>,<span class="dv">2</span>])<span class="sc">/</span>(table_classify[<span class="dv">1</span>,<span class="dv">1</span>]<span class="sc">+</span>table_classify[<span class="dv">1</span>,<span class="dv">2</span>]<span class="sc">+</span>table_classify[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">+</span>table_classify[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb110-5"><a href="question-1.html#cb110-5" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>Accuracy_rate</span></code></pre></div>
<pre><code>## [1] 0.1464049</code></pre>
</div>
<div id="j.-3-points-consider-a-logistic-model-with-only-launch_angle-and-launch_speed-being-used-to-predict-the-probability-of-a-home-run.-what-is-the-aic-of-this-model" class="section level2 hasAnchor" number="7.10">
<h2><span class="header-section-number">7.10</span> j. (3 points) Consider a logistic model with only launch_angle and launch_speed being used to predict the probability of a home run. What is the AIC of this model?<a href="question-1.html#j.-3-points-consider-a-logistic-model-with-only-launch_angle-and-launch_speed-being-used-to-predict-the-probability-of-a-home-run.-what-is-the-aic-of-this-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The AIC of the model is 6203.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="question-1.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce AIC </span></span>
<span id="cb112-2"><a href="question-1.html#cb112-2" aria-hidden="true" tabindex="-1"></a>Logistic_Model_reduced <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> home_run <span class="sc">~</span>  launch_angle <span class="sc">+</span> launch_speed, <span class="at">family =</span> binomial, <span class="at">data =</span> HomeRun)</span></code></pre></div>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="question-1.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Logistic_Model_reduced)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = home_run ~ launch_angle + launch_speed, family = binomial, 
##     data = HomeRun)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.7202  -0.1812  -0.0479  -0.0038   4.2110  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -36.664943   0.835606  -43.88   &lt;2e-16 ***
## launch_angle   0.097468   0.002849   34.22   &lt;2e-16 ***
## launch_speed   0.317479   0.007616   41.69   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 10624.6  on 29595  degrees of freedom
## Residual deviance:  6197.6  on 29593  degrees of freedom
## AIC: 6203.6
## 
## Number of Fisher Scoring iterations: 9</code></pre>
</div>
<div id="k.-11-points-create-a-dummy-variable-which-is-1-if-launch_angle-is-between-20-and-40-degrees-and-use-this-variable-in-your-model-instead-of-the-raw-value-for-launch_angle.-then-complete-the-following-1.-compare-the-aic-of-this-model-to-the-model-in-part-j-which-model-is-better-2.-what-does-the-coefficient-of-your-dummy-variable-mean-interpret-the-value.-3.-interpret-the-value-of-the-intercept-by-converting-to-a-probability.-does-this-result-make-sense" class="section level2 hasAnchor" number="7.11">
<h2><span class="header-section-number">7.11</span> k. (11 points) Create a dummy variable which is 1 if launch_angle is between 20 and 40 degrees and use this variable in your model instead of the raw value for launch_angle. Then, complete the following: 1. Compare the AIC of this model to the model in part j, which model is better? 2. What does the coefficient of your dummy variable mean? Interpret the value. 3. Interpret the value of the intercept by converting to a probability. Does this result make sense?<a href="question-1.html#k.-11-points-create-a-dummy-variable-which-is-1-if-launch_angle-is-between-20-and-40-degrees-and-use-this-variable-in-your-model-instead-of-the-raw-value-for-launch_angle.-then-complete-the-following-1.-compare-the-aic-of-this-model-to-the-model-in-part-j-which-model-is-better-2.-what-does-the-coefficient-of-your-dummy-variable-mean-interpret-the-value.-3.-interpret-the-value-of-the-intercept-by-converting-to-a-probability.-does-this-result-make-sense" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The model with dummy’s AIC is 4508 which is much smaller than the 6203.</p>
<p>The dummy variable means when the launch_angle is between 20 and 40 degree the odds of success is higher than the launch_angle outside the window. Thus, there is a optimal point of the launch angle.</p>
<p>The intercept is very small or 4.186275e-17 which means the chance of making a home run when all other variables are set to 0 is very small.</p>
<div id="section-1" class="section level3" number="7.11.1">
<h3><span class="header-section-number">7.11.1</span> </h3>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="question-1.html#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare with other temp, here is more likely.</span></span>
<span id="cb115-2"><a href="question-1.html#cb115-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-3"><a href="question-1.html#cb115-3" aria-hidden="true" tabindex="-1"></a>HomeRun<span class="sc">$</span>launch_angle_d <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(HomeRun<span class="sc">$</span>launch_angle <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">&amp;</span> HomeRun<span class="sc">$</span>launch_angle <span class="sc">&lt;=</span> <span class="dv">40</span> ,<span class="dv">1</span>,<span class="dv">0</span>)</span></code></pre></div>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="question-1.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce AIC </span></span>
<span id="cb116-2"><a href="question-1.html#cb116-2" aria-hidden="true" tabindex="-1"></a>Logistic_Model_reduced_d <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">formula =</span> home_run <span class="sc">~</span>  launch_angle_d <span class="sc">+</span> launch_speed, <span class="at">family =</span> binomial, <span class="at">data =</span> HomeRun) </span></code></pre></div>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="question-1.html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Logistic_Model_reduced)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = home_run ~ launch_angle + launch_speed, family = binomial, 
##     data = HomeRun)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.7202  -0.1812  -0.0479  -0.0038   4.2110  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -36.664943   0.835606  -43.88   &lt;2e-16 ***
## launch_angle   0.097468   0.002849   34.22   &lt;2e-16 ***
## launch_speed   0.317479   0.007616   41.69   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 10624.6  on 29595  degrees of freedom
## Residual deviance:  6197.6  on 29593  degrees of freedom
## AIC: 6203.6
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="question-1.html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Logistic_Model_reduced_d)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = home_run ~ launch_angle_d + launch_speed, family = binomial, 
##     data = HomeRun)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.1862  -0.0780  -0.0148  -0.0025   3.9332  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    -37.712135   0.991093  -38.05   &lt;2e-16 ***
## launch_angle_d   5.329550   0.156367   34.08   &lt;2e-16 ***
## launch_speed     0.313245   0.009108   34.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 10624.6  on 29595  degrees of freedom
## Residual deviance:  4502.2  on 29593  degrees of freedom
## AIC: 4508.2
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="question-1.html#cb121-1" aria-hidden="true" tabindex="-1"></a>Coef_LogOdds_d <span class="ot">&lt;-</span> <span class="fu">coefficients</span>(Logistic_Model_reduced_d)</span>
<span id="cb121-2"><a href="question-1.html#cb121-2" aria-hidden="true" tabindex="-1"></a>Coef_LogOdds_d <span class="sc">|&gt;</span> <span class="fu">exp</span>()</span></code></pre></div>
<pre><code>##    (Intercept) launch_angle_d   launch_speed 
##   4.186275e-17   2.063451e+02   1.367857e+00</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="question-1.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert intercept to probability odds/ (1+odds)</span></span>
<span id="cb123-2"><a href="question-1.html#cb123-2" aria-hidden="true" tabindex="-1"></a>(<span class="fl">4.186275e-17</span>)<span class="sc">/</span>(<span class="dv">1</span><span class="fl">-4.186275e-17</span>)</span></code></pre></div>
<pre><code>## [1] 4.186275e-17</code></pre>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="applied-stats-model-ii---exam-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="question-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/lyf718718/Book2.git/edit/master/ASM2_HW1v2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/lyf718718/Book2.git/blob/master/ASM2_HW1v2.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
