<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 STAT 4520/7520 - Homework 4 Spring 2022 Due: April 25, 2022 | Frank’s second book</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 STAT 4520/7520 - Homework 4 Spring 2022 Due: April 25, 2022 | Frank’s second book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 STAT 4520/7520 - Homework 4 Spring 2022 Due: April 25, 2022 | Frank’s second book" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Frank Lin" />


<meta name="date" content="2022-04-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"/>
<link rel="next" href="applied-stats-model-ii-lecture-note.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Frank second book</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html"><i class="fa fa-check"></i><b>1</b> Selling and buying process:<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salespeople-skill-perception"><i class="fa fa-check"></i><b>1.1</b> Salespeople skill/ perception<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#communication---intraorganization"><i class="fa fa-check"></i><b>1.2</b> Communication - intraorganization<span></span></a></li>
<li class="chapter" data-level="1.3" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#communication-interorganization---fle-interactions"><i class="fa fa-check"></i><b>1.3</b> Communication Interorganization - FLE interactions<span></span></a></li>
<li class="chapter" data-level="1.4" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#sales-marketing-interface"><i class="fa fa-check"></i><b>1.4</b> Sales marketing interface<span></span></a></li>
<li class="chapter" data-level="1.5" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#firm-level-impact-on-salespeople"><i class="fa fa-check"></i><b>1.5</b> Firm level impact on salespeople<span></span></a></li>
<li class="chapter" data-level="1.6" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salesperson-trait-orientation"><i class="fa fa-check"></i><b>1.6</b> Salesperson trait orientation<span></span></a></li>
<li class="chapter" data-level="1.7" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#salesperson-non-sales-activity-service"><i class="fa fa-check"></i><b>1.7</b> Salesperson non-sales activity/ service<span></span></a></li>
<li class="chapter" data-level="1.8" data-path="selling-and-buying-process.html"><a href="selling-and-buying-process.html#b2g-selling"><i class="fa fa-check"></i><b>1.8</b> B2G selling<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="literature-review-note.html"><a href="literature-review-note.html"><i class="fa fa-check"></i><b>2</b> Literature Review Note<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="literature-review-note.html"><a href="literature-review-note.html#persuasion-knowledge-model-review"><i class="fa fa-check"></i><b>2.1</b> Persuasion knowledge Model Review<span></span></a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="literature-review-note.html"><a href="literature-review-note.html#summary-for-pkm-in-online-environment"><i class="fa fa-check"></i><b>2.1.1</b> Summary for PKM in online environment<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html"><i class="fa fa-check"></i><b>3</b> Database marketing substantive domain<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#key-issues"><i class="fa fa-check"></i><b>3.1</b> Key Issues<span></span></a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#data-privacy"><i class="fa fa-check"></i><b>3.1.1</b> Data Privacy<span></span></a></li>
<li class="chapter" data-level="3.1.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#customer-lifetime-value-ltv"><i class="fa fa-check"></i><b>3.1.2</b> Customer lifetime value (LTV)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#method"><i class="fa fa-check"></i><b>3.2</b> Method<span></span></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#rfm"><i class="fa fa-check"></i><b>3.2.1</b> RFM<span></span></a></li>
<li class="chapter" data-level="3.2.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#market-basket-analysis"><i class="fa fa-check"></i><b>3.2.2</b> Market basket analysis<span></span></a></li>
<li class="chapter" data-level="3.2.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#collaborative-filtering"><i class="fa fa-check"></i><b>3.2.3</b> Collaborative filtering<span></span></a></li>
<li class="chapter" data-level="3.2.4" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#cluster-analysis"><i class="fa fa-check"></i><b>3.2.4</b> Cluster analysis<span></span></a></li>
<li class="chapter" data-level="3.2.5" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#decision-trees"><i class="fa fa-check"></i><b>3.2.5</b> Decision trees<span></span></a></li>
<li class="chapter" data-level="3.2.6" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#machine-learning"><i class="fa fa-check"></i><b>3.2.6</b> Machine learning<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#sub---substantive-areas"><i class="fa fa-check"></i><b>3.3</b> Sub - substantive areas<span></span></a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#acquisition"><i class="fa fa-check"></i><b>3.3.1</b> Acquisition<span></span></a></li>
<li class="chapter" data-level="3.3.2" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#retention-churn-management"><i class="fa fa-check"></i><b>3.3.2</b> Retention/ Churn management<span></span></a></li>
<li class="chapter" data-level="3.3.3" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#cross-selling-and-up-selling"><i class="fa fa-check"></i><b>3.3.3</b> Cross-selling and up-selling<span></span></a></li>
<li class="chapter" data-level="3.3.4" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#reward-program"><i class="fa fa-check"></i><b>3.3.4</b> Reward program<span></span></a></li>
<li class="chapter" data-level="3.3.5" data-path="database-marketing-substantive-domain.html"><a href="database-marketing-substantive-domain.html#multichannel-customer"><i class="fa fa-check"></i><b>3.3.5</b> Multichannel customer<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-scientist-job.html"><a href="data-scientist-job.html"><i class="fa fa-check"></i><b>4</b> Data Scientist Job<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#business-strategy-track-a.k.a-marketing-analytics"><i class="fa fa-check"></i><b>4.1</b> Business strategy Track (a.k.a Marketing Analytics)<span></span></a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#database-marketing"><i class="fa fa-check"></i><b>4.1.1</b> Database marketing<span></span></a></li>
<li class="chapter" data-level="4.1.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#programming"><i class="fa fa-check"></i><b>4.1.2</b> Programming<span></span></a></li>
<li class="chapter" data-level="4.1.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#statistics"><i class="fa fa-check"></i><b>4.1.3</b> Statistics:<span></span></a></li>
<li class="chapter" data-level="4.1.4" data-path="data-scientist-job.html"><a href="data-scientist-job.html#visualization"><i class="fa fa-check"></i><b>4.1.4</b> Visualization<span></span></a></li>
<li class="chapter" data-level="4.1.5" data-path="data-scientist-job.html"><a href="data-scientist-job.html#automation"><i class="fa fa-check"></i><b>4.1.5</b> Automation<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#consumer-insight-track-aka.-marketing-research"><i class="fa fa-check"></i><b>4.2</b> Consumer insight Track (aka. Marketing Research)<span></span></a></li>
<li class="chapter" data-level="4.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#optimization-track-a.k.a-operational-research"><i class="fa fa-check"></i><b>4.3</b> Optimization Track (a.k.a Operational Research)<span></span></a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="data-scientist-job.html"><a href="data-scientist-job.html#model-optimization"><i class="fa fa-check"></i><b>4.3.1</b> Model optimization<span></span></a></li>
<li class="chapter" data-level="4.3.2" data-path="data-scientist-job.html"><a href="data-scientist-job.html#macro-level-models"><i class="fa fa-check"></i><b>4.3.2</b> Macro level models<span></span></a></li>
<li class="chapter" data-level="4.3.3" data-path="data-scientist-job.html"><a href="data-scientist-job.html#academic-paper-implementation"><i class="fa fa-check"></i><b>4.3.3</b> Academic Paper implementation<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html"><i class="fa fa-check"></i><b>5</b> Marketing Strategy PhD skills<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#reading"><i class="fa fa-check"></i><b>5.1</b> Reading<span></span></a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#meta-skill-to-gain"><i class="fa fa-check"></i><b>5.1.1</b> Meta skill to gain<span></span></a></li>
<li class="chapter" data-level="5.1.2" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#reading-purpose"><i class="fa fa-check"></i><b>5.1.2</b> Reading Purpose<span></span></a></li>
<li class="chapter" data-level="5.1.3" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#how-to-train"><i class="fa fa-check"></i><b>5.1.3</b> How to train<span></span></a></li>
<li class="chapter" data-level="5.1.4" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#suggested-reading-optional"><i class="fa fa-check"></i><b>5.1.4</b> Suggested reading (optional)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="marketing-strategy-phd-skills.html"><a href="marketing-strategy-phd-skills.html#writing"><i class="fa fa-check"></i><b>5.2</b> Writing<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html"><i class="fa fa-check"></i><b>6</b> Applied Stats Model II - Exam 1<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-in-a-poisson-regression-problem-with-one-explanatory-variable-x-the-estimate-of-the-β"><i class="fa fa-check"></i><b>6.1</b> 1. (7 points) In a poisson regression problem with one explanatory variable x, the estimate of the β<span></span></a></li>
<li class="chapter" data-level="6.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-in-a-generalized-linear-model-why-is-the-null-deviance-typically-larger-than-the-residual-deviance"><i class="fa fa-check"></i><b>6.2</b> 2. (5 points) In a generalized linear model, why is the null deviance typically larger than the residual deviance?<span></span></a></li>
<li class="chapter" data-level="6.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-can-standard-linear-regression-ever-be-used-when-the-data-are-counts-explain-why-or-why-not."><i class="fa fa-check"></i><b>6.3</b> 3. (5 points) Can standard linear regression ever be used when the data are counts? Explain why or why not.<span></span></a></li>
<li class="chapter" data-level="6.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#take-the-following-random-effect-model"><i class="fa fa-check"></i><b>6.4</b> 4. Take the following random effect model<span></span></a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#section"><i class="fa fa-check"></i><b>6.4.1</b> </a></li>
<li class="chapter" data-level="6.4.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-find-the-intra-class-correlation-coefficient."><i class="fa fa-check"></i><b>6.4.2</b> (3 points) Find the intra class correlation coefficient.<span></span></a></li>
<li class="chapter" data-level="6.4.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-which-level-of-the-random-effect-α-will-have-the-largest-predicted-value"><i class="fa fa-check"></i><b>6.4.3</b> (2 points) Which level of the random effect α will have the largest predicted value?<span></span></a></li>
<li class="chapter" data-level="6.4.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-predict-y-for-level-6-of-the-random-effect."><i class="fa fa-check"></i><b>6.4.4</b> (2 points) Predict y for level 6 of the random effect.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#utilizing-the-below-code-and-output-answer-the-following"><i class="fa fa-check"></i><b>6.5</b> 5. Utilizing the below code and output, answer the following:<span></span></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-why-are-the-residual-and-null-deviance-values-the-same"><i class="fa fa-check"></i><b>6.5.1</b> • (3 points) Why are the residual and null deviance values the same?<span></span></a></li>
<li class="chapter" data-level="6.5.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#points-based-on-these-deviance-values-does-the-model-fit-well-does-this-make-sense"><i class="fa fa-check"></i><b>6.5.2</b> • (2 points) Based on these deviance values, does the model “fit” well? Does this make sense?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#take-the-data-given-by-problem6data.csv-which-contains-a-continuous-response-y-and-two-predictors-x1-and-x2."><i class="fa fa-check"></i><b>6.6</b> 6. Take the data given by Problem6Data.csv, which contains a continuous response y and two predictors x1 and x2.<span></span></a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#a.-5-points-read-the-data-into-r-and-make-some-plots-between-the-response-and-predictors.-describe-the-patterns-and-comment-on-behaviors-you-observe-with-exact-0s."><i class="fa fa-check"></i><b>6.6.1</b> a. (5 points) Read the data into R and make some plots between the response and predictors. Describe the patterns and comment on behaviors you observe with exact 0s.<span></span></a></li>
<li class="chapter" data-level="6.6.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#b.-5-points-make-a-histogram-of-the-response-variable-and-comment-on-the-shape.-are-the-values-strictly-positive"><i class="fa fa-check"></i><b>6.6.2</b> b. (5 points) Make a histogram of the response variable and comment on the shape. Are the values strictly positive?<span></span></a></li>
<li class="chapter" data-level="6.6.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#c.-4-points-state-the-range-that-the-index-parameter-p-for-use-in-the-tweedie-distribution-must-be-contained-in.-why-is-this-the-case"><i class="fa fa-check"></i><b>6.6.3</b> c. (4 points) State the range that the index parameter p, for use in the Tweedie distribution, must be contained in. Why is this the case?<span></span></a></li>
<li class="chapter" data-level="6.6.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#d.-6-points-find-an-optimal-value-of-p-for-use-in-the-tweedie-distribution-using-a-log-link."><i class="fa fa-check"></i><b>6.6.4</b> d. (6 points) Find an optimal value of p for use in the Tweedie Distribution, using a log link.<span></span></a></li>
<li class="chapter" data-level="6.6.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#e.-5-points-again-using-a-log-link-fit-a-tweedie-distribution-using-the-index-parameter-value-you-obtained-in-part-d."><i class="fa fa-check"></i><b>6.6.5</b> e. (5 points) Again using a log link, fit a Tweedie Distribution using the index parameter value you obtained in part d.<span></span></a></li>
<li class="chapter" data-level="6.6.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#f.-6-points-for-each-of-the-values-of-x2-given-by-the-r-vector-x2_vals---seq0-15-by-.01-use-the-compound-poisson-gamma-structure-to-predict-the-probability-of-obtaining-an-exact-0-response-when-x1-is-at-its-mean-value."><i class="fa fa-check"></i><b>6.6.6</b> f. (6 points) For each of the values of x2 given by the R vector x2_vals &lt;- seq(0, 15, by= .01), use the compound Poisson-Gamma structure to predict the probability of obtaining an exact 0 response when x1 is at its mean value.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#the-ships-dataset-in-the-mass-package-provides-the-number-of-incidentsindicents-resulting-in-ship-damage-as-a-function-of-total-months-of-serviceservice-ship-typetype-as-well-as-year-of-ship-constructionyear-broken-into-5-year-increments-with-the-years-variable-value-indicating-the-beginning-of-this-period.-e.g.-year60-refers-to-1960-1964-period-of-operationperiod-with-realizations-60-1960---1974-75-1975---1979-the-data-can-be-loaded-with-dataships-packagemass"><i class="fa fa-check"></i><b>6.7</b> 7. The ships dataset in the MASS package provides the number of incidents(indicents) resulting in ship damage as a function of total months of service(service), ship type(type), as well as: • Year of ship construction(year) – Broken into 5 year increments with the year’s variable value indicating the beginning of this period. e.g. year=60 refers to 1960-1964 • Period of operation(period) with realizations: – 60: 1960 - 1974 – 75: 1975 - 1979 The data can be loaded with: data(ships, package=“MASS”)<span></span></a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#a.-4-points-use-group_by-and-summarise-to-compute-the-average-months-of-service-for-each-combination-of-year-of-construction-and-period-of-operation.-explain-why-there-is-a-0-in-the-result."><i class="fa fa-check"></i><b>6.7.1</b> a. (4 points) Use group_by and summarise to compute the average months of service for each combination of year of construction and period of operation. Explain why there is a 0 in the result.<span></span></a></li>
<li class="chapter" data-level="6.7.2" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#b.-3-points-create-a-new-filtered-dataset-by-removing-the-rows-where-service0."><i class="fa fa-check"></i><b>6.7.2</b> b. (3 points) Create a new filtered dataset by removing the rows where service=0.<span></span></a></li>
<li class="chapter" data-level="6.7.3" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#c.-10-points-fit-both-a-poisson-rate-model-and-negative-binomial-rate-model-model-using-number-of-incidents-per-service-month-as-the-response-and-all-other-variables-as-predictors.-compare-which-model-is-better-using-aic."><i class="fa fa-check"></i><b>6.7.3</b> c. (10 points) Fit both a Poisson rate model and Negative Binomial rate model model using number of incidents per service month as the response and all other variables as predictors. Compare which model is better using AIC.<span></span></a></li>
<li class="chapter" data-level="6.7.4" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#d.-7-points-using-the-better-model-selected-in-part-c-assess-the-significance-of-each-term-using-drop1.-which-terms-are-insignificant-remove-the-insignificant-variables-from-the-model-in-c-and-refit."><i class="fa fa-check"></i><b>6.7.4</b> d. (7 points) Using the better model selected in part c, assess the significance of each term using drop1(). Which terms are insignificant? Remove the insignificant variables from the model in c, and refit.<span></span></a></li>
<li class="chapter" data-level="6.7.5" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#e.-6-points-statistically-compare-the-residual-deviance-in-your-final-model-from-d-to-the-null-deviance."><i class="fa fa-check"></i><b>6.7.5</b> e. (6 points) Statistically compare the residual deviance in your final model from d to the null deviance.<span></span></a></li>
<li class="chapter" data-level="6.7.6" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#f.-4-points-compare-the-aic-from-the-reduced-model-in-d-to-the-corresponding-value-from-c.-is-the-change-you-see-expected-also-examine-the-residual-deviance-of-the-model-in-d-what-does-it-say-about-the-models-fit-to-the-data"><i class="fa fa-check"></i><b>6.7.6</b> f. (4 points) Compare the AIC from the reduced model in d to the corresponding value from c. Is the change you see expected? Also examine the residual deviance of the model in d, what does it say about the model’s fit to the data?<span></span></a></li>
<li class="chapter" data-level="6.7.7" data-path="applied-stats-model-ii---exam-1.html"><a href="applied-stats-model-ii---exam-1.html#g.-6-points-make-a-plot-of-the-deviance-residuals-vs-the-predicted-valueslink-scale.-how-is-the-fit"><i class="fa fa-check"></i><b>6.7.7</b> g. (6 points) Make a plot of the deviance residuals vs the predicted values(link scale). How is the fit?<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="question-1.html"><a href="question-1.html"><i class="fa fa-check"></i><b>7</b> Question 1:<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="question-1.html"><a href="question-1.html#a.-8-points-create-plots-to-examine-how-launch-speed-and-angle-may-affect-the-probability-of-a-home-run-and-describe-your-findings."><i class="fa fa-check"></i><b>7.1</b> a. (8 points) Create plots to examine how launch speed and angle may affect the probability of a home run and describe your findings.<span></span></a></li>
<li class="chapter" data-level="7.2" data-path="question-1.html"><a href="question-1.html#b.-9-points-fit-a-logistic-regression-model-with-home_run-as-the-response-and-all-other-variables-as-predictors.-conduct-a-deviance-test-to-assess-if-this-model-is-better-than-the-null-model."><i class="fa fa-check"></i><b>7.2</b> b. (9 points) Fit a logistic regression model with home_run as the response and all other variables as predictors. Conduct a deviance test to assess if this model is better than the null model.<span></span></a></li>
<li class="chapter" data-level="7.3" data-path="question-1.html"><a href="question-1.html#c.-8-points-conduct-deviance-tests-with-the-drop1-function-to-assess-the-significance-of-each-individual-variable-and-report-the-results.-compare-the-p-values-to-those-obtained-from-summary."><i class="fa fa-check"></i><b>7.3</b> c. (8 points) Conduct deviance tests with the drop1() function to assess the significance of each individual variable and report the results. Compare the p-values to those obtained from summary().<span></span></a></li>
<li class="chapter" data-level="7.4" data-path="question-1.html"><a href="question-1.html#d.-6-points-fit-a-smaller-model-after-removing-all-variables-which-are-insignificant-using-α-0.05.-compare-this-model-to-the-larger-model-are-they-significantly-different-what-are-the-implications-of-this-with-regard-to-model-selection-until-the-end-of-this-question-use-the-smaller-model-for-all-analysis"><i class="fa fa-check"></i><b>7.4</b> d. (6 points) Fit a smaller model after removing all variables which are insignificant using α = 0.05. Compare this model to the larger model, are they significantly different? What are the implications of this with regard to model selection? Until the end of this question, use the smaller model for all analysis<span></span></a></li>
<li class="chapter" data-level="7.5" data-path="question-1.html"><a href="question-1.html#e.-7-points-how-does-the-launch-speed-after-the-ball-is-hit-affect-the-odds-of-homerun-occurring-provide-a-confidence-interval-for-this-value."><i class="fa fa-check"></i><b>7.5</b> e. (7 points) How does the launch speed after the ball is hit affect the <strong>odds of HomeRun occurring</strong>? Provide a confidence interval for this value.<span></span></a></li>
<li class="chapter" data-level="7.6" data-path="question-1.html"><a href="question-1.html#f.-5-points-using-the-deviance-residuals-make-a-binned-residual-vs-fitted-probability-plot-and-comment-on-the-fit-of-the-model."><i class="fa fa-check"></i><b>7.6</b> f. (5 points) Using the deviance residuals, make a binned residual vs fitted probability plot and comment on the fit of the model.<span></span></a></li>
<li class="chapter" data-level="7.7" data-path="question-1.html"><a href="question-1.html#g.-4-points-using-a-probability-of-0.5-as-the-threshold-for-predicting-an-observation-yielding-a-home-run-create-a-table-classifying-the-predictions-against-the-observed-values.-describe-your-findings.-what-is-the-misclassification-rate"><i class="fa fa-check"></i><b>7.7</b> g. (4 points) Using a probability of 0.5 as the threshold for predicting an observation yielding a home run, create a table classifying the predictions against the observed values. Describe your findings. What is the misclassification rate?<span></span></a></li>
<li class="chapter" data-level="7.8" data-path="question-1.html"><a href="question-1.html#h.-6-points-using-probability-thresholds-from-0.005-to-0.995-obtain-the-sensitivities-and-specificity-of-the-resulting-predictions.-create-an-roc-plot-and-comment-on-the-effectiveness-of-the-models-ability-to-correctly-classify-the-response.-as-we-vary-the-threshold-to-determine-classifications-is-inverse-relationship-between-sensitivity-and-specificity-strongly-evident"><i class="fa fa-check"></i><b>7.8</b> h. (6 points) Using probability thresholds from 0.005 to 0.995, obtain the sensitivities and specificity of the resulting predictions. Create an ROC plot and comment on the effectiveness of the model’s ability to correctly classify the response. As we vary the threshold to determine classifications, is inverse relationship between sensitivity and specificity strongly evident?<span></span></a></li>
<li class="chapter" data-level="7.9" data-path="question-1.html"><a href="question-1.html#i.-5-points-produce-a-plot-of-the-sensitivity-and-specificity-against-the-threshold.-is-there-a-threshold-for-classification-you-would-recommend-that-provides-a-good-balance-between-the-two-make-another-confusion-matrix-using-this-cutoff-how-does-the-result-compare-to-the-previous-one-consider-the-types-of-errors-you-observe."><i class="fa fa-check"></i><b>7.9</b> i. (5 points) Produce a plot of the sensitivity and specificity against the threshold. Is there a threshold for classification you would recommend that provides a good balance between the two? Make another confusion matrix using this cutoff, how does the result compare to the previous one? Consider the types of errors you observe.<span></span></a></li>
<li class="chapter" data-level="7.10" data-path="question-1.html"><a href="question-1.html#j.-3-points-consider-a-logistic-model-with-only-launch_angle-and-launch_speed-being-used-to-predict-the-probability-of-a-home-run.-what-is-the-aic-of-this-model"><i class="fa fa-check"></i><b>7.10</b> j. (3 points) Consider a logistic model with only launch_angle and launch_speed being used to predict the probability of a home run. What is the AIC of this model?<span></span></a></li>
<li class="chapter" data-level="7.11" data-path="question-1.html"><a href="question-1.html#k.-11-points-create-a-dummy-variable-which-is-1-if-launch_angle-is-between-20-and-40-degrees-and-use-this-variable-in-your-model-instead-of-the-raw-value-for-launch_angle.-then-complete-the-following-1.-compare-the-aic-of-this-model-to-the-model-in-part-j-which-model-is-better-2.-what-does-the-coefficient-of-your-dummy-variable-mean-interpret-the-value.-3.-interpret-the-value-of-the-intercept-by-converting-to-a-probability.-does-this-result-make-sense"><i class="fa fa-check"></i><b>7.11</b> k. (11 points) Create a dummy variable which is 1 if launch_angle is between 20 and 40 degrees and use this variable in your model instead of the raw value for launch_angle. Then, complete the following: 1. Compare the AIC of this model to the model in part j, which model is better? 2. What does the coefficient of your dummy variable mean? Interpret the value. 3. Interpret the value of the intercept by converting to a probability. Does this result make sense?<span></span></a>
<ul>
<li class="chapter" data-level="7.11.1" data-path="question-1.html"><a href="question-1.html#section-1"><i class="fa fa-check"></i><b>7.11.1</b> </a></li>
</ul></li>
<li class="chapter" data-level="7.12" data-path="question-1.html"><a href="question-1.html#a.-5-points-make-a-plot-or-set-of-tables-showing-the-distribution-of-lsd-use-between-genders-and-interpret.-you-can-use-code-similar-to-that-on-slide-84-of-the-course-notes."><i class="fa fa-check"></i><b>7.12</b> a. (5 points) Make a plot or set of tables showing the distribution of LSD use between genders and interpret. You can use code similar to that on slide 84 of the course notes.<span></span></a></li>
<li class="chapter" data-level="7.13" data-path="question-1.html"><a href="question-1.html#b.-9-points-fit-a-proportional-odds-model-using-lsd-as-the-response-variable-and-the-other-variables-listed-above-as-predictors.-using-drop1-test-if-the-variables-are-significant-or-insignificant-and-describe-2-your-results."><i class="fa fa-check"></i><b>7.13</b> b. (9 points) Fit a proportional odds model using LSD as the response variable and the other variables listed above as predictors. Using drop1(), test if the variables are significant or insignificant and describe 2 your results.<span></span></a></li>
<li class="chapter" data-level="7.14" data-path="question-1.html"><a href="question-1.html#c.-6-points-interpret-the-values-of-the-intercepts-θj-."><i class="fa fa-check"></i><b>7.14</b> c. (6 points) Interpret the values of the intercepts θj .<span></span></a></li>
<li class="chapter" data-level="7.15" data-path="question-1.html"><a href="question-1.html#d.-10-points-print-the-coefficient-table-and-interpret-the-values-of-the-significant-personality-characteristics."><i class="fa fa-check"></i><b>7.15</b> d. (10 points) Print the coefficient table and interpret the values of the significant personality characteristics.<span></span></a></li>
<li class="chapter" data-level="7.16" data-path="question-1.html"><a href="question-1.html#e.-7250-only-6-points-explore-interacting-some-of-the-categorical-demographic-variables-with-the-personality-measurements-and-report-your-findings-does-the-nature-of-any-personality-characteristics-affect-on-lsd-usage-change-according-to-your-analysis"><i class="fa fa-check"></i><b>7.16</b> e. (7250 only) (6 points) Explore interacting some of the categorical demographic variables with the personality measurements and report your findings, does the nature of any personality characteristics affect on LSD usage change according to your analysis?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html"><i class="fa fa-check"></i><b>8</b> 1 1) Modeling the Number of Claims<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#a.-5-points-create-a-table-to-present-the-distribution-of-the-number-of-claims-by-computing-the-proportion-of-each-possibility.-what-percent-of-the-policies-have-0-claims"><i class="fa fa-check"></i><b>8.1</b> a. (5 points) Create a table to present the distribution of the number of claims by computing the proportion of each possibility. What percent of the policies have 0 claims?<span></span></a></li>
<li class="chapter" data-level="8.2" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#b.-6-points-create-a-poisson-regression-to-predict-the-number-of-claims-in-the-year-using-only-the-variables-for-vehicle-age-driver-age-bonusmalus-and-density.-what-is-the-deviance-does-is-differ-significantly-from-the-null-deviance"><i class="fa fa-check"></i><b>8.2</b> b. (6 points) Create a Poisson regression to predict the number of claims in the year using only the variables for vehicle age, driver age, bonusMalus, and density. What is the deviance? Does is differ significantly from the null deviance?<span></span></a></li>
<li class="chapter" data-level="8.3" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#c.-4-points-generate-predictions-on-the-response-scale-µ-and-round-them-to-the-nearest-count.-create-a-table-as-in-part-a-and-comment-on-how-similar-or-dissimilar-this-result-is."><i class="fa fa-check"></i><b>8.3</b> c. (4 points) Generate predictions on the response scale µ and round them to the nearest count. Create a table as in part a and comment on how similar or dissimilar this result is.<span></span></a></li>
<li class="chapter" data-level="8.4" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#d.-3-points-fit-a-negative-binomial-model-to-the-data-and-generate-predictions-as-in-part-c.-did-this-solve-the-problem"><i class="fa fa-check"></i><b>8.4</b> d. (3 points) Fit a negative binomial model to the data and generate predictions as in part c. Did this solve the problem?<span></span></a></li>
<li class="chapter" data-level="8.5" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#e.-5-points-now-fit-a-zero-inflation-poisson-model-zip-and-compute-the-fitted-proportion-of-zero-counts-as-on-slide-38-of-the-poisson-notes.-does-this-help"><i class="fa fa-check"></i><b>8.5</b> e. (5 points) Now fit a zero inflation Poisson model (ZIP) and compute the fitted proportion of zero counts as on slide 38 of the Poisson Notes. Does this help?<span></span></a></li>
<li class="chapter" data-level="8.6" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#f.-8-points-interpret-the-signs-of-the-coefficient-estimates-out-of-the-zip-model-both-the-count-portion-as-well-as-the-zero-inflated-portion"><i class="fa fa-check"></i><b>8.6</b> f. (8 points) Interpret the signs of the coefficient estimates out of the ZIP model, both the count portion as well as the zero inflated portion!<span></span></a></li>
<li class="chapter" data-level="8.7" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#a.-3-points-in-this-problem-we-will-focus-on-modeling-the-positive-continuous-variable-avgclaimamount.-attempt-to-fit-a-gamma-regression-with-a-log-link-predicting-avgclaimamount-as-a-function-of-all-feature-variables-in-the-dataset.-what-happens-when-you-attempt-to-fit-this-model"><i class="fa fa-check"></i><b>8.7</b> a. (3 points) In this problem we will focus on modeling the positive continuous variable “AvgClaimAmount.” Attempt to fit a Gamma regression with a log link, predicting AvgClaimAmount as a function of all feature variables in the dataset. What happens when you attempt to fit this model?<span></span></a></li>
<li class="chapter" data-level="8.8" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#b.-5-points-create-a-new-dataset-consisting-of-the-rows-that-correspond-to-strictly-positive-realizations-of-avgclaimamount.-make-a-histogram-of-this-variable-on-standard-and-log-scale-and-describe-your-findings."><i class="fa fa-check"></i><b>8.8</b> b. (5 points) Create a new dataset consisting of the rows that correspond to strictly positive realizations of AvgClaimAmount. Make a histogram of this variable on standard and log scale and describe your findings.<span></span></a></li>
<li class="chapter" data-level="8.9" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#c.-4-points-fit-the-gamma-regression-proposed-in-part-a-to-the-filtered-dataset.-do-you-notice-anything-strange-how-many-iterations-did-it-take-glm-to-find-this-result"><i class="fa fa-check"></i><b>8.9</b> c. (4 points) Fit the Gamma regression proposed in part a to the filtered dataset. Do you notice anything strange? How many iterations did it take glm() to find this result?<span></span></a></li>
<li class="chapter" data-level="8.10" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#d.-3-points-to-the-glm-function-add-the-argument-control-listmaxit-500.-what-do-you-think-this-will-do-fit-the-model-and-examine-the-summary-output-to-check-the-number-of-iterations-needed-for-convergence."><i class="fa fa-check"></i><b>8.10</b> d. (3 points) To the glm() function, add the argument control = list(maxit = 500). What do you think this will do? Fit the model and examine the summary output to check the number of iterations needed for convergence.<span></span></a></li>
<li class="chapter" data-level="8.11" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#e.3-points-from-the-model-in-e.-interpret-the-parameter-estimate-for-a-vehicles-age"><i class="fa fa-check"></i><b>8.11</b> e.(3 points) From the model in e. Interpret the parameter estimate for a vehicle’s age<span></span></a></li>
<li class="chapter" data-level="8.12" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#a.-8-points-using-the-entire-dataset-create-a-profile-likelihood-of-the-index-values-p-for-use-in-a-glm-utilizing-the-tweedie-distribution-to-predict-purepremium-directly.-make-a-plot-of-the-profile-likelihood-and-select-the-best-value.-7520---3-points-for-graduate-students-i-expect-some-exploration-to-find-the-best-value-as-these-data-are-quite-poorly-behaved.-look-at-the-value-section-of-tweedie.profile-for-some-hints-and-i-would-suggest-narrowing-the-search-space-for-p-and-evaluating-it-on-a-somewhat-fine-grid."><i class="fa fa-check"></i><b>8.12</b> a. (8 points) Using the entire dataset, create a profile likelihood of the index values p for use in a glm utilizing the Tweedie distribution to predict PurePremium directly. Make a plot of the profile likelihood and select the best value. (7520 - 3 points): For graduate students, I expect some <strong>exploration to find the best value as these data are quite poorly behaved</strong>. Look at the “Value” section of ?tweedie.profile for some hints, and I <strong>would suggest narrowing the search space for p and evaluating it on a somewhat fine grid.</strong><span></span></a></li>
<li class="chapter" data-level="8.13" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#b.-fit-the-tweedie-glm-model-using-the-optimal-power-value-you-computed-from-the-previous-question.-the-file-insurance_test.csv-contains-a-few-additional-observations-which-were-not-a-portion-of-the-data-used-to-fit-the-previous-models.-we-can-read-it-in-and-format-it-using-syntax-similar-to-when-we-started.-newdatapoints---read.csv.insurance_test.csv-newdatapointsvehbrand---as.factornewdatapointsvehbrand-newdatapointsvehpower---as.factornewdatapointsvehpower-newdatapointsvehgas---as.factornewdatapointsvehgas-newdatapointsregion---as.factornewdatapointsregion-newdatapointsarea---as.factornewdatapointsarea"><i class="fa fa-check"></i><b>8.13</b> b. Fit the Tweedie GLM model using the optimal power value you computed from the previous question. The file Insurance_test.csv contains a few additional observations which were not a portion of the data used to fit the previous models. We can read it in and format it using syntax similar to when we started. NewDataPoints &lt;- read.csv(“…./Insurance_test.csv”) NewDataPoints$VehBrand &lt;- as.factor(NewDataPoints$VehBrand) NewDataPoints$VehPower &lt;- as.factor(NewDataPoints$VehPower) NewDataPoints$VehGas &lt;- as.factor(NewDataPoints$VehGas) NewDataPoints$Region &lt;- as.factor(NewDataPoints$Region) NewDataPoints$Area &lt;- as.factor(NewDataPoints$Area)<span></span></a></li>
<li class="chapter" data-level="8.14" data-path="modeling-the-number-of-claims.html"><a href="modeling-the-number-of-claims.html#c.7-points-use-your-poisson-model-from-1b-from-and-your-final-gamma-model-from-2d-to-generate-respective-predictions-for-the-number-of-claims-in-a-year-as-well-as-the-average-amount-per-claim.-multiply-these-together-and-call-this-product-purepremium_prod.-similarly-use-your-tweedie-model-from-3b-to-directly-predict-the-purepremium-value-and-store-this-in-purepremium_tw."><i class="fa fa-check"></i><b>8.14</b> c.(7 points) Use your Poisson model from 1b from and your final Gamma model from 2d to generate respective predictions for the number of claims in a year as well as the average amount per claim. Multiply these together and call this product purepremium_prod. Similarly, use your Tweedie model from 3b to directly predict the PurePremium value and store this in purepremium_TW.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><i class="fa fa-check"></i><b>9</b> STAT 4520/7520 - Homework 3 Spring 2022 Due: March 30, 2022<span></span></a>
<ul>
<li class="chapter" data-level="9.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#the-cake-dataset-in-the-lme4-package-contains-data-on-an-experiment-was-conducted-to-determine-the-effect-of-recipe-and-baking-temperature-on-chocolate-cake-quality.-fifteen-batches-of-cake-mix-for-each-recipe-were-prepared.-each-batch-was-sufficient-for-six-cakes.-each-of-the-six-cakes-was-baked-at-a-different-temperature-which-was-randomly-assigned.-as-an-indicator-of-quality-the-breakage-angle-of-the-cake-was-recorded."><i class="fa fa-check"></i><b>9.1</b> 1) The cake dataset in the lme4 package contains data on an experiment was conducted to determine the effect of recipe and baking temperature on chocolate cake quality. Fifteen batches of cake mix for each recipe were prepared. Each batch was sufficient for six cakes. Each of the six cakes was baked at a different temperature which was randomly assigned. As an indicator of quality, the breakage angle of the cake was recorded.<span></span></a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#a.-of-the-explanatory-variables-recipe-temp-and-replicate-which-are-fixed-and-which-are-random-explain.-is-there-any-nesting-in-these-variables"><i class="fa fa-check"></i><b>9.1.1</b> a. Of the explanatory variables recipe, temp, and replicate, which are fixed and which are random? Explain. Is there any nesting in these variables?<span></span></a></li>
<li class="chapter" data-level="9.1.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#b.-fit-a-linear-model-with-no-random-effects-for-breaking-angle-against-the-interaction-between-recipe-and-temperature.-which-variables-are-significant-what-is-the-t-value-for-temp-the-temperature-variable-what-is-the-rmse-of-this-model"><i class="fa fa-check"></i><b>9.1.2</b> b. Fit a linear model with no random effects for breaking angle against the interaction between recipe and temperature. Which variables are significant? What is the t value for temp the temperature variable? What is the RMSE of this model?<span></span></a></li>
<li class="chapter" data-level="9.1.3" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#c.-fit-a-mixed-model-to-the-data-which-takes-into-account-the-replicates-of-the-recipes.-examine-the-variance-components.-is-there-variation-in-the-batches-made-with-each-recipe-how-does-the-residual-variance-component-compare-to-the-mse-from-b-what-is-the-t-value-for-temperature"><i class="fa fa-check"></i><b>9.1.3</b> c. Fit a mixed model to the data which takes into account the replicates of the recipes. Examine the variance components. Is there variation in the batches made with each recipe? How does the Residual variance component compare to the MSE from (b)? What is the t-value for temperature?<span></span></a></li>
<li class="chapter" data-level="9.1.4" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#d.-test-for-a-recipe-and-temperature-effect."><i class="fa fa-check"></i><b>9.1.4</b> d. Test for a recipe and temperature effect.<span></span></a></li>
<li class="chapter" data-level="9.1.5" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#e.-create-a-qq-plot-of-the-residuals-and-a-residual-vs-predicted-plot-for-the-linear-model-in-b-and-the-mixed-model-in-d-describe-how-well-the-model-assumptions-are-satisfied-for-each."><i class="fa fa-check"></i><b>9.1.5</b> e. Create a QQ plot of the residuals and a residual vs predicted plot for the linear model in (b) and the mixed model in (d), describe how well the model assumptions are satisfied for each.<span></span></a></li>
<li class="chapter" data-level="9.1.6" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#f.-7510-only-examine-the-blups-from-the-mixed-model-in-d.-do-you-notice-any-patterns"><i class="fa fa-check"></i><b>9.1.6</b> f. (7510 only) Examine the BLUPs from the mixed model in (d). Do you notice any patterns?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#the-purpose-of-random-effects-is-to-remove-variation-from-known-sources.-in-this-problem-we-will-use-this-idea-and-see-how-it-can-work-with-a-popular-technique-for-predictive-modeling-the-random-forest.-random-forests-were-covered-in-the-prerequisite-course-and-can-be-fit-using-the-randomforest-function-in-the-randomforest-library.-the-dataset-problem-2.csv-has-a-simulated-dataset.-there-is-a-nonlinear-relationship-between-6-numeric-explanatory-variables-x1-.-.-.-x6-and-the-response-y-to-addition-to-a-grouping-effect-according-to-the-id-variable-which-has-100-levels."><i class="fa fa-check"></i><b>9.2</b> 2) The purpose of random effects is to remove variation from known sources. In this problem, we will use this idea and see how it can work with a popular technique for predictive modeling, the random forest. Random forests were covered in the prerequisite course, and can be fit using the randomForest function in the randomForest library. The dataset Problem-2.csv has a simulated dataset. There is a nonlinear relationship between 6 numeric explanatory variables x1, . . . x6 and the response y, to addition to a grouping effect according to the ID variable, which has 100 levels.<span></span></a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#a.-read-in-the-dataset-and-split-the-data-into-a-training-and-test-set-using-95-of-the-data-for-the-training-set.-set-a-seed-of-1-for-consistency-of-results."><i class="fa fa-check"></i><b>9.2.1</b> a. Read in the dataset, and split the data into a training and test set, using 95% of the data for the training set. Set a seed of 1 for consistency of results.<span></span></a></li>
<li class="chapter" data-level="9.2.2" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#b.-fit-a-random-forest-model-to-the-training-data-using-y-as-the-response-with-x1-.-.-.-x6-and-id-as-the-explanatory-variables.-use-the-model-to-predict-y-in-the-test-set-and-compute-the-test-root-mean-squared-error-rmse-."><i class="fa fa-check"></i><b>9.2.2</b> b. Fit a random forest model to the training data using y as the response with x1, . . . x6 and ID as the explanatory variables. Use the model to predict y in the test set and compute the test root mean squared error ( RMSE ).<span></span></a></li>
<li class="chapter" data-level="9.2.3" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#c.-fit-the-mixed-model-yij-µ-idi-εij-to-the-training-data.-this-model-does-not-use-the-x_i-at-all-and-has-a-random-intercept-based-on-id.-after-fitting-the-model-extract-the-blups-for-id-and-add-them-to-the-constant-µˆ-the-estimate-of-the-overall-intercept.-what-do-these-values-represent-store-them-in-a-data-frame-along-with-a-column-storing-the-ids."><i class="fa fa-check"></i><b>9.2.3</b> c. Fit the mixed model yij = µ + IDi + εij to the training data. This model does not use the x_i at all, and has a random intercept based on ID. After fitting the model, extract the BLUPs for ID and add them to the constant µˆ, the estimate of the overall intercept. What do these values represent? Store them in a data frame along with a column storing the IDs.<span></span></a></li>
<li class="chapter" data-level="9.2.4" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#d.-add-a-column-to-the-test-dataset-containing-the-values-obtained-in-part-c-joined-to-the-test-dataset-by-matching-the-ids.-note-with-the-dplyr-package-loaded-you-can-quickly-join-by-id-using-a-line-like-data.test---left_joindata.test-int_plus_blups-by-id-examine-the-first-few-rows-and-describe-what-the-new-column-represents."><i class="fa fa-check"></i><b>9.2.4</b> d. Add a column to the test dataset containing the values obtained in part c, joined to the test dataset by matching the IDs. Note: with the dplyr package loaded, you can quickly join by ID using a line like: Data.Test &lt;- left_join(Data.Test, int_plus_blups, by = “ID”) Examine the first few rows and describe what the new column represents.<span></span></a></li>
<li class="chapter" data-level="9.2.5" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#e.-compute-the-residuals-of-the-mixed-model-fit-in-c-using-the-residuals-function-store-them-in-a-column-of-the-training-data."><i class="fa fa-check"></i><b>9.2.5</b> e. Compute the residuals of the mixed model fit in (c) using the residuals() function, store them in a column of the training data.<span></span></a></li>
<li class="chapter" data-level="9.2.6" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#f.-fit-another-random-forest-model-to-the-training-data-using-the-residuals-from-part-e-as-the-response-and-only-x1-.-.-.-x6-as-the-explanatory-variables.-use-this-model-to-predict-into-the-test-data-and-store-these-predictions.-what-do-these-predictions-represent"><i class="fa fa-check"></i><b>9.2.6</b> f. Fit another random forest model to the training data, using the residuals from part (e) as the response and only x1, . . . x6 as the explanatory variables. Use this model to predict into the test data and store these predictions. What do these predictions represent?<span></span></a></li>
<li class="chapter" data-level="9.2.7" data-path="stat-45207520---homework-3-spring-2022-due-march-30-2022.html"><a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html#g.-add-the-predictions-in-f-to-the-values-joined-to-the-test-data-in-d.-consider-these-values-test-predictions-and-compute-the-test-mse.-compare-this-to-the-test-mse-compared-in-part-b.-what-do-you-observe"><i class="fa fa-check"></i><b>9.2.7</b> g. Add the predictions in (f) to the values joined to the test data in (d). Consider these values test predictions, and compute the test MSE. Compare this to the test MSE compared in part (b). What do you observe?<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><i class="fa fa-check"></i><b>10</b> STAT 4520/7520 - Homework 4 Spring 2022 Due: April 25, 2022<span></span></a>
<ul>
<li class="chapter" data-level="10.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#section-2"><i class="fa fa-check"></i><b>10.1</b> 1)<span></span></a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-make-a-plot-of-weight-vs-time-for-the-data-with-rat-specific-lines-to-show-the-subject-specific-trajectory.-describe-your-findings.-7510-only-further-color-the-lines-differently-for-the-different-diets.-do-you-notice-anything-further"><i class="fa fa-check"></i><b>10.1.1</b> a. Make a plot of weight vs Time for the data with rat specific lines to show the subject specific trajectory. Describe your findings. (7510 only) Further, color the lines differently for the different diets. Do you notice anything further?<span></span></a></li>
<li class="chapter" data-level="10.1.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-use-lm-to-regress-the-weight-onto-the-time.-what-is-the-slope-and-intercept-of-this-model-is-the-slope-significant"><i class="fa fa-check"></i><b>10.1.2</b> b. Use lm() to regress the weight onto the Time. What is the slope and intercept of this model? Is the slope significant?<span></span></a></li>
<li class="chapter" data-level="10.1.3" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-use-the-lmlist-function-to-fit-a-linear-regression-model-that-describes-how-weight-varies-with-days-for-each-individual-rat.-how-do-the-slopes-and-intercepts-vary-do-you-notice-any-patterns-with-respect-to-diets"><i class="fa fa-check"></i><b>10.1.3</b> c. Use the lmList function to fit a linear regression model that describes how weight varies with days for each individual rat. How do the slopes and intercepts vary? Do you notice any patterns with respect to diets?<span></span></a></li>
<li class="chapter" data-level="10.1.4" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#d.-fit-a-random-intercept-model-to-account-for-the-different-weights-of-each-individual-rat-and-continue-to-use-time-as-a-fixed-effect.-answer-the-following"><i class="fa fa-check"></i><b>10.1.4</b> d. Fit a random intercept model to account for the different weights of each individual rat and continue to use Time as a fixed effect. Answer the following:<span></span></a></li>
<li class="chapter" data-level="10.1.5" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#e.-obtain-the-blups-for-the-rats-and-list-who-is-the-most-heavy."><i class="fa fa-check"></i><b>10.1.5</b> e. Obtain the BLUPs for the rats and list who is the most heavy.<span></span></a></li>
<li class="chapter" data-level="10.1.6" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#f.-fit-a-mixed-effects-model-that-describes-how-the-weight-varies-linearly-with-time-and-allows-for-random-variation-in-the-intercepts-and-slopes-of-the-rats.-then-do-the-following"><i class="fa fa-check"></i><b>10.1.6</b> f. Fit a mixed effects model that describes how the weight varies linearly with time and allows for random variation in the intercepts and slopes of the rats. Then do the following:<span></span></a></li>
<li class="chapter" data-level="10.1.7" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#g.-obtain-the-blups-for-the-model-in-part-f.-which-rat-has-the-fastest-rate-of-increase-the-slowest"><i class="fa fa-check"></i><b>10.1.7</b> g. Obtain the BLUPs for the model in part f. Which rat has the fastest rate of increase? The slowest?<span></span></a></li>
<li class="chapter" data-level="10.1.8" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#h.-add-the-fixed-diet-variable-to-the-model-in-the-form-of-an-interaction-with-time.-does-the-diet-effect-weight-is-this-effect-different-at-different-times"><i class="fa fa-check"></i><b>10.1.8</b> h. Add the (fixed) diet variable to the model in the form of an interaction with time. Does the diet effect weight? Is this effect different at different times?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#time-series"><i class="fa fa-check"></i><b>10.2</b> 2) Time Series<span></span></a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-create-a-variable-containing-the-log-base-10-of-the-eps-then-use-lm-to-regress-it-onto-time.-store-the-residuals-of-this-regression-in-another-variable-in-jj.-make-a-plot-of-the-residuals-vs-time-and-describe-your-findings."><i class="fa fa-check"></i><b>10.2.1</b> a. Create a variable containing the log (base 10) of the EPS, then use lm() to regress it onto Time. Store the residuals of this regression in another variable in JJ. Make a plot of the residuals vs Time and describe your findings.<span></span></a></li>
<li class="chapter" data-level="10.2.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-run-the-detrended-values-through-auto.arima-to-find-a-good-arma-model.-note-that-you-may-want-to-use-the-additional-argument-stepwise-false-to-allow-auto.arima-to-conduct-a-full-grid-search.-what-model-was-found"><i class="fa fa-check"></i><b>10.2.2</b> b. Run the detrended values through auto.arima() to find a good ARMA model. Note that you may want to use the additional argument stepwise = FALSE to allow auto.arima() to conduct a full grid search. What model was found?<span></span></a></li>
<li class="chapter" data-level="10.2.3" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-use-the-best-model-to-forecast-the-detrended-relationship-2-years-8-quarters-ahead.-make-a-plot-of-the-result-and-comment-on-how-reasonable-your-predictions-look."><i class="fa fa-check"></i><b>10.2.3</b> c. Use the best model to forecast the detrended relationship 2 years (8 quarters) ahead. Make a plot of the result and comment on how reasonable your predictions look.<span></span></a></li>
<li class="chapter" data-level="10.2.4" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#d.-use-the-linear-model-from-part-a-to-predict-the-trend-for-the-next-8-quarters-add-the-result-to-that-of-part-c-transform-back-to-the-original-scale-and-plot-the-forecast-along-with-the-original-data.-does-the-forecast-seem-reasonable"><i class="fa fa-check"></i><b>10.2.4</b> d. Use the linear model from part a to predict the trend for the next 8 quarters, add the result to that of part c, transform back to the original scale, and plot the forecast along with the original data. Does the forecast seem reasonable?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#spatial-point-process-analysis"><i class="fa fa-check"></i><b>10.3</b> 3) Spatial Point Process Analysis<span></span></a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-make-a-plot-of-the-point-pattern.-does-the-distribution-of-the-points-in-space-appear-to-be-homogeneous-poisson-process"><i class="fa fa-check"></i><b>10.3.1</b> a. Make a plot of the point pattern. Does the distribution of the points in space appear to be homogeneous Poisson process?<span></span></a></li>
<li class="chapter" data-level="10.3.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-make-plots-of-gr-and-fr-and-comment-on-what-you-observe."><i class="fa fa-check"></i><b>10.3.2</b> b. Make plots of G(r) and F(r) and comment on what you observe.<span></span></a></li>
<li class="chapter" data-level="10.3.3" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-fit-a-point-process-model-with-linear-terms-in-both-x-and-y.-are-there-any-significant-spatial-relationships"><i class="fa fa-check"></i><b>10.3.3</b> c. Fit a point process model with linear terms in both x and y. Are there any significant spatial relationships?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#loading-keras"><i class="fa fa-check"></i><b>10.4</b> 4) Loading Keras<span></span></a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-mostly-as-an-exercise-to-ensure-you-have-keras-installed-correctly-run-the-above-code-and-comment-onthe-quality-of-the-fit-you-observe.-note-i-was-unable-to-run-the-code-within-an-rmarkdown-cell-but-this-may-be-due-to-a-system-configuration-issue."><i class="fa fa-check"></i><b>10.4.1</b> a. Mostly as an exercise to ensure you have Keras installed correctly, run the above code and comment onthe quality of the fit you observe. NOTE: I was unable to run the code within an RMarkdown cell, but this may be due to a system configuration issue.<span></span></a></li>
<li class="chapter" data-level="10.4.2" data-path="stat-45207520---homework-4-spring-2022-due-april-25-2022.html"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-modify-the-code-in-an-attempt-to-improve-the-fit.-specifically-study-the-effects-as-well-as-interactions-of"><i class="fa fa-check"></i><b>10.4.2</b> b. Modify the code in an attempt to improve the fit. Specifically, study the effects (as well as interactions) of:<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html"><i class="fa fa-check"></i><b>11</b> Applied Stats Model II Lecture Note<span></span></a>
<ul>
<li class="chapter" data-level="11.1" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#list-of-questions"><i class="fa fa-check"></i><b>11.1</b> List of Questions:<span></span></a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#hw1"><i class="fa fa-check"></i><b>11.1.1</b> HW1<span></span></a></li>
<li class="chapter" data-level="11.1.2" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#hw2"><i class="fa fa-check"></i><b>11.1.2</b> HW2<span></span></a></li>
<li class="chapter" data-level="11.1.3" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#midterm"><i class="fa fa-check"></i><b>11.1.3</b> Midterm<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#class-content-overview"><i class="fa fa-check"></i><b>11.2</b> Class content overview:<span></span></a></li>
<li class="chapter" data-level="11.3" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glm-categoricaldata_sp2022"><i class="fa fa-check"></i><b>11.3</b> GLM-CategoricalData_SP2022<span></span></a></li>
<li class="chapter" data-level="11.4" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glm-countdata_sp2022"><i class="fa fa-check"></i><b>11.4</b> GLM-CountData_SP2022<span></span></a></li>
<li class="chapter" data-level="11.5" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#glms_advancedtopics_sp2022"><i class="fa fa-check"></i><b>11.5</b> GLMs_AdvancedTopics_SP2022<span></span></a></li>
<li class="chapter" data-level="11.6" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#mm-randomeffects_spring2022"><i class="fa fa-check"></i><b>11.6</b> MM-RandomEffects_Spring2022<span></span></a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="applied-stats-model-ii-lecture-note.html"><a href="applied-stats-model-ii-lecture-note.html#hw4-repeated-measure-time-and-space-dependence."><i class="fa fa-check"></i><b>11.6.1</b> HW4: Repeated measure, time and space dependence.<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html"><i class="fa fa-check"></i><b>12</b> Experimental Data Analysis<span></span></a>
<ul>
<li class="chapter" data-level="12.1" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#process-macro"><i class="fa fa-check"></i><b>12.1</b> PROCESS Macro<span></span></a></li>
<li class="chapter" data-level="12.2" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#data-cleaning"><i class="fa fa-check"></i><b>12.2</b> Data cleaning<span></span></a></li>
<li class="chapter" data-level="12.3" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#mediation-analysis"><i class="fa fa-check"></i><b>12.3</b> Mediation analysis<span></span></a></li>
<li class="chapter" data-level="12.4" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#adding-more-controls"><i class="fa fa-check"></i><b>12.4</b> Adding more controls<span></span></a></li>
<li class="chapter" data-level="12.5" data-path="experimental-data-analysis.html"><a href="experimental-data-analysis.html#efa-and-cfa-analysis-measurement-analysis"><i class="fa fa-check"></i><b>12.5</b> EFA And CFA Analysis / Measurement analysis<span></span></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Frank’s second book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="stat-45207520---homework-4-spring-2022-due-april-25-2022" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> STAT 4520/7520 - Homework 4 Spring 2022 Due: April 25, 2022<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#stat-45207520---homework-4-spring-2022-due-april-25-2022" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="section-2" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> 1)<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#section-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The BodyWeight dataset in the nlme package contains data on the body weights of rats measured over 64 days. The body weights of the rats (in grams) are measured on day 1 and every seven days thereafter until day 64, with an extra measurement on day 44. The experiment started several weeks before “day 1.” There are three groups of rats, each on a different diet.
It contains the variables:
• weight: The body weight of the rat in grams.
• Time: The time at which the measurement is made in number of days.
• Rat: The rat whose weight is measured.
• Diet: A factor with levels 1 to 3 indicating the diet that the rat receives.
The data can be loaded with the following command.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(BodyWeight,<span class="at">package =</span> <span class="st">&quot;nlme&quot;</span>)</span></code></pre></div>
<div id="a.-make-a-plot-of-weight-vs-time-for-the-data-with-rat-specific-lines-to-show-the-subject-specific-trajectory.-describe-your-findings.-7510-only-further-color-the-lines-differently-for-the-different-diets.-do-you-notice-anything-further" class="section level3 hasAnchor" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> a. Make a plot of weight vs Time for the data with rat specific lines to show the subject specific trajectory. Describe your findings. (7510 only) Further, color the lines differently for the different diets. Do you notice anything further?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-make-a-plot-of-weight-vs-time-for-the-data-with-rat-specific-lines-to-show-the-subject-specific-trajectory.-describe-your-findings.-7510-only-further-color-the-lines-differently-for-the-different-diets.-do-you-notice-anything-further" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#S7</span></span>
<span id="cb3-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(BodyWeight, <span class="fu">aes</span>(<span class="at">x=</span>Time,<span class="at">y=</span>weight))<span class="sc">+</span></span>
<span id="cb7-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>()<span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Rat) </span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># color the lines differently for different diet. </span></span>
<span id="cb8-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb8-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(BodyWeight, <span class="fu">aes</span>(<span class="at">x=</span>Time,<span class="at">y=</span>weight, <span class="at">color =</span> Diet))<span class="sc">+</span></span>
<span id="cb8-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>()<span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>Rat) </span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="b.-use-lm-to-regress-the-weight-onto-the-time.-what-is-the-slope-and-intercept-of-this-model-is-the-slope-significant" class="section level3 hasAnchor" number="10.1.2">
<h3><span class="header-section-number">10.1.2</span> b. Use lm() to regress the weight onto the Time. What is the slope and intercept of this model? Is the slope significant?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-use-lm-to-regress-the-weight-onto-the-time.-what-is-the-slope-and-intercept-of-this-model-is-the-slope-significant" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb9-1" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> Time, BodyWeight)</span>
<span id="cb9-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ Time, data = BodyWeight)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -157.32 -119.54  -25.42  125.75  225.68 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 364.8359    19.0841   19.12   &lt;2e-16 ***
## Time          0.5857     0.4921    1.19    0.236    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 127 on 174 degrees of freedom
## Multiple R-squared:  0.008074,   Adjusted R-squared:  0.002373 
## F-statistic: 1.416 on 1 and 174 DF,  p-value: 0.2356</code></pre>
<p>The slope is 0.59, the intercept is 365. It means the average weight at the begining is 365.Every unit of increase in time increases the weight by 0.59.
However, the slope is not significant.</p>
</div>
<div id="c.-use-the-lmlist-function-to-fit-a-linear-regression-model-that-describes-how-weight-varies-with-days-for-each-individual-rat.-how-do-the-slopes-and-intercepts-vary-do-you-notice-any-patterns-with-respect-to-diets" class="section level3 hasAnchor" number="10.1.3">
<h3><span class="header-section-number">10.1.3</span> c. Use the lmList function to fit a linear regression model that describes how weight varies with days for each individual rat. How do the slopes and intercepts vary? Do you notice any patterns with respect to diets?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-use-the-lmlist-function-to-fit-a-linear-regression-model-that-describes-how-weight-varies-with-days-for-each-individual-rat.-how-do-the-slopes-and-intercepts-vary-do-you-notice-any-patterns-with-respect-to-diets" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#how is c diff from d??? random intercept model vs. fixed effect here?</span></span>
<span id="cb11-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># how is lmList (fit a series simple regression within the group) vs. lmer diff</span></span>
<span id="cb11-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb13-1" aria-hidden="true" tabindex="-1"></a>ml <span class="ot">&lt;-</span> <span class="fu">lmList</span>(weight <span class="sc">~</span> <span class="fu">I</span>(Time<span class="dv">-1</span>) <span class="sc">|</span> Rat, BodyWeight)</span>
<span id="cb13-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(ml,coef)[,<span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>] <span class="sc">|&gt;</span> <span class="fu">as.matrix</span>()</span></code></pre></div>
<pre><code>##                      2           3           4           1           8
## (Intercept) 226.884778 247.2276043 255.8208779 245.3256606 252.1534833
## I(Time - 1)   0.330356   0.3980345   0.3295261   0.4844071   0.4086919
##                       5           6           7          11          9
## (Intercept) 256.2473029 264.3630487 268.0675693 443.0196549 407.925879
## I(Time - 1)   0.4058091   0.3184538   0.2018345   0.3625246   1.010657
##                     10        12          13          15          14
## (Intercept) 409.080542 553.10439 463.0154619 524.1315571 526.0279100
## I(Time - 1)   1.341101   1.14763   0.9185193   0.4931644   0.3147849
##                      16
## (Intercept) 504.3502948
## I(Time - 1)   0.9054379</code></pre>
<p>The intercepts and slopes vary a lot across the rats.
Only Diet 2 (Rat 9-12) seems to have a positive slope.</p>
</div>
<div id="d.-fit-a-random-intercept-model-to-account-for-the-different-weights-of-each-individual-rat-and-continue-to-use-time-as-a-fixed-effect.-answer-the-following" class="section level3 hasAnchor" number="10.1.4">
<h3><span class="header-section-number">10.1.4</span> d. Fit a random intercept model to account for the different weights of each individual rat and continue to use Time as a fixed effect. Answer the following:<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#d.-fit-a-random-intercept-model-to-account-for-the-different-weights-of-each-individual-rat-and-continue-to-use-time-as-a-fixed-effect.-answer-the-following" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>• What proportion of the variation is explained by Rat?
• Interpret the fixed effect intercept and comment on it’s value in the context of the variance component
for rat.
• Test for significance of the Time effect. What do you find? Is the conclusion different from part b?</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;lmerTest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     lmer</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     step</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb19-1" aria-hidden="true" tabindex="-1"></a>BodyWeight<span class="sc">$</span>Time_s <span class="ot">&lt;-</span> BodyWeight<span class="sc">$</span>Time<span class="dv">-1</span></span>
<span id="cb19-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb19-2" aria-hidden="true" tabindex="-1"></a>ml_intercept <span class="ot">&lt;-</span> <span class="fu">lmer</span>(weight <span class="sc">~</span> Time_s <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span> Rat), <span class="at">data =</span> BodyWeight)</span>
<span id="cb19-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ml_intercept)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: weight ~ Time_s + (1 | Rat)
##    Data: BodyWeight
## 
## REML criterion at convergence: 1360.3
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5029 -0.5458 -0.0394  0.5608  3.1139 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Rat      (Intercept) 16940.80 130.157 
##  Residual                66.85   8.176 
## Number of obs: 176, groups:  Rat, 16
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept) 365.42163   32.56138  15.03013   11.22 1.05e-08 ***
## Time_s        0.58568    0.03168 159.00000   18.49  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##        (Intr)
## Time_s -0.032</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? why it says null for the Rat?</span></span></code></pre></div>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="dv">19640</span><span class="sc">/</span> (<span class="dv">19640</span> <span class="sc">+</span> <span class="fl">66.85</span>)</span></code></pre></div>
<pre><code>## [1] 0.9966078</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">19640</span>)</span></code></pre></div>
<pre><code>## [1] 140.1428</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(ml_intercept, <span class="at">method=</span><span class="st">&quot;boot&quot;</span>, <span class="at">oldNames =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Computing bootstrap confidence intervals ...</code></pre>
<pre><code>##                          2.5 %      97.5 %
## sd_(Intercept)|Rat  79.6436591 178.6157691
## sigma                7.3076618   9.2588507
## (Intercept)        292.8748923 429.2448963
## Time_s               0.5197526   0.6519881</code></pre>
<p>The % of variance explained by the rats is 99%
The fixed effect is 365 or the average weight of the rat is 365 in the sample. However, the random effect standard deviation is 140 or almost half of the body weight.
The Time effect is significant at 99% confidence level. The boostrap tests show no 0 is contained in the interval.</p>
</div>
<div id="e.-obtain-the-blups-for-the-rats-and-list-who-is-the-most-heavy." class="section level3 hasAnchor" number="10.1.5">
<h3><span class="header-section-number">10.1.5</span> e. Obtain the BLUPs for the rats and list who is the most heavy.<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#e.-obtain-the-blups-for-the-rats-and-list-who-is-the-most-heavy." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the blup</span></span>
<span id="cb29-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(ml_intercept)</span></code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
## 242.0738 246.1736 250.2734 254.3732 258.4730 262.5727 266.6725 267.2582 
##        9       10       11       12       13       14       15       16 
## 270.7723 274.8721 278.9719 218.6277 222.7275 226.8273 230.9270 235.0268 
##       17       18       19       20       21       22       23       24 
## 239.1266 243.2264 243.8121 247.3262 251.4260 255.5257 241.1651 245.2649 
##       25       26       27       28       29       30       31       32 
## 249.3646 253.4644 257.5642 261.6640 265.7638 266.3494 269.8635 273.9633 
##       33       34       35       36       37       38       39       40 
## 278.0631 247.5264 251.6262 255.7260 259.8258 263.9256 268.0253 272.1251 
##       41       42       43       44       45       46       47       48 
## 272.7108 276.2249 280.3247 284.4245 250.4345 254.5343 258.6340 262.7338 
##       49       50       51       52       53       54       55       56 
## 266.8336 270.9334 275.0332 275.6189 279.1330 283.2327 287.3325 255.7053 
##       57       58       59       60       61       62       63       64 
## 259.8051 263.9049 268.0047 272.1044 276.2042 280.3040 280.8897 284.4038 
##       65       66       67       68       69       70       71       72 
## 288.5036 292.6034 255.6144 259.7142 263.8140 267.9138 272.0136 276.1133 
##       73       74       75       76       77       78       79       80 
## 280.2131 280.7988 284.3129 288.4127 292.5125 246.4359 250.5357 254.6355 
##       81       82       83       84       85       86       87       88 
## 258.7353 262.8350 266.9348 271.0346 271.6203 275.1344 279.2342 283.3340 
##       89       90       91       92       93       94       95       96 
## 421.7366 425.8364 429.9362 434.0360 438.1358 442.2356 446.3353 446.9210 
##       97       98       99      100      101      102      103      104 
## 450.4351 454.5349 458.6347 433.6415 437.7413 441.8410 445.9408 450.0406 
##      105      106      107      108      109      110      111      112 
## 454.1404 458.2402 458.8259 462.3400 466.4397 470.5395 435.7316 439.8314 
##      113      114      115      116      117      118      119      120 
## 443.9312 448.0310 452.1308 456.2305 460.3303 460.9160 464.4301 468.5299 
##      121      122      123      124      125      126      127      128 
## 472.6297 571.3193 575.4191 579.5189 583.6187 587.7185 591.8183 595.9180 
##      129      130      131      132      133      134      135      136 
## 596.5037 600.0178 604.1176 608.2174 473.8089 477.9087 482.0084 486.1082 
##      137      138      139      140      141      142      143      144 
## 490.2080 494.3078 498.4076 498.9933 502.5074 506.6071 510.7069 517.1570 
##      145      146      147      148      149      150      151      152 
## 521.2567 525.3565 529.4563 533.5561 537.6559 541.7557 542.3413 545.8554 
##      153      154      155      156      157      158      159      160 
## 549.9552 554.0550 521.0647 525.1644 529.2642 533.3640 537.4638 541.5636 
##      161      162      163      164      165      166      167      168 
## 545.6633 546.2490 549.7631 553.8629 557.9627 514.7033 518.8031 522.9029 
##      169      170      171      172      173      174      175      176 
## 527.0026 531.1024 535.2022 539.3020 539.8877 543.4018 547.5016 551.6013</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">predict</span>(ml_intercept))</span></code></pre></div>
<pre><code>## [1] 608.2174</code></pre>
<p>The rat 132 is heavist with a weight of 608.</p>
</div>
<div id="f.-fit-a-mixed-effects-model-that-describes-how-the-weight-varies-linearly-with-time-and-allows-for-random-variation-in-the-intercepts-and-slopes-of-the-rats.-then-do-the-following" class="section level3 hasAnchor" number="10.1.6">
<h3><span class="header-section-number">10.1.6</span> f. Fit a mixed effects model that describes how the weight varies linearly with time and allows for random variation in the intercepts and slopes of the rats. Then do the following:<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#f.-fit-a-mixed-effects-model-that-describes-how-the-weight-varies-linearly-with-time-and-allows-for-random-variation-in-the-intercepts-and-slopes-of-the-rats.-then-do-the-following" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Note: Convergence of this model may be an issue. You can use the argument
control=lmerControl(optimizer=“Nelder_Mead”) in lmer() to use a different optimizer.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? why need a diff optimizer to converge? what&#39;s diff?</span></span>
<span id="cb33-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb33-2" aria-hidden="true" tabindex="-1"></a>ml_mix <span class="ot">&lt;-</span> <span class="fu">lmer</span>(weight <span class="sc">~</span> Time_s <span class="sc">+</span> (Time_s<span class="sc">|</span> Rat), <span class="at">data =</span> BodyWeight, <span class="at">control=</span><span class="fu">lmerControl</span>(<span class="at">optimizer=</span><span class="st">&quot;Nelder_Mead&quot;</span>))</span>
<span id="cb33-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ml_mix)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: weight ~ Time_s + (Time_s | Rat)
##    Data: BodyWeight
## Control: lmerControl(optimizer = &quot;Nelder_Mead&quot;)
## 
## REML criterion at convergence: 1208.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.2658 -0.4256  0.0711  0.5871  2.7485 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr
##  Rat      (Intercept) 15246.84 123.4781     
##           Time_s          0.12   0.3463 0.56
##  Residual                19.75   4.4436     
## Number of obs: 176, groups:  Rat, 16
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept) 365.42163   30.87642  15.00001  11.835 5.22e-09 ***
## Time_s        0.58568    0.08828  15.00001   6.634 7.95e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##        (Intr)
## Time_s 0.550</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(ml_mix, <span class="at">method=</span><span class="st">&quot;boot&quot;</span>, <span class="at">oldNames =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Computing bootstrap confidence intervals ...</code></pre>
<pre><code>## 
## 2 warning(s): Model failed to converge with max|grad| = 0.00376307 (tol = 0.002, component 1) (and others)</code></pre>
<pre><code>##                                  2.5 %      97.5 %
## sd_(Intercept)|Rat          82.8559068 171.3197209
## cor_Time_s.(Intercept)|Rat   0.1279669   0.8435561
## sd_Time_s|Rat                0.2129623   0.4749755
## sigma                        3.9224008   4.9165953
## (Intercept)                311.7805567 417.4600562
## Time_s                       0.3832744   0.7455524</code></pre>
<p>• Compute confidence intervals for the random effects, do the slopes and intercepts seem to vary between subjects?</p>
<p>The slopes and intercepts are both significant at 95% confidence level. Thus they both vary between subjects.</p>
<p>• Interpret the standard deviation of the slope random effect in the context of the fixed effect slope estimate. Does it seem large or small?</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.3463</span> <span class="sc">/</span> <span class="fl">0.58568</span></span></code></pre></div>
<pre><code>## [1] 0.5912785</code></pre>
<p>The random effect of the slope is about 60% of the fixed effect, thus it seems large.</p>
<p>• Test for significance of the Time fixed effect again, and compare the result to parts b and d.</p>
<p>The time fixed effect is significant with an estimate of 0.59 and the t value of 6.63.
In b is: the estimate is the same of 0.59 but it was not significant with the time value of 1.19.
In d is: the estimate is the same of 0.59 but it was more significant at the t value of 18.49<br />
In summary, the (f) result fits the data better. In b without considering the rat’s random effect, it contains too much noise. In d, without the random slope, too much variations were attributed to the intercept.</p>
</div>
<div id="g.-obtain-the-blups-for-the-model-in-part-f.-which-rat-has-the-fastest-rate-of-increase-the-slowest" class="section level3 hasAnchor" number="10.1.7">
<h3><span class="header-section-number">10.1.7</span> g. Obtain the BLUPs for the model in part f. Which rat has the fastest rate of increase? The slowest?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#g.-obtain-the-blups-for-the-model-in-part-f.-which-rat-has-the-fastest-rate-of-increase-the-slowest" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Compute the values of their specific slopes using the fixed effect estimate for time and their BLUP value. Print out the data for these two rats and comment on their minimum and maximum weights over the course of the study.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#predict(ml_mix)</span></span>
<span id="cb41-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(ml_mix) </span></code></pre></div>
<pre><code>## $Rat
##    (Intercept)     Time_s
## 2   -138.54609 -0.2545799
## 3   -118.14461 -0.1887413
## 4   -109.71085 -0.2524615
## 1   -119.87610 -0.1075102
## 8   -113.21541 -0.1782011
## 5   -109.14111 -0.1805082
## 6   -101.21900 -0.2620429
## 7    -97.74852 -0.3716064
## 11    76.90824 -0.2025888
## 9     43.16497  0.4048760
## 10    44.94282  0.7164946
## 12   188.10531  0.5485514
## 13    97.89066  0.3235416
## 15   157.98977 -0.0713060
## 14   159.54107 -0.2392710
## 16   139.05884  0.3153536
## 
## with conditional variances for &quot;Rat&quot;</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ml_mix) <span class="co">#need to combine with the gloabl slope of 0.58 to get the actual slope. </span></span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: weight ~ Time_s + (Time_s | Rat)
##    Data: BodyWeight
## Control: lmerControl(optimizer = &quot;Nelder_Mead&quot;)
## 
## REML criterion at convergence: 1208.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.2658 -0.4256  0.0711  0.5871  2.7485 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr
##  Rat      (Intercept) 15246.84 123.4781     
##           Time_s          0.12   0.3463 0.56
##  Residual                19.75   4.4436     
## Number of obs: 176, groups:  Rat, 16
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept) 365.42163   30.87642  15.00001  11.835 5.22e-09 ***
## Time_s        0.58568    0.08828  15.00001   6.634 7.95e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##        (Intr)
## Time_s 0.550</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#!!! how to seperate the effects for time growth?</span></span></code></pre></div>
</div>
<div id="h.-add-the-fixed-diet-variable-to-the-model-in-the-form-of-an-interaction-with-time.-does-the-diet-effect-weight-is-this-effect-different-at-different-times" class="section level3 hasAnchor" number="10.1.8">
<h3><span class="header-section-number">10.1.8</span> h. Add the (fixed) diet variable to the model in the form of an interaction with time. Does the diet effect weight? Is this effect different at different times?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#h.-add-the-fixed-diet-variable-to-the-model-in-the-form-of-an-interaction-with-time.-does-the-diet-effect-weight-is-this-effect-different-at-different-times" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb46-1" aria-hidden="true" tabindex="-1"></a>ml_mix_int <span class="ot">&lt;-</span> <span class="fu">lmer</span>(weight <span class="sc">~</span> Time_s<span class="sc">*</span>Diet <span class="sc">+</span> (Time_s<span class="sc">|</span> Rat), <span class="at">data =</span> BodyWeight, <span class="at">control=</span><span class="fu">lmerControl</span>(<span class="at">optimizer=</span><span class="st">&quot;Nelder_Mead&quot;</span>))</span>
<span id="cb46-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co">#allow rat specific slope to vary. if I combine with another, no need to do both. The question only asks for two fixed effect interaction.</span></span>
<span id="cb46-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Time_s and Rat are interacted. depends on the rat. </span></span></code></pre></div>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ml_mix_int)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: weight ~ Time_s * Diet + (Time_s | Rat)
##    Data: BodyWeight
## Control: lmerControl(optimizer = &quot;Nelder_Mead&quot;)
## 
## REML criterion at convergence: 1151.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.2556 -0.4220  0.0823  0.5993  2.7899 
## 
## Random effects:
##  Groups   Name        Variance  Std.Dev. Corr 
##  Rat      (Intercept) 1.362e+03 36.9028       
##           Time_s      6.171e-02  0.2484  -0.14
##  Residual             1.975e+01  4.4436       
## Number of obs: 176, groups:  Rat, 16
## 
## Fixed effects:
##               Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)  252.01129   13.07975  13.00001  19.267 6.08e-11 ***
## Time_s         0.35964    0.09114  12.99997   3.946  0.00167 ** 
## Diet2        201.27133   22.65479  13.00001   8.884 6.97e-07 ***
## Diet3        252.37002   22.65479  13.00001  11.140 5.07e-08 ***
## Time_s:Diet2   0.60584    0.15786  12.99997   3.838  0.00205 ** 
## Time_s:Diet3   0.29834    0.15786  12.99997   1.890  0.08127 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) Time_s Diet2  Diet3  Tm_:D2
## Time_s      -0.153                            
## Diet2       -0.577  0.088                     
## Diet3       -0.577  0.088  0.333              
## Time_s:Dit2  0.088 -0.577 -0.153 -0.051       
## Time_s:Dit3  0.088 -0.577 -0.051 -0.153  0.333</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#!!!do I need to interact when the Rat is the predictors for random slopes?</span></span></code></pre></div>
<p>The diet affects the wieght. Both Diet2 and Diet3 have positive and significant fixed efect coefficients. Thus, they are more effective than Diet1 in gaining weight.
The Diet2 interact with the Time. As the time increases, the Diet2 is more effective in gaining the weight.</p>
</div>
</div>
<div id="time-series" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> 2) Time Series<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#time-series" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall the Johnson &amp; Johnson data from course notes, which contains the quarterly earnings per Johnson &amp; Johnson share from 1960 to 1980. We can read this in and convert it to a more familiar dataframe format with the following code.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Why read as vector in the dataframe -&gt; final step add the trend back. Make the format as.vector -&gt; strip out the meta data. </span></span>
<span id="cb50-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(JohnsonJohnson)</span>
<span id="cb50-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb50-3" aria-hidden="true" tabindex="-1"></a>JJ <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">EPS=</span> <span class="fu">as.vector</span>(JohnsonJohnson),</span>
<span id="cb50-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="at">Time=</span> <span class="fu">as.vector</span>(<span class="fu">time</span>(JohnsonJohnson))) <span class="co">#matrix of year and quarter if without the vector. 1960 will be q1 -&gt; 1960.25 vs. four columns for differetn period of the year</span></span></code></pre></div>
<div id="a.-create-a-variable-containing-the-log-base-10-of-the-eps-then-use-lm-to-regress-it-onto-time.-store-the-residuals-of-this-regression-in-another-variable-in-jj.-make-a-plot-of-the-residuals-vs-time-and-describe-your-findings." class="section level3 hasAnchor" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> a. Create a variable containing the log (base 10) of the EPS, then use lm() to regress it onto Time. Store the residuals of this regression in another variable in JJ. Make a plot of the residuals vs Time and describe your findings.<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-create-a-variable-containing-the-log-base-10-of-the-eps-then-use-lm-to-regress-it-onto-time.-store-the-residuals-of-this-regression-in-another-variable-in-jj.-make-a-plot-of-the-residuals-vs-time-and-describe-your-findings." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb51-1" aria-hidden="true" tabindex="-1"></a>JJ<span class="sc">$</span>EPS_lg <span class="ot">=</span> <span class="fu">log</span>(JJ<span class="sc">$</span>EPS)</span></code></pre></div>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb52-1" aria-hidden="true" tabindex="-1"></a>lm_model_ts <span class="ot">&lt;-</span> <span class="fu">lm</span>(EPS_lg <span class="sc">~</span> Time, JJ)</span>
<span id="cb52-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model_ts)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = EPS_lg ~ Time, data = JJ)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.38309 -0.08569  0.00297  0.09984  0.38016 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.275e+02  5.623e+00  -58.25   &lt;2e-16 ***
## Time         1.668e-01  2.854e-03   58.45   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1585 on 82 degrees of freedom
## Multiple R-squared:  0.9766, Adjusted R-squared:  0.9763 
## F-statistic:  3416 on 1 and 82 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb54-1" aria-hidden="true" tabindex="-1"></a>lm_ts_resids <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(EPS_lg <span class="sc">~</span> Time, JJ))</span></code></pre></div>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(lm_ts_resids)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#weakly dependent process: The correlation is with which period? why does it keep decreasing? since it is further away?</span></span></code></pre></div>
<p>There seems to be a seasonal cycle of every 4th periods.</p>
</div>
<div id="b.-run-the-detrended-values-through-auto.arima-to-find-a-good-arma-model.-note-that-you-may-want-to-use-the-additional-argument-stepwise-false-to-allow-auto.arima-to-conduct-a-full-grid-search.-what-model-was-found" class="section level3 hasAnchor" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> b. Run the detrended values through auto.arima() to find a good ARMA model. Note that you may want to use the additional argument stepwise = FALSE to allow auto.arima() to conduct a full grid search. What model was found?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-run-the-detrended-values-through-auto.arima-to-find-a-good-arma-model.-note-that-you-may-want-to-use-the-additional-argument-stepwise-false-to-allow-auto.arima-to-conduct-a-full-grid-search.-what-model-was-found" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#arima(lm_ts_resids, order = c(1, 0, 1))</span></span>
<span id="cb57-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(lm_ts_resids,<span class="at">stepwise =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Series: lm_ts_resids 
## ARIMA(4,0,0) with zero mean 
## 
## Coefficients:
##          ar1     ar2      ar3     ar4
##       0.0454  0.0386  -0.0826  0.8525
## s.e.  0.0601  0.0555   0.0613  0.0582
## 
## sigma^2 = 0.008767:  log likelihood = 79.07
## AIC=-148.13   AICc=-147.36   BIC=-135.98</code></pre>
<p>The model is ARIMA(4,0,0)</p>
</div>
<div id="c.-use-the-best-model-to-forecast-the-detrended-relationship-2-years-8-quarters-ahead.-make-a-plot-of-the-result-and-comment-on-how-reasonable-your-predictions-look." class="section level3 hasAnchor" number="10.2.3">
<h3><span class="header-section-number">10.2.3</span> c. Use the best model to forecast the detrended relationship 2 years (8 quarters) ahead. Make a plot of the result and comment on how reasonable your predictions look.<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-use-the-best-model-to-forecast-the-detrended-relationship-2-years-8-quarters-ahead.-make-a-plot-of-the-result-and-comment-on-how-reasonable-your-predictions-look." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? why is the JJ not need time() function?</span></span>
<span id="cb61-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb61-2" aria-hidden="true" tabindex="-1"></a>dt <span class="ot">&lt;-</span> <span class="fu">diff</span>(JJ<span class="sc">$</span>Time)[<span class="dv">1</span>] <span class="co"># diff func gives the difference of adjacnet value. diff 1,2,3 -&gt; 1,1. take the first element.  </span></span>
<span id="cb61-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb61-3" aria-hidden="true" tabindex="-1"></a>time_steps <span class="ot">&lt;-</span> <span class="fu">max</span>(JJ<span class="sc">$</span>Time) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)<span class="sc">*</span>dt <span class="co"># Time points we will predict at</span></span>
<span id="cb61-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb61-4" aria-hidden="true" tabindex="-1"></a>ARMA_p1q1 <span class="ot">&lt;-</span> <span class="fu">arima</span>(lm_ts_resids, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">0</span>,<span class="dv">0</span>)) <span class="co">#!!! need to be on the residual. NOT in the JJ. </span></span>
<span id="cb61-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb61-5" aria-hidden="true" tabindex="-1"></a>ARMA_p1q1_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>( ARMA_p1q1, <span class="at">n.ahead=</span><span class="dv">8</span> )<span class="sc">$</span>pred</span>
<span id="cb61-6"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(JJ<span class="sc">$</span>Time,lm_ts_resids,<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">1970</span>, <span class="dv">1990</span>),<span class="at">type =</span> <span class="st">&#39;l&#39;</span>) <span class="co">#How to specify exactly how many periods here? the Time unit is off??? #no plot.ts stripe out the time function -&gt; only if passing time-seris object. generic func may recognize it is time series. </span></span>
<span id="cb61-7"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> time_steps, <span class="at">y =</span> ARMA_p1q1_pred, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb62-1" aria-hidden="true" tabindex="-1"></a>ARMA_p1q1_pred</span></code></pre></div>
<pre><code>## Time Series:
## Start = 85 
## End = 92 
## Frequency = 1 
## [1]  0.05160930 -0.06661295  0.01437544 -0.33250908  0.03520765 -0.06894246
## [7]  0.03825592 -0.28704069</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#time_steps</span></span></code></pre></div>
<p>The prediction seems to reflect the seasonal fluctuation and a reasonable average, thus the prediction looks good.</p>
</div>
<div id="d.-use-the-linear-model-from-part-a-to-predict-the-trend-for-the-next-8-quarters-add-the-result-to-that-of-part-c-transform-back-to-the-original-scale-and-plot-the-forecast-along-with-the-original-data.-does-the-forecast-seem-reasonable" class="section level3 hasAnchor" number="10.2.4">
<h3><span class="header-section-number">10.2.4</span> d. Use the linear model from part a to predict the trend for the next 8 quarters, add the result to that of part c, transform back to the original scale, and plot the forecast along with the original data. Does the forecast seem reasonable?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#d.-use-the-linear-model-from-part-a-to-predict-the-trend-for-the-next-8-quarters-add-the-result-to-that-of-part-c-transform-back-to-the-original-scale-and-plot-the-forecast-along-with-the-original-data.-does-the-forecast-seem-reasonable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb65-1" aria-hidden="true" tabindex="-1"></a>dt <span class="ot">&lt;-</span> <span class="fu">diff</span>(JJ<span class="sc">$</span>Time)[<span class="dv">1</span>] <span class="co"># differences between time points ??? What&#39;s the diff?</span></span>
<span id="cb65-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb65-2" aria-hidden="true" tabindex="-1"></a>time_steps <span class="ot">&lt;-</span> <span class="fu">max</span>(JJ<span class="sc">$</span>Time) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)<span class="sc">*</span>dt <span class="co"># Time points we will predict at</span></span>
<span id="cb65-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co">#plot.ts(JJ[,3],xlim = c(1970, 1990)) #How to specify exactly how many periods here? the Time unit is off???</span></span>
<span id="cb65-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="co">#lines(x = time_steps, y = ARMA_lm_pred, col=&quot;red&quot;)</span></span></code></pre></div>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb66-1" aria-hidden="true" tabindex="-1"></a>lm_model_ts_resid <span class="ot">&lt;-</span> <span class="fu">lm</span>(lm_ts_resids <span class="sc">~</span> Time, JJ)</span>
<span id="cb66-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb66-2" aria-hidden="true" tabindex="-1"></a>ARMA_lm_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_model_ts_resid,<span class="at">n.ahead=</span><span class="dv">8</span>) <span class="co">#??? cannot predict the time series?</span></span>
<span id="cb66-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb66-5" aria-hidden="true" tabindex="-1"></a>ARMA_lm_pred_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ARMA_lm_pred)</span>
<span id="cb66-6"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb66-6" aria-hidden="true" tabindex="-1"></a>ARMA_lm_pred_df[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>),] <span class="co">#change it to the first 8 periods of prediction</span></span></code></pre></div>
<pre><code>## [1] -2.416911e-17 -2.329483e-17 -2.242055e-17 -2.154627e-17 -2.067199e-17
## [6] -1.979771e-17 -1.892343e-17 -1.804915e-17</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(JJ<span class="sc">$</span>Time,lm_ts_resids,<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">1970</span>, <span class="dv">1990</span>),<span class="at">type =</span> <span class="st">&#39;l&#39;</span>)</span>
<span id="cb68-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> time_steps, <span class="at">y =</span> ARMA_p1q1_pred, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb68-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> time_steps, <span class="at">y =</span> ARMA_lm_pred_df[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>),], <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>The forcast doesn’t seem reasonable from the linear model. it is essentially a flat line that doesn’t reflect the seasonality.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#S25 !!!</span></span>
<span id="cb69-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>); n <span class="ot">&lt;-</span> <span class="dv">2000</span>; eps_t <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">2</span>); <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb69-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-3" aria-hidden="true" tabindex="-1"></a>AR <span class="ot">&lt;-</span> MA <span class="ot">&lt;-</span> ARMA <span class="ot">&lt;-</span> <span class="fu">double</span>(n)</span>
<span id="cb69-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-4" aria-hidden="true" tabindex="-1"></a>AR[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="ot">&lt;-</span> MA[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="ot">&lt;-</span> ARMA[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb69-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">3</span><span class="sc">:</span>n) AR[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">c</span>(.<span class="dv">6</span>, .<span class="dv">2</span>) <span class="sc">*</span> AR[(i<span class="dv">-1</span>)<span class="sc">:</span>(i<span class="dv">-2</span>)]) <span class="sc">+</span> eps_t[i]</span>
<span id="cb69-6"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">3</span><span class="sc">:</span>n) MA[i] <span class="ot">&lt;-</span> eps_t[i] <span class="sc">+</span> .<span class="dv">8</span><span class="sc">*</span>eps_t[i<span class="dv">-1</span>]</span>
<span id="cb69-7"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">3</span><span class="sc">:</span>n) ARMA[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">c</span>(.<span class="dv">6</span>, .<span class="dv">2</span>) <span class="sc">*</span> AR[(i<span class="dv">-1</span>)<span class="sc">:</span>(i<span class="dv">-2</span>)]) <span class="sc">+</span> eps_t[i] <span class="sc">+</span> .<span class="dv">8</span><span class="sc">*</span>eps_t[i<span class="dv">-1</span>]</span>
<span id="cb69-8"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(AR,<span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">15</span>,<span class="dv">15</span>)); <span class="fu">lines</span>(MA, <span class="at">col=</span><span class="st">&quot;red&quot;</span>); <span class="fu">lines</span>(ARMA, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb69-9"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb69-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
</div>
</div>
<div id="spatial-point-process-analysis" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> 3) Spatial Point Process Analysis<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#spatial-point-process-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The mucosa datset in spatstat.data gives the locations of the centers of two types of cells in a cross-section of the gastric mucosa of a rat. For the purpose of this analysis, we will ignore the type of cell and focus on the locations of the cells only. The data can be loaded with the following command:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span></code></pre></div>
<pre><code>## Loading required package: spatstat.data</code></pre>
<pre><code>## Loading required package: spatstat.geom</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;spatstat.geom&#39;:
##   method     from
##   print.boxx cli</code></pre>
<pre><code>## spatstat.geom 2.4-0</code></pre>
<pre><code>## Loading required package: spatstat.random</code></pre>
<pre><code>## spatstat.random 2.2-0</code></pre>
<pre><code>## Loading required package: spatstat.core</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## 
## Attaching package: &#39;nlme&#39;</code></pre>
<pre><code>## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     BodyWeight</code></pre>
<pre><code>## The following object is masked from &#39;package:forecast&#39;:
## 
##     getResponse</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     lmList</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     collapse</code></pre>
<pre><code>## Loading required package: rpart</code></pre>
<pre><code>## spatstat.core 2.4-2</code></pre>
<pre><code>## Loading required package: spatstat.linnet</code></pre>
<pre><code>## spatstat.linnet 2.3-2</code></pre>
<pre><code>## 
## spatstat 2.3-4       (nickname: &#39;Watch this space&#39;) 
## For an introduction to spatstat, type &#39;beginner&#39;</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mucosa, <span class="at">package =</span> <span class="st">&quot;spatstat.data&quot;</span>)</span></code></pre></div>
<div id="a.-make-a-plot-of-the-point-pattern.-does-the-distribution-of-the-points-in-space-appear-to-be-homogeneous-poisson-process" class="section level3 hasAnchor" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> a. Make a plot of the point pattern. Does the distribution of the points in space appear to be homogeneous Poisson process?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-make-a-plot-of-the-point-pattern.-does-the-distribution-of-the-points-in-space-appear-to-be-homogeneous-poisson-process" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co">#S43</span></span>
<span id="cb90-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb90-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mucosa, <span class="at">main=</span>(<span class="st">&#39;mucosa&#39;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-33-1.png" width="672" />
It doesn’t appear to be homogeneous poisson since the distribution is more dense in the bottom of the plot in comparison with the top.</p>
</div>
<div id="b.-make-plots-of-gr-and-fr-and-comment-on-what-you-observe." class="section level3 hasAnchor" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> b. Make plots of G(r) and F(r) and comment on what you observe.<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-make-plots-of-gr-and-fr-and-comment-on-what-you-observe." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb91-1" aria-hidden="true" tabindex="-1"></a>GCSR <span class="ot">&lt;-</span> <span class="fu">envelope</span>(mucosa, Gest, <span class="at">verbose=</span><span class="cn">FALSE</span>) <span class="co">#??? how to judge if poisson? or all count poisson? just not homo?</span></span>
<span id="cb91-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb91-2" aria-hidden="true" tabindex="-1"></a>FCSR <span class="ot">&lt;-</span> <span class="fu">envelope</span>(mucosa, Fest, <span class="at">verbose=</span><span class="cn">FALSE</span>)</span>
<span id="cb91-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(GCSR); <span class="fu">plot</span>(FCSR)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-34-1.png" width="672" /><img src="bookdownproj_files/figure-html/unnamed-chunk-34-2.png" width="672" />
According to the plot, it is not a homogeneous poisson process as the black line is outside the boundary</p>
</div>
<div id="c.-fit-a-point-process-model-with-linear-terms-in-both-x-and-y.-are-there-any-significant-spatial-relationships" class="section level3 hasAnchor" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> c. Fit a point process model with linear terms in both x and y. Are there any significant spatial relationships?<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#c.-fit-a-point-process-model-with-linear-terms-in-both-x-and-y.-are-there-any-significant-spatial-relationships" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#S62 - what&#39;s the z, why is it a func of x and y??? what&#39;s the weight on the distance here?</span></span>
<span id="cb92-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="co">#ppm function to look for gradience -&gt; intensitivyt of point process. how many in diff grids. lower value of y has more.</span></span>
<span id="cb92-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb92-4" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mucosa)</span>
<span id="cb92-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb92-6"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb92-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(x, y, <span class="at">data=</span>dat) </span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ppm</span>(mucosa <span class="sc">~</span> x <span class="sc">+</span> y) <span class="co">#homogeneous poisson process , must have a point dataframe.note there is no DV. the first item is the dataset. not set as data = </span></span></code></pre></div>
<pre><code>## Nonstationary multitype Poisson process
## 
## Possible marks: &#39;ECL&#39; and &#39;other&#39;
## 
## Log intensity:  ~x + y
## 
## Fitted trend coefficients:
##  (Intercept)            x            y 
##  6.825371255 -0.007512035 -1.156055790 
## 
##                 Estimate       S.E.    CI95.lo    CI95.hi Ztest       Zval
## (Intercept)  6.825371255 0.08038734  6.6678150  6.9829275   *** 84.9060501
## x           -0.007512035 0.11152004 -0.2260873  0.2110632       -0.0673604
## y           -1.156055790 0.14068205 -1.4317875 -0.8803240   *** -8.2175075</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#??? why the y coefficient is negative. how to interpret?</span></span>
<span id="cb95-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="co">#pp.dists &lt;- cbind(dat$x, dat$y) |&gt; dist() |&gt; as.matrix()</span></span>
<span id="cb95-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="co">#pp.dists[1:3,1:3] #what&#39;s the distance here1:3!!! first three elements. </span></span>
<span id="cb95-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-6"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="co">#pp.dists.inv &lt;- 1/pp.dists</span></span>
<span id="cb95-7"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-7" aria-hidden="true" tabindex="-1"></a><span class="co">#diag(pp.dists.inv) &lt;- 0</span></span>
<span id="cb95-8"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-9"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb95-9" aria-hidden="true" tabindex="-1"></a><span class="co">#ape::Moran.I(dat$x, pp.dists.inv) #!!! what weight should be here? -&gt; ONLY if there are three dimensions for moran.</span></span></code></pre></div>
<p>There is significant spatial relationship here. The y is significant. the lower the y the denser the units per grid.</p>
</div>
</div>
<div id="loading-keras" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> 4) Loading Keras<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#loading-keras" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Below you will find a block of code that can be used to simulate some simple noisy nonlinear data, fit an
ANN to that data, and plot the fit.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Then, use the install_tensorflow() function to install TensorFlow. Note that on Windows you need a working installation of Anaconda.</span></span>
<span id="cb96-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co"># already install the anaconda version of tensorflow https://tensorflow.rstudio.com/installation/</span></span>
<span id="cb96-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="co">#library(tensorflow)</span></span>
<span id="cb96-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install_tensorflow()</span></span></code></pre></div>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tensorflow)</span>
<span id="cb97-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(keras)</span>
<span id="cb97-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb97-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(N, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">3</span>) <span class="co"># Build a Gompertz function with some noise</span></span>
<span id="cb97-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-5" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># ceiling parameter</span></span>
<span id="cb97-6"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-6" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="co"># horizontal shift parameter</span></span>
<span id="cb97-7"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-7" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="co"># growth rate parameter </span></span>
<span id="cb97-8"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-8" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> a<span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fu">exp</span>(b <span class="sc">-</span> c<span class="sc">*</span>x)) <span class="sc">+</span> <span class="fu">rnorm</span>(N, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span> a<span class="sc">/</span><span class="dv">10</span>)</span>
<span id="cb97-9"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y) <span class="co"># format data in a way model.fit() would like it</span></span>
<span id="cb97-10"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-10" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(x)</span>
<span id="cb97-11"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-11" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(y) <span class="co"># sequence along x for later prediction</span></span>
<span id="cb97-12"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-12" aria-hidden="true" tabindex="-1"></a>xnew <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">seq</span>(<span class="at">from=</span><span class="fu">min</span>(x), <span class="at">to=</span><span class="fu">max</span>(x), <span class="at">length.out=</span><span class="dv">1000</span>)) <span class="co"># Build and compile simple model</span></span>
<span id="cb97-13"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-13" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">keras_model_sequential</span>() <span class="sc">|&gt;</span></span>
<span id="cb97-14"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-14" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">32</span>, <span class="at">activation=</span><span class="st">&quot;relu&quot;</span>, <span class="at">input_shape=</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb97-15"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-15" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">16</span>, <span class="at">activation =</span> <span class="st">&quot;relu&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb97-16"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb97-16" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">1</span>, <span class="at">activation=</span><span class="st">&quot;linear&quot;</span>)</span></code></pre></div>
<pre><code>## Loaded Tensorflow version 2.8.0</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb99-1" aria-hidden="true" tabindex="-1"></a>model <span class="sc">|&gt;</span> <span class="fu">compile</span>(</span>
<span id="cb99-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="at">loss =</span> <span class="st">&quot;mse&quot;</span>,</span>
<span id="cb99-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="at">optimizer =</span> <span class="st">&quot;adam&quot;</span>,</span>
<span id="cb99-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb99-4" aria-hidden="true" tabindex="-1"></a><span class="at">metrics =</span> <span class="fu">list</span>(<span class="st">&quot;mean_absolute_error&quot;</span>)</span>
<span id="cb99-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb99-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb99-6"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb99-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model, get predictions, and display result.</span></span>
<span id="cb99-7"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb99-7" aria-hidden="true" tabindex="-1"></a>model <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Model: &quot;sequential&quot;
## ________________________________________________________________________________
##  Layer (type)                       Output Shape                    Param #     
## ================================================================================
##  dense_2 (Dense)                    (None, 32)                      64          
##                                                                                 
##  dense_1 (Dense)                    (None, 16)                      528         
##                                                                                 
##  dense (Dense)                      (None, 1)                       17          
##                                                                                 
## ================================================================================
## Total params: 609
## Trainable params: 609
## Non-trainable params: 0
## ________________________________________________________________________________</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Can change verbose &gt; 0 to see plots and text output as model trains</span></span>
<span id="cb101-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb101-2" aria-hidden="true" tabindex="-1"></a>model <span class="sc">|&gt;</span> <span class="fu">fit</span>(x, y, <span class="at">epochs =</span> <span class="dv">20</span>, <span class="at">verbose =</span> <span class="dv">0</span>)</span>
<span id="cb101-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb101-3" aria-hidden="true" tabindex="-1"></a>y_pred <span class="ot">=</span> model <span class="sc">|&gt;</span> <span class="fu">predict</span>(xnew)</span>
<span id="cb101-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y)</span>
<span id="cb101-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb101-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(xnew, y_pred, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>Complete the following:</p>
<div id="a.-mostly-as-an-exercise-to-ensure-you-have-keras-installed-correctly-run-the-above-code-and-comment-onthe-quality-of-the-fit-you-observe.-note-i-was-unable-to-run-the-code-within-an-rmarkdown-cell-but-this-may-be-due-to-a-system-configuration-issue." class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> a. Mostly as an exercise to ensure you have Keras installed correctly, run the above code and comment onthe quality of the fit you observe. NOTE: I was unable to run the code within an RMarkdown cell, but this may be due to a system configuration issue.<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#a.-mostly-as-an-exercise-to-ensure-you-have-keras-installed-correctly-run-the-above-code-and-comment-onthe-quality-of-the-fit-you-observe.-note-i-was-unable-to-run-the-code-within-an-rmarkdown-cell-but-this-may-be-due-to-a-system-configuration-issue." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The fit is not well. It fits the first part of linear relationship well but not the second part of non-linear relationship.</p>
</div>
<div id="b.-modify-the-code-in-an-attempt-to-improve-the-fit.-specifically-study-the-effects-as-well-as-interactions-of" class="section level3 hasAnchor" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> b. Modify the code in an attempt to improve the fit. Specifically, study the effects (as well as interactions) of:<a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#b.-modify-the-code-in-an-attempt-to-improve-the-fit.-specifically-study-the-effects-as-well-as-interactions-of" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>• Modifying how much data (N) we have.
• The complexity of the model.
• For how many epochs the model is trained.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tensorflow)</span>
<span id="cb102-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(keras)</span>
<span id="cb102-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb102-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(N, <span class="sc">-</span><span class="dv">2</span>, <span class="dv">3</span>) <span class="co"># Build a Gompertz function with some noise</span></span>
<span id="cb102-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-5" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># ceiling parameter</span></span>
<span id="cb102-6"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-6" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="co"># horizontal shift parameter</span></span>
<span id="cb102-7"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-7" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="co"># growth rate parameter </span></span>
<span id="cb102-8"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-8" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> a<span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fu">exp</span>(b <span class="sc">-</span> c<span class="sc">*</span>x)) <span class="sc">+</span> <span class="fu">rnorm</span>(N, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span> a<span class="sc">/</span><span class="dv">10</span>)</span>
<span id="cb102-9"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y) <span class="co"># format data in a way model.fit() would like it</span></span>
<span id="cb102-10"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-10" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(x)</span>
<span id="cb102-11"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-11" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(y) <span class="co"># sequence along x for later prediction</span></span>
<span id="cb102-12"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-12" aria-hidden="true" tabindex="-1"></a>xnew <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">seq</span>(<span class="at">from=</span><span class="fu">min</span>(x), <span class="at">to=</span><span class="fu">max</span>(x), <span class="at">length.out=</span><span class="dv">1000</span>)) <span class="co"># Build and compile simple model</span></span>
<span id="cb102-13"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-13" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">keras_model_sequential</span>() <span class="sc">|&gt;</span></span>
<span id="cb102-14"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-14" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">32</span>, <span class="at">activation=</span><span class="st">&quot;relu&quot;</span>, <span class="at">input_shape=</span><span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb102-15"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-15" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">16</span>, <span class="at">activation =</span> <span class="st">&quot;relu&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb102-16"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-16" aria-hidden="true" tabindex="-1"></a><span class="fu">layer_dense</span>(<span class="at">units=</span><span class="dv">1</span>, <span class="at">activation=</span><span class="st">&quot;linear&quot;</span>)</span>
<span id="cb102-17"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-17" aria-hidden="true" tabindex="-1"></a>model <span class="sc">|&gt;</span> <span class="fu">compile</span>(</span>
<span id="cb102-18"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-18" aria-hidden="true" tabindex="-1"></a><span class="at">loss =</span> <span class="st">&quot;mse&quot;</span>,</span>
<span id="cb102-19"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-19" aria-hidden="true" tabindex="-1"></a><span class="at">optimizer =</span> <span class="st">&quot;adam&quot;</span>,</span>
<span id="cb102-20"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-20" aria-hidden="true" tabindex="-1"></a><span class="at">metrics =</span> <span class="fu">list</span>(<span class="st">&quot;mean_absolute_error&quot;</span>)</span>
<span id="cb102-21"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb102-22"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model, get predictions, and display result.</span></span>
<span id="cb102-23"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb102-23" aria-hidden="true" tabindex="-1"></a>model <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>## Model: &quot;sequential_1&quot;
## ________________________________________________________________________________
##  Layer (type)                       Output Shape                    Param #     
## ================================================================================
##  dense_5 (Dense)                    (None, 32)                      64          
##                                                                                 
##  dense_4 (Dense)                    (None, 16)                      528         
##                                                                                 
##  dense_3 (Dense)                    (None, 1)                       17          
##                                                                                 
## ================================================================================
## Total params: 609
## Trainable params: 609
## Non-trainable params: 0
## ________________________________________________________________________________</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Can change verbose &gt; 0 to see plots and text output as model trains</span></span>
<span id="cb104-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb104-2" aria-hidden="true" tabindex="-1"></a>model <span class="sc">|&gt;</span> <span class="fu">fit</span>(x, y, <span class="at">epochs =</span> <span class="dv">100</span>, <span class="at">verbose =</span> <span class="dv">0</span>)</span>
<span id="cb104-3"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb104-3" aria-hidden="true" tabindex="-1"></a>y_pred <span class="ot">=</span> model <span class="sc">|&gt;</span> <span class="fu">predict</span>(xnew)</span>
<span id="cb104-4"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y)</span>
<span id="cb104-5"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb104-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(xnew, y_pred, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y)</span>
<span id="cb105-2"><a href="stat-45207520---homework-4-spring-2022-due-april-25-2022.html#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(xnew, y_pred, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-39-1.png" width="672" />
The model fits much better after I added more data for training and let it train for more iterations.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="stat-45207520---homework-3-spring-2022-due-march-30-2022.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="applied-stats-model-ii-lecture-note.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/lyf718718/Book2.git/edit/master/ASM2_HW4.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/lyf718718/Book2.git/blob/master/ASM2_HW4.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
